### ISSUE TITLE
Internet Health Report Onepager

### ISSUE THREAD

**Issue by kitsunenosaraT** [MozillaItalia/Mozilla-Italia-l10n-guide#100]
Questo issue fa parte del progetto di localizzazione di [Internet Health Report](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/projects/6).

In particolare è rivolto a chi desidera tradurre in italiano il documento *onepager* di questa iniziativa Mozilla.
 
## Informazioni sul file da tradurre
**Nome**: 2018 Internet Health Report Onepager
**File**: [Google Drive](https://docs.google.com/document/d/1XgUHamydWJGag5C3xLTx-vLBTXCxske2CevvGrUc4W0/edit) | [Testo in formato markdown](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/InternetHealthReport/IHR_onepager.md) (no immagini, formattazione semplice)
**Tipo**: google docs oppure markdown
**Strumento di traduzione**: A scelta:
- scaricare il file e tradurlo con il proprio editor di testo preferito. Dal menu di Drive: File > Download as > scegli il formato
- scaricare il [testo in formato markdown](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/InternetHealthReport/IHR_onepager.md) e tradurlo con il proprio editor di testo preferito.
- tradurre direttamente su questo [Google doc collaborativo](https://docs.google.com/document/d/1e6KrkgknSh6TNEAtepzftXkh6H9nZJ6VwwmHvLlnSeY/edit) ❕ È necessario possedere un account Google e richiedere l'autorizzazione a modificare il documento

### Parti
- [x] Introduzione - @Sav22999
- [x] Privacy and Security - @eliogi
- [x] Openness - @Sav22999
- [x] Digital Inclusion - @Sav22999
- [x] Web Literacy - @Sav22999
- [x] Decentralization - @Sav22999

#### Prima di iniziare:
* **Leggi i capitoli della guida**, se lo desideri, lascia un feedback nel relativo issue:
  - Capitolo 1 – [Buone norme di traduzione tecnica](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/1-Buone_norme_di_traduzione.md) Feedback: issue #91 
❕ In particolare presta attenzione alla sezione [Billion, Trillion ecc.](https://mozillaitalia.gitbooks.io/l10n-guide/it/1-Buone_norme_di_traduzione.html#billon-trillion-ecc)
  - Capitolo 2 – [Linee guida di Mozilla Italia](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/2-Linee_guida_di_Mozilla_Italia.md) Feedback: issue #27 
  - Capitolo 3 – [Flusso di lavoro](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/3-Flusso_di_lavoro.md) Feedback: issue #24 
 ❕  Leggi solo la parte introduttiva riguardo al ciclo traduzione > revisione, dal  momento che in questo progetto non faremo uso degli strumenti descritti nel resto del capitolo.
  - Capitolo 4 – [Tipi di file](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/4-Tipi_di_file.md) Feedback: issue #31 
  - Capitolo 5  – [Risorse esterne](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/5-Risorse_esterne.md) Feedback: issue #36

#### Prendere in carico il progetto:
* lascia un messaggio nella sezione Commenti, chiedendo che ti venga assegnato il progetto. 
❗️ Il progetto può essere suddiviso tra più traduttori (scrivi nei commenti se desideri tradurne solo una parte e quale.
* attieniti alle indicazioni della guida e, in particolare, fai uso delle [memorie di traduzione di Mozilla](https://transvision.mozfr.org/) per verificare come sono stati tradotti in precedenza i termini. Per le tematiche come *decentralization*, *openness*, *web literacy* ecc. dai un'occhiata a come sono stati tradotti sul sito [Salute di Internet](https://www.mozilla.org/it/internet-health/)
* per qualsiasi problema o domanda scrivi pure in questo issue
* quando la tua traduzione è pronta, lascia un commento nello issue e allega direttamente il file tradotto (trascina il documento nel riquadro del commento), oppure caricalo su un servizio cloud (Google Drive, Dropbox ecc.) e inserisci qui il link.
* **rimani a disposizione per il QA**, ti verrà chiesto se vuoi confermare le modifiche del revisore o meno
* e buona traduzione! 🎊 

## Link Utili
* La [pagina wiki](https://wiki.mozilla.org/Internet_Health_Report) di Internet Health Report
* La [memoria di traduzione](https://transvision.mozfr.org/) di Mozilla, da consultare per garantire consistenza terminologica
* Il sito [Salute di Internet](https://www.mozilla.org/it/internet-health/), tradotto dai volontari di Mozilla Italia, che parla delle stesse tematiche affrontate in Internet Health Report.

**Comment by Sav22999** [comment]
Ovviamente sono interessato a tradurre qualcosa. Non ho preferenze di sessione e, se qualcuno vuole tradurlo tutto, posso benissimo rinunciare e dare spazio a loro :v: buona domenica gente!

**Comment by kitsunenosaraT** [comment]
@Sav22999 Grazie, prode picciotto!
Ho modificato lo issue per aggiungere una lista delle varie parti (i "tasselli" del foglio). Scrivi il tuo nome accanto alla parte che vuoi tradurre, poi procedi con il metodo con cui ti trovi meglio.

**Comment by Sav22999** [comment]
Prendo solo una sezione o posso sceglierne due..? :joy:

**Comment by Sav22999** [comment]
Mi prenoto con l'introduzione, penso di riuscirla a finire entro questo pomeriggio 👍

**Comment by kitsunenosaraT** [comment]
Puoi sceglierne anche più di una, dopotutto a parte il primo, tutti gli altri tasselli sono di poche frasi.
A proposito, per quanto riguarda le varie cifre esorbitanti di questo documento, vi ricordo che abbiamo aggiornato la guida con una [sottosezione apposita](https://mozillaitalia.gitbooks.io/l10n-guide/it/1-Buone_norme_di_traduzione.html#billon-trillion-ecc) che spiega le "trappole" di billion, trillion ecc.
(Questo lo aggiungo anche in cima allo issue)

**Comment by Sav22999** [comment]
A, perfetto. Leggo subito

**Comment by Sav22999** [comment]
Io ho finito la traduzione dell'introduzione. Non ho ben capito il fatto che "le persone nel mondo dicono, insegnano o costruiscono..." però spero che il resto più o meno l'ho fatto bene.
Condivido il link di google docs, nel quale chiunque può mettere dei commenti https://docs.google.com/document/d/1e6KrkgknSh6TNEAtepzftXkh6H9nZJ6VwwmHvLlnSeY/edit?usp=sharing

**Comment by kitsunenosaraT** [comment]
@Sav22999 stavo per dirti che avevo lasciato commenti/suggerimenti, ma vedo che li stai già vagliando 👍 
Ho una proposta, visto che hai già impostato per bene il foglio, possiamo usare quello per la collaborazione.

O, meglio, chi vuole lavorare online può lavorare direttamente su quello, chi preferisce lavorare sul proprio computer si scarica il file, lo traduce e poi posta la sua traduzione (che io provvederò a copia-incollare).

**Comment by Sav22999** [comment]
Certo... L'unica cosa... Io direi di lasciare Internet Health Report... perché è un titolo. Però ditemi voi

**Comment by eliogi** [comment]
Faccio Provacy & Security, così provo il metodo Sara-Saverio

**Comment by eliogi** [comment]
Ho fatto la modifica al paragrafo Privacy & Security, lasciando attiva la funzione suggerimento. Vedete se è incasinata o va bene. Si può sempre accettare tutto e poi correggere.

**Comment by Sav22999** [comment]
Accetto tutto così Sara può procedere al QA

**Comment by kitsunenosaraT** [comment]
Grazie a tutti e due, ragazzi! 👍 
@eliogi Ho lasciato dei commenti, quando vuoi.

C'è un altro problema: come dice il nome "one-pager", il testo dovrebbe stare tutto in un'unica pagina. Quindi, quando abbiamo finito ci sarà un lavoretto di potatura 😁 

@MozillaItalia/l10n Questione: Internet Healt Report… Come tradurlo?
In passato lo avevamo lasciato in inglese perché non avevamo modo di tradurne i contenuti, ma adesso la situazione è cambiata. Una traduzione possibile che aleggiava nell'aria è "Resoconto sullo stato di salute di Internet". Fate sentire le vostre opinioni.

**Comment by flodolo** [comment]
"Rapporto sullo stato di salute di Internet"

**Comment by eliogi** [comment]
Ciao @kitsunenosaraT per me vanno bene le tue modifiche. Puoi accettarle, purtroppo non me le fa accettare a me.

**Comment by kitsunenosaraT** [comment]
@eliogi Grazie per averci riguardato! Neanche io ho la facoltà di approvare i suggerimenti. O @Sav22999 mi investe dei poteri di Editor, oppure devo lasciare a lui l'incombenza.

**Comment by eliogi** [comment]
ok

**Comment by kitsunenosaraT** [comment]
@Sav22999 scusa se oggi continuo a pingarti 😅 
Quando hai tempo, ho messo dei suggerimenti per sfoltire la tua colonna e farla entrare tutta nella prima pagina.

**Comment by Sav22999** [comment]
Certo! Ho appena ricevuto la notifica da google docs. Non preoccuparti, quando è sabato sono libero tutta la giornata

**Comment by Sav22999** [comment]
Mi prenoto per openness

**Comment by Sav22999** [comment]
Potete procedere al QA di openness

**Comment by Sav22999** [comment]
Quale sarebbe la trappola di billions?

**Comment by Sav22999** [comment]
Posso fare la traduzione di un altro pezzo? Vorrei finire questo documento così facciamo le slide :joy:

**Comment by Sav22999** [comment]
mi prenoto per Digital Inclusion

**Comment by kitsunenosaraT** [comment]
@Sav22999 Grazie, il QA è pronto.
P.s. La [trappola di billion](https://mozillaitalia.gitbooks.io/l10n-guide/it/1-Buone_norme_di_traduzione.html#billon-trillion-ecc) sarebbe tradurre con "bilione", che è una cifra di ordine di grandezza parecchio superiore. È un errore che commettono anche in TV a volte.

**Comment by Sav22999** [comment]
Ah, non sapevo cadessero in queste false simililitudini... billion l'ho sempre tradotto con miliardo (se non vado errato è trillion)

**Comment by Sav22999** [comment]
Mi prenoto anche per le ultime 2 sezioni, così terminiamo IHR onepager :)

**Comment by Sav22999** [comment]
Mi ero dimenticato di dare l'OK per la QA. Potete procedere alla QA di entrambe se sezioni :)

**Comment by Sav22999** [comment]
Chiedo scusa se ho commesso molti errori di distrazione, quali il punto/virgola (1,000->1.000) e la "ed" invece di "e"

**Comment by kitsunenosaraT** [comment]
Non preoccuparti, capita a tutti! Vedo che hai già accettato tutto.
Temo che bisognerà tagliuzzare ancora un pochino per far stare tutto nella pagina ✂️ 
Adesso provo...

**Comment by kitsunenosaraT** [comment]
Vediamo adesso!
@eliogi Per ragioni di spazio ho dovuto "sforbiciare" un altro po' anche il tuo tassello, Privacy e sicurezza. Spetta a te decidere se i cambiamenti sono accettabili

**Comment by eliogi** [comment]
@kitsunenosaraT ho approvato. Per me ok, ci sta tutto. ;)

**Comment by Sav22999** [comment]
@eliogi controlla il file perchè ci sono delle modifiche che @kitsunenosaraT ha apportato alla sezione che hai tradotto tu

**Comment by eliogi** [comment]
Ciao @Sav22999 , todo ok, ho fatto.

**Comment by Sav22999** [comment]
Perfetto. :+1:

**Comment by kitsunenosaraT** [comment]
@eliogi e soprattutto @Sav22999 grazie per l'infinita pazienza! E scusate se ho dimenticato di avvisare che avevo lasciato altre modifiche da accettare. 🙇 

Finalmente, anche grazie al suggerimento di Saverio di abbreviare "Creative Commons", riusciamo a stare in una pagina sola.

Ho fatto una copia [sul mio Drive](https://docs.google.com/document/d/1BYneGVDG9GRzSxy65UchgaQ8PnFhdTs-o_pEqOnQZp4/edit?usp=sharing) del documento finale. Ha le seguenti caratteristiche: tutti possono vederlo e scaricarlo, nessuno può modificarlo.
**Useremo questa versione come "distribuzione".**
Ho aggiornato anche l'[indice delle risorse](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/InternetHealthReport/README.md) con la copia italiana.

🔔 Quindi @edovio @Mte90 abbiamo un altro asset pronto!

Passo e chiudo (lo issue).
