### ISSUE TITLE
Translating Common Voice website

### ISSUE THREAD

**Issue by kitsunenosaraT** [MozillaItalia/Mozilla-Italia-l10n-guide#101]
Questo issue si occupa della traduzione della nuova iniziativa Mozilla [Common Voice](https://voice.mozilla.org/en)

## Informazioni sul progetto
**URL** https://voice.mozilla.org/
**URL sito di test** https://voice.allizom.org/it
**Formato di file** `.ftl`
**Strumenti** [Pontoon](https://pontoon.mozilla.org/it/)

#### Prima di iniziare:
* (facoltativo) Presentati nello Issue #20 Introduction (Presentazioni)
* (facoltativo) Rispondi a un breve sondaggio nello Issue #7 Survey on volunteers preferences and expectations

* **Leggi i capitoli della guida**, se lo desideri, lascia un feedback nel relativo issue:
  - Capitolo 1 – [Buone norme di traduzione tecnica](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/1-Buone_norme_di_traduzione.md) Feedback: issue #91 
  - Capitolo 2 – [Linee guida di Mozilla Italia](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/2-Linee_guida_di_Mozilla_Italia.md) Feedback: issue #27 
  - Capitolo 3 – [Flusso di lavoro](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/3-Flusso_di_lavoro.md) Feedback: issue #24 
  - Capitolo 4 – [Tipi di file](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/4-Tipi_di_file.md) Feedback: issue #31 
  - Capitolo 5  – [Risorse esterne](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/5-Risorse_esterne.md) Feedback: issue #36

#### Prendere in carico il progetto:
* Effettua l'accesso a Pontoon e vai al progetto *Common Voice (**[link diretto alle stringhe mancanti](https://pontoon.mozilla.org/it/common-voice/all-resources/?status=missing&string=177872)**]
* traduci quante stringhe vuoi, attenendoti alle istruzioni del [capitolo 3](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/3-Flusso_di_lavoro.md) e del [capitolo 4](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/4-Tipi_di_file.md)
* per qualsiasi problema o domanda scrivi pure in questo issue
* quando la tua traduzione è pronta, lascia un commento nello issue per dare l'OK al QA
* rimani a disposizione per il QA, ti verrà chiesto se vuoi confermare le modifiche del revisore o meno
* e buona traduzione! 🎊 

## Link Utili
* [Stringhe da tradurre](https://pontoon.mozilla.org/it/common-voice/all-resources/?status=missing&string=177872) -- Link diretto al progetto su Pontoon
* [Server di test](https://voice.allizom.org/it) -- Per vedere dove andranno a finire le tue traduzioni direttamente sulla pagina web
* [Memorie di traduzione di Mozilla](https://transvision.mozfr.org/) -- Per ricerche terminologiche (come sono stati tradotti precedentemente prodotti e iniziative Mozilla)
* [mozilla.dev.l10n.web](https://groups.google.com/forum/#!forum/mozilla.dev.l10n.web) -- Un newsgroup internazionale di riferimento per le stringhe della settimana. Condivide informazioni sui progetti correnti, anche utile per porre domande e segnalare bug ecc.

**Comment by eliogi** [comment]
Buongiorno, ho visitato il sito. Interessante davvero! Ho visto al momento il link di test ha un redirect su quello in inglese attuale.

**Comment by edovio** [comment]
Ho iniziato stasera la traduzione tramite pontoon delle stringhe.

**Comment by kitsunenosaraT** [comment]
@edovio rompe il ghiaccio con il nuovo progetto 🎉 
Grazie, ne ho accettato la maggior parte. Domani suggerisco qualche piccolo cambiamento per le rimanenti.

**Comment by Sav22999** [comment]
Io lascio, per il momento, questo progetto agli altri. Così do la possibilita a tutti di collaborare. Se poi avete bisogno di una mano in più contattatemi

**Comment by kitsunenosaraT** [comment]
Innanzittutto ottimo lavoro @edovio ! Ti ringrazio per il tuo impegno.
Ho apportato alcune modifiche. [Eccole qui](https://pontoon.mozilla.org/it/common-voice/all-resources/?status=suggested&string=177874).
Certe sono adeguamenti allo stile Mozilla, certe sono correzioni tecniche, altre sono semplicementi miglioramenti stilistici, infine alcune le ho proprio cambiate dall'originale tenendo in considerazione cosa sarebbe stato meglio sul sito.

Mi dispiace di non poterti fare qui il QA modifica per modifica, purtroppo mi si stanno accumulando revisioni da fare sia dai progetti settimanali sia da IHR 😓 
Ma se non sei d'accordo, o semplicemente non ti è chiara, una qualsiasi modifica, scrivi qui senza farti problemi.

Già emergono due termini di cui vorrei discutere.
1) I "dataset" in gergo sarebbero proprio dei set di dati ottimizzati in un certo modo per l'apprendimento automatico, quindi penso sarebbe meglio lasciarli in originale per evitare confusione. Idee/opinioni?
2) "validare" un clip audio. "Validare" lo usiamo già in ambito AMO, per la revisione dei componenti aggiuntivi. Però qui ci si rivolge all'utente medio che deve semplicemente confermare se un clip è valido o meno. Che ne dite di un termine più user-friendly come valutare / vagliare / smistare / si accettano suggerimenti?

**Comment by eliogi** [comment]
Ciao ho visto che ci sono molte stringhe lunghe... vogliamo provarlo a dividere in più sezioni? Che ne pensate?

**Comment by edovio** [comment]
Ciao @kitsunenosaraT 
Per dataset per me va benissimo lasciarlo come tale, ho voluto però porre una traduzione al fine di poter poi discutere tutti assieme su come, successivamente trattare questo termine.
Per quanto riguarda validare a questo punto utilizzerei confermare. Confermi la clip audio? credo che sia un termine più user-friendly e più affine allo scopo della validazione. 
Che ne pensate?

**Comment by edovio** [comment]
Questa frase: 
We at Mozilla are building a community around voice technology. We would like to stay in touch with updates, new data sources and to hear more about how you're using this data.

Io ho proposto originariamente: 
In Mozilla stiamo costruendo una comunità sulla tecnologia vocale. Ci piacerebbe rimanere in contatto con te con aggiornamenti, nuove fonti di dati e per conoscere come li usi.

@kitsunenosaraT ha proposto:
Mozilla sta radunando una comunità di interessati alle tecnologie vocali. Ci piacerebbe rimanere in contatto con te con aggiornamenti e nuove fonti di dati, ma anche conoscere come usi i dati di Common Voice.

Ma credo che nel complesso mi suoni meglio così:
Mozilla sta radunando una comunità di persone interessate alle tecnologie vocali. Ci piacerebbe rimanere in contatto con te con aggiornamenti e nuove fonti di dati, ma anche per conoscere come usi i dati di Common Voice.

che ne pensate?

**Comment by kitsunenosaraT** [comment]
Io approvo. Inserisci il nuovo suggerimento. Quando hai letto tutto e fatto i cambiamenti che ritieni opportuni, io passo e approvo! 👌

**Comment by edovio** [comment]
Oki :)

**Comment by Mte90** [comment]
Ho tradotto le restanti stringhe ma ne ho lasciate alcune (6) perché sono in legalese. Mi spiego meglio sembrano parti di licenze riguardo i diritti ed è meglio che le traduca chi ha più esperienza per evitare errori :-)

Non vedo l'ora che siano sul sito di sviluppo così da poterlo provare in italiano :-D

**Comment by valtermura** [comment]
Bravi, ovviamente io arrivo sempre in ritardo e sono impegnatissimo su
altri fronti. 😌

 Per ciò che riguarda le parti in "legalese", è bene accertarsi che sia il
caso di tradurle. In OmegaT, per esempio, la licenza non è stata tradotta
per questioni, appunto, legali.

Ciao

Valter
Open source is better!
Sent from my Android device

Il mer 18 apr 2018, 18:32 Daniele Scasciafratte <notifications@github.com>
ha scritto:

**Comment by kitsunenosaraT** [comment]
@Mte90 Wow, già quasi finito! 👍 
Queste stringhe sono un miscuglio inestricabile.
Ti sono capitate le risposte delle FAQ (mentre a Edoardo erano capitate le domande).
Ho fatto [piccole correzioni qua e là](https://pontoon.mozilla.org/it/common-voice/all-resources/?author=mte90net%40gmail.com&string=175857), alcune tenendo presente del contesto in cui appariranno nel sito.
Se trovi una stringa che non è stata accettata ma non ha miei suggerimenti attaccati, vuol dire che ci sto ancora pensando.
Fammi sapere cosa ne pensi, se vuoi cambiare qualcosa, basta che inserisci un nuovo suggerimento.

@valtermura ha ragione, le condizioni legali sono una grossa responsabilità perché potrebbero avere ripercussioni giuridiche. Sarebbe meglio chiedere come fare ai responsabili del progetto.
@edovio tu sei in contatto con loro, vero? Potresti mandarmi il loro indirizzo in privato.

**Comment by Mte90** [comment]
Da quello che vedo sono correzioni minime nella forma e una terminologia legalese migliore (nel tuo qa).

**Comment by edovio** [comment]
Buondì a tutti, anche per quanto riguarda le mie sono correzioni minime, più che in contatto con loro direttamente è un qualcosa che abbiamo seguito dalla sua nascita con @mte90. Addirittura il primo meeting dove si è iniziato a parlare di voice recognition era il European Gathering a Berlino nel 2016. Però sicuramente ci possiamo informare immediatamente per capire questo dettaglio non trascurabile! :)

**Comment by kitsunenosaraT** [comment]
Ragazzi, ho accettato le stringhe che mi avete confermato,

### [ma ne mancano ancora 75](https://pontoon.mozilla.org/it/common-voice/all-resources/?status=missing&string=178232)!

Per gli interessati: fatevi sotto! 😀

**Comment by kitsunenosaraT** [comment]
@Mte90 ho messo suggerimenti alle ultime tue stringhe rimaste. Vuoi darci un'occhiata prima che le accetti?

**Comment by Mte90** [comment]
Vai accetta tutto :-)

**Comment by eliogi** [comment]
Ciao,
questo è il mio [contributo](https://pontoon.mozilla.org/it/common-voice/all-resources/?status=suggested&string=178232).
Ho lasciato quelle [stringhe](https://pontoon.mozilla.org/it/common-voice/all-resources/?status=missing&string=175966) prettamente legali.
@kitsunenosaraT decidi tu come è meglio procedere.

**Comment by kitsunenosaraT** [comment]
Fantastico @eliogi !
Ho lasciato [alcuni suggerimenti](https://pontoon.mozilla.org/it/common-voice/all-resources/?status=suggested&string=178229). Certe stringhe come *Mixed*, *Exit Form* me le sono andate a cercare sul sito e le ho cambiate dopo aver visto il contesto.
Per quanto riguarda quella stringa con l'a capo, si tratta di un errore nel testo sorgente.
Nelle stringhe gli a capo, come i doppi spazi, non dovrebbero esistere. Se ci sono, sono errori che si possono ignorare. In caso si intenda andare a capo, troverai il tag `<br>` o simili.

Per il legalese, provo a mandare una mail a qualcuno, se mi dicono di procedere provo a tradurre io.
Si potrebbe anche inserire la clausola che in caso di ambiguità fa fede il testo in inglese.

**Comment by eliogi** [comment]
Grazie @kitsunenosaraT 
L'esperienza rende elegante molto di più la forma... sono sincero è bello quando si viene corretti e rileggi quella frase in modo più pulito. Thanks so much ;)
Adesso ho approvato. Ok anche per i tuoi interventi allora.

**Comment by Sav22999** [comment]
Posso prendere le ultime stringhe?

**Comment by Sav22999** [comment]
Potete procedere al QA delle lingue
La "n" l'ho tradotta come "e" supponendo fosse l'abbreviazione di "and" (anche se in genere scrivono 'n)

**Comment by kitsunenosaraT** [comment]
@Sav22999 grazie, ho approvato le tue stringhe. Anche se c'erano solo nomi di lingue, non ho trovato nessuna "n" 🤔 
Adesso mancano [2 stringhe](https://pontoon.mozilla.org/it/common-voice/all-resources/?status=suggested&string=178620) (altri nomi di lingua). Le ho tradotte al volo, ma se qualcuno me le rilegge e dà la conferma possiamo arrivare al 100%.

Tra l'altro, non ho ricevuto risposta riguardo le stringhe in legalese, ma sembrano sparite da Pontoon.
Infine...
# Mirate il sito di test in [italiano](https://voice.allizom.org/it) ❗️ 
Se vedete qualche cosa fuori posto, segnalatelo qui, così cambio direttamente le stringhe.

**Comment by Sav22999** [comment]
Per me va bene 👍

**Comment by Sav22999** [comment]
Sara, strano siano sparite le due stringhe "n"... le ho tradotte sicuro... le avranno rimosse?

**Comment by kitsunenosaraT** [comment]
Secondo me sì, perché ne mancano anche altre...

**Comment by Sav22999** [comment]
👍 il sito è fantastico ✌
________________________________

**Comment by Sav22999** [comment]
C'è una lingua non tradotta in Italiano ![](https://i.imgur.com/j30hfdf.png)

**Comment by kitsunenosaraT** [comment]
Si tratta di una delle due stringhe che ho tradotto io oggi, rimaste in sospeso.

**Comment by Sav22999** [comment]
Ah, sorry ????
________________________________

**Comment by Sav22999** [comment]
Eccomi qui :) fatte e potete procedere al QA.

**Comment by kitsunenosaraT** [comment]
Grazie @Sav22999! Finalmente siamo al 100% 🎉

**Comment by kitsunenosaraT** [comment]
Ho corretto un errore di contesto.
Avevamo tradotto la stringa "Spekers" come "Altoparlanti", credendo si riferisse ai componenti per la registrazione. Invece indica il numero di persone che parlano una lingua (vedere la sezione [Lingue](https://voice.mozilla.org/it/languages)). 😅 
Comunque anche il sito di produzione è in italiano ora. Suppongo che per "avviare" le registrazioni vere e proprie, un tot. di persone deva richiedere l'italiano come lingua nel modulo.

**Comment by Sav22999** [comment]
Bene, allora richiediamk tutti subito la lingua italiana, così facciamo numero 😊😊

**Comment by AndyUrbi** [comment]
L'iniziativa è interessante anche se sul forum avevo riscontrato delle reticenze, mi pare a livello di privacy.
@Sav22999 con la registrazione hai avuto la possibilità di richiedere l'italiano? Se così fosse inizio a spammare.

**Comment by Sav22999** [comment]
Nessun problema direttamente da qui https://voice.mozilla.org/it

**Comment by kitsunenosaraT** [comment]
@AndyUrbi ho approvato la tua stringa. Grazie 😄

**Comment by kitsunenosaraT** [comment]
Ciao a tutti!
Dal momento che il grosso del sito Common Voice è stato tradotto e ormai ci sono solo aggiornamenti occasionali di poche stringhe, ho pensato sia più pratico **chiudere questo issue e gestire gli eventuali aggiornamenti futuri nello [issue settimanale](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/projects/5) insieme agli altri porgetti di Pontoon.**

Grazie ancora a tutti coloro che hanno collaborato a tradurre questo sito in tempi da record!
