### ISSUE TITLE
Internet Health Report Slide Deck: Collage Slide 2

### ISSUE THREAD

**Issue by kitsunenosaraT** [MozillaItalia/Mozilla-Italia-l10n-guide#107]
Questo issue fa parte del progetto di localizzazione di [Internet Health Report](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/projects/6).

In particolare è rivolto a chi desidera tradurre in italiano la presentazione in slide di questa iniziativa Mozilla (issue #104 ).
La slide n. 2 consiste in un collage di titoli di articoli di giornale in formato immagine (dunque non modificabili direttamente). Qui di seguito è riportata la trascrizione dei vari titoli.
Chi vuole collaborare, traducendo anche un solo titolo, è il benvenuto. **Leggi istruzioni**
 
## Informazioni sul file da tradurre
**Nome**: IHR 2018 Slide Deck (Slide n. 2)
**File**: [Originale Google Drive](https://docs.google.com/presentation/d/1EDP3DaCOR-rPVqt5TJ-RcHTawzWauUiCl8Cfpl4XDPc/edit#slide=id.p) | [Documento di lavoro collaborativo Google Drive](https://docs.google.com/presentation/d/1MSXheT1x-me32F9NQ6LMvz-1GV5_ZcEQiJ0ade0YhYE/edit?usp=sharing)
**Tipo**: immagine
**Strumento di traduzione**: Inserire la traduzione direttamente nei commenti dello issue.

### Parti
- [x] Titolo 1: Google, Mozilla, And the Race to Make Voice Data for Everyone - @joyrom 
- [x] Titolo 2: Personal data of a billion Indians sold online for £6, report claims - @joyrom
- [x] Titolo 3: THE FAKE NEWS CULPRIT NO ONE WANTS TO IDENTIFY: YOU - @joyrom
- [x] Titolo 4: Amnesty reveals alarming impact of online abuse against women - @joyrom
- [x] Titolo 5: We can't reach the U.N. goals of sustainable development without the internet - @joyrom
- [x] Titolo 6: Can Washington Stop Big Data Companies? Don't Bet on It - @joyrom
- [x] Titolo 7: When Citizens Rejected a Ban on WhatsApp and Telegram, Afghan Officials Backed Down - @joyrom
- [x] Titolo 8: We're all connected now, so why is the internet so white and western? - @joyrom
- [x] Titolo 9: Internet shutdowns are costing African governments more than we thought - @joyrom
- [x] Titolo 10: Germany bans children's smartwatches - @joyrom
- [x] Titolo 11: UK hospitals hit with massive ransomware attack / Sixteen hospitals shut down as a result of the attack - @joyrom
- [x] Titolo 12: Women in Senegal are smashing steretypes and taking charge of a blooming tech industry - @joyrom

## Istruzioni
* Scegli il titolo che vuoi tradurre e scrivi nei commenti dello issue il numero del titolo (oppure metti il tuo nome tra parentesi accanto al titolo in cima allo issue - usa l'icona della matita in alto a destra per modificare lo issue).
* per qualsiasi problema o domanda scrivi pure in questo issue.
* quando la tua traduzione ti soddisfa, copiala nei commenti.
* **rimani a disposizione per il QA**, ti verrà chiesto se vuoi confermare le modifiche del revisore o meno
* e buona traduzione! 🎊 

## Link Utili
* La [pagina wiki](https://wiki.mozilla.org/Internet_Health_Report) di Internet Health Report
* La [memoria di traduzione](https://transvision.mozfr.org/) di Mozilla, da consultare per garantire consistenza terminologica
* Il sito [Salute di Internet](https://www.mozilla.org/it/internet-health/), tradotto dai volontari di Mozilla Italia, che parla delle stesse tematiche affrontate in Internet Health Report.

**Comment by joyrom** [comment]
Titolo 4: Amnesty rivela un impatto allarmante di abusi on-line contro le donne

**Comment by joyrom** [comment]
Titolo 2: I dati di milioni di indiani venduti online per 6 euro

**Comment by joyrom** [comment]
Titolo 5: Non possiamo raggiungere gli obiettivi delle Nazioni Unite di sviluppo sostenibile senza Internet

**Comment by joyrom** [comment]
Titolo 10: La Germania vieta gli smartwatch per i bambini

**Comment by joyrom** [comment]
Titolo 8: Ormai siamo tutti connessi, come mai Internet è ancora così "bianca" e occidentale?

**Comment by joyrom** [comment]
Titolo 6: Può Washington fermare le grandi aziende tecnologiche? Non ci scometterei

**Comment by joyrom** [comment]
Titolo 9: Il blocco di Internet costa ai Governi africani più di quanto si pensa

**Comment by joyrom** [comment]
Titolo 1: Google, Mozilla, e la corsa per rendere i dati vocali accessibili per tutti

**Comment by joyrom** [comment]
Titolo 7: Quando i cittadini rifiutano il blocco di WhatsApp e Telegram, gli ufficiali afghani arretrano

**Comment by joyrom** [comment]
Titolo 11: Gli ospedali britannici colpiti da un massiccio attacco ransomware / Sedici ospedali bloccati come conseguenza dell'attacco

**Comment by joyrom** [comment]
Titolo 12: Le donne in Senegal abbattono gli stereotipi e prendono in carico la nascente industria tecnologica

**Comment by joyrom** [comment]
> Davvero ottimo lavoro @joyrom Mi piace come hai mantenuto un registro giornalistico ￼

Grazie Sara

> Titolo 3: IL COLPEVOLE DELLE FAKE NEWS CHE NESSUNO VUOLE IDENTIFICARE: TU
>> IL COLPEVOLE DELLE FAKE NEWS CHE NESSUNO VUOLE IDENTIFICARE: TE

Mi piace di più TU

> Titolo 8: Ormai siamo tutti connessi, come mai Internet è ancora così "bianca" e occidentale?
>> Ormai siamo tutti connessi, come mai Internet è ancora così "bianco" e occidentale?
> Ci sono opinioni contrastanti, ma a Mozilla Italia Internet lo consideriamo maschile.

Mi verrà un po' complicato, ho sempre visto Internet come la Rete, quindi femminile, ma se è questa la linea prevalente cercherò di ricordarmi per il futuro.

Per il resto concordo

**Comment by kitsunenosaraT** [comment]
OK @joyrom grazie per aver riguardato il QA. Per la 3 ti do ragione.
Ricapitolo qui le soluzioni finali:

Titolo 1: Google, Mozilla, e la corsa per rendere i dati vocali accessibili a tutti
Titolo 2: I dati personali di un miliardo di indiani venduti online per 6 dollari
Titolo 3: IL COLPEVOLE DELLE FAKE NEWS CHE NESSUNO VUOLE IDENTIFICARE: TU
Titolo 4: Amnesty rivela l'allarmante impatto degli abusi online contro le donne
Titolo 5: Le Nazioni Unite non possono raggiungere i loro obiettivi di sviluppo sostenibile senza Internet
Titolo 6: Può Washington fermare le aziende dei Big Data? Non scommetterci
Titolo 7: Quando i cittadini insorgono contro il blocco di WhatsApp e Telegram, il governo afgano fa un passo indietro.
Titolo 8: Ormai siamo tutti connessi, come mai Internet è ancora così "bianco" e occidentale?
Titolo 9: Il blocco di Internet costa ai governi africani più di quanto si pensi
Titolo 10: La Germania vieta l'uso degli smartwatch ai bambini 
Titolo 11: Ospedali britannici colpiti da un massiccio attacco ransomware / Sedici ospedali bloccati in seguito all'attacco
Titolo 12: Le donne in Senegal abbattono gli stereotipi e prendono in carico la nascente industria tecnologica 

Appena ho tempo trascriverò le tue traduzioni nella slide 2, poi metterò qui il link in modo che tu possa ammirare il tuo operato. 😄

**Comment by kitsunenosaraT** [comment]
@joyrom Ecco una prima bozza del [collage in italiano](https://docs.google.com/presentation/d/1MSXheT1x-me32F9NQ6LMvz-1GV5_ZcEQiJ0ade0YhYE/edit#slide=id.g3371ea11e0_2_20) (slide 2).
Non ho dovuto alterare nessun testo, c'è stato tutto.
Che ne pensi?

**Comment by joyrom** [comment]
Bene, mi piace. Ho notato solo una stranezza quando metti le slide in modalità "presentazione", la 6 e la 8 si sovrappongono

**Comment by kitsunenosaraT** [comment]
@joyrom Hai buon occhio. Ora dovrebbe essere [sistemato](https://docs.google.com/presentation/d/1MSXheT1x-me32F9NQ6LMvz-1GV5_ZcEQiJ0ade0YhYE/edit#slide=id.g3371ea11e0_2_20)

**Comment by joyrom** [comment]
Sì @kitsunenosaraT, ora si vede bene

**Comment by kitsunenosaraT** [comment]
Perfetto, grazie mille! Chiudo questo issue.
