### ISSUE TITLE
Translating Firefox Monitor Website

### ISSUE THREAD

**Issue by kitsunenosaraT** [MozillaItalia/Mozilla-Italia-l10n-guide#136]
Questo issue si occupa della traduzione del nuovo sito [Firefox Monitor](https://monitor.firefox.com/)

# Stringhe da tradurre
- [x] [app](https://pontoon.mozilla.org/it/firefox-monitor-website/app.ftl/?status=missing%2Cfuzzy%2Cerrors&string=191981) 112 stringhe @Sav22999 + @flodolo 
- [x] [data classes](https://pontoon.mozilla.org/it/firefox-monitor-website/app.ftl/?status=missing%2Cfuzzy%2Cerrors&string=191981) 115 stringhe @flodolo
- [x] [email strings](https://pontoon.mozilla.org/it/firefox-monitor-website/email-strings.ftl/?status=missing%2Cfuzzy%2Cerrors&string=192044) 28 stringhe - @AndyUrbi 

## Informazioni sul progetto
**URL** https://monitor.firefox.com/
**URL sito di test** https://fx-breach-alerts.herokuapp.com/
**Formato di file** `.ftl`
**Strumenti** [Pontoon](https://pontoon.mozilla.org/it/)

## Istruzioni
Per questo progetto dovremo usare un approccio sperimentale.
Invece di suddividere il progetto in sottoparti (cosa che nell'ultimo progetto simile non ha funzionato), il traduttore è libero di tradurre le stringhe che vuole e poi richiedere in questo issue il QA (che verrà eseguito filtrando i risultati per utente).
Per evitare sovrapposizioni con altri traduttori, meglio segnalare sul gruppo Telegram L10n quando si sta lavorando al progetto e su che parte (app, data classes o email strings).
Se dovessero esserci problemi o si trovasse una soluzione più funzionale, le istruzioni cambieranno di conseguenza.

Grazie per la pazienza e buona traduzione!

**Comment by AndyUrbi** [comment]
Ok, proviamo a fare le 28....

**Comment by Sav22999** [comment]
Mi butto un po' sulle "app", parto da sopra

**Comment by Sav22999** [comment]
Ok, per oggi ho finito. Potete procede al QA delle mie stringhe. Grazie

**Comment by flodolo** [comment]
@Sav22999 
Puoi dare un'occhiata ai [suggerimenti in sospeso](https://pontoon.mozilla.org/it/firefox-monitor-website/app.ftl/?status=unreviewed&author=saverio.morelli%40outlook.it&string=191829)?

In general, credo sia il caso di concordare su alcune traduzioni prima di procedere.

**subscribe**: iscriversi, sottoscrivere
**unsubscribe**: annulllare/cancellare/rimuovere iscrizione/sottoscrizione
**data breaches**: violazioni dei/di dati

Nei miei suggerimenti ho scelto iscriversi, annullare iscrizione, violazione di dati. "Violazioni" da solo non va bene, è il caso di aggiungere sempre "di dati.

I titoli con i due punti e lo spazio dovrebbero usare sostantivi senza articoli, visto che sono titoli.

P.S. attiva il correttore ortografico

**Comment by flodolo** [comment]
Comincio a tradurne alcune anche io (app.ftl)

**Comment by Sav22999** [comment]
Esattamente non sapevo se usare sottoscrivere o iscrivere. Nella cronologia abbiamo usato più sottoscrivere, ma nel caso specifico credo sia più corretto iscrivere. Quindi ho inserito entrambi i suggerimenti ?? dopo le guardo, ora sono a lezione, perdonatemi
________________________________

**Comment by Sav22999** [comment]
(Inoltre il controllo ortografico era attivo... forse si è disattivato con l'aggiornamento. Verifico quando torno a casa questa sera, scusa!)
________________________________

**Comment by flodolo** [comment]
Mi sono fatto prendere la mano e le ho tradotte tutte (pronte per il QA).

Rimane *data classes* da tradurre.

**Comment by flodolo** [comment]
Ulteriori correzione: in alcuni casi ho usato "violazione" da solo, ma solo dove il contesto era chiaro.

**Comment by flodolo** [comment]
Tradotto anche un po' del file rimanente, pronto per il QA anche quello.

**Comment by Sav22999** [comment]
Io ho accettato tutti i suggerimenti @flodolo escluso questo https://pontoon.mozilla.org/it/firefox-monitor-website/app.ftl/?status=missing%2Cfuzzy%2Cerrors&string=191977, credo di aver interpretato male: è un titolo, non è un avviso. Fammi sapere. Grazie mille dei suggerimenti e della pazienza

**Comment by flodolo** [comment]
> Io ho accettato tutti i suggerimenti @flodolo escluso questo https://pontoon.mozilla.org/it/firefox-monitor-website/app.ftl/?status=missing%2Cfuzzy%2Cerrors&string=191977, credo di aver interpretato male: è un titolo, non è un avviso. Fammi sapere. Grazie mille dei suggerimenti e della pazienza

Esatto, è un titolo, per cui meglio usare un sostantivo.

> Firefox Monitor : Unsubscribe

La tua traduzione (`{-product-name} : Iscrizione annullata`) andrebbe bene per Unsubscribe**d**

**Comment by Sav22999** [comment]
@flodolo si, infatti ho corretto in "Annulla iscrizione" perché anche tu avevi corretto con "Sottoscrizione annullata" :) cosa ne pensi?

**Comment by flodolo** [comment]
> @flodolo si, infatti ho corretto in "Annulla iscrizione" perché anche tu avevi corretto con "Sottoscrizione annullata" :) cosa ne pensi?

Ah, non avevo capito. "Annullamento iscrizione" è orribile, per cui direi che va bene "Annulla iscrizione".

**Comment by Sav22999** [comment]
:+1: perfetto. :) grazie mille del tempo dedicato al QA (e anche dopo) e buona giornata

**Comment by flodolo** [comment]
> Ho riguardato le mie, direi che si possa procedere al QA.

Mi ero perso questa. Puoi dare un'occhiata ai [suggerimenti in sospeso](https://pontoon.mozilla.org/it/firefox-monitor-website/email-strings.ftl/?string=192044)?

Alcune note:
* Niente maiuscole in mezzo alla frase (es. "Email"), apostrofi ’ invece di '
* Ho usato "violazioni di dati" invece di "violazioni dei dati", visto che è la forma utilizzata in tutte le altre stringhe.
* Attenzione alla consistenza: se "Report" è "Rapporto" in una stringa, non dovrebbe diventare "Segnalazione" poco dopo.
* Se ci sono variabili nell'inglese, normalmente devono essere mantenute (es. il numero di breach). Stesso discorso per gli a capo nel testo (shift+invio in Pontoon).

P.S. quanto traducete, date un'occhiata alla scheda MACHINERY. Google Translate è davvero accurato, e in alcuni casi può darvi un'idea di come tradurre alcuni termini.

**Comment by AndyUrbi** [comment]
1. Per la maiuscola ho pensato fosse come nei casi che usiamo Web in maiuscolo.
2. ok per violazioni DI dati
3. ok per Rapporto
4. sulle variabili non ho capito anche se la prima opzione, quella con lo zero, ieri non ci fosse, o perlomeno non riuscivo a vederla. Ti riferisci a quello? Ai ritorno a capo non ci avevo fatto caso, colpa mia.
Personalmente la scheda Machinery la uso sempre perché mi risparmia di scrivere la maggior parte delle parole, e un controllo lo faccio anche su Google. Ho capito molto meno, anzi forse non ho capito affatto, come sfruttare Transvision.
Puoi accettare praticamente tutto, ma ho modificato ulteriormente questa:
https://pontoon.mozilla.org/it/firefox-monitor-website/email-strings.ftl/?string=192006
e questa:
https://pontoon.mozilla.org/it/firefox-monitor-website/email-strings.ftl/?string=192042
Infine un chiarimento per questa:
https://pontoon.mozilla.org/it/firefox-monitor-website/email-strings.ftl/?string=192041
con la tua traduzione sembra che i siti abbiano una coscienza propria mentre il controllo, come ho scritto io, si attua tramite programmazione, quindi più attinente. Cosa ne pensi?

**Comment by AndyUrbi** [comment]
Dimenticavo gli apostrofi! Quindi **mai** quello della tastiera ma...?

**Comment by flodolo** [comment]
>         Puoi accettare praticamente tutto, ma ho modificato ulteriormente questa:
>         https://pontoon.mozilla.org/it/firefox-monitor-website/email-strings.ftl/?string=192006

Non sono convintissimo dell'inciso, mi sembra che renda la frase meno leggibile? Oltretutto, se lo togli la frase non ha più senso, e non dovrebbe essere il caso per un inciso.

>         e questa:
>         https://pontoon.mozilla.org/it/firefox-monitor-website/email-strings.ftl/?string=192042

Accettata la tua versione.

>         Infine un chiarimento per questa:
>         https://pontoon.mozilla.org/it/firefox-monitor-website/email-strings.ftl/?string=192041

Direi che ha senso (anche *accurate* invece di *corrette*). Accettata la tua versione (ho dovuto reinserirla, non c'era un a capo tra le due frasi).

**Comment by flodolo** [comment]
> Dimenticavo gli apostrofi! Quindi **mai** quello della tastiera ma...?

L'apostrofo tipografico (credo che ci siano indicazioni nella guida per ottenerlo su Windows e Linux, su macOS è cmd+shift+3 con il layout di tastiera italiano).

`'`-> sbagliato 
`’` -> corretto

Ho dimenticato di rispondere a un pezzo

> sulle variabili non ho capito anche se la prima opzione, quella con lo zero, ieri non ci fosse, o perlomeno non riuscivo a vederla. Ti riferisci a quello? 

Lo zero mancante è un bug di Pontoon, bisogna [girarci intorno](https://groups.google.com/d/msg/mozilla.dev.l10n/iHn_kJ1ta88/sS0zLXI0AwAJ) per farlo apparire.

Sulle variabili mi riferivo a [questa stringa](https://pontoon.mozilla.org/it/firefox-monitor-website/email-strings.ftl/?string=191849). Per *other* (plurale) hai tradotto `Il tuo account è apparso in altre violazioni.`, perdendo la variabile con il numero.

**Comment by kitsunenosaraT** [comment]
Siete stati davvero rapidi ed effiicenti con questo sito 🥇 
@flodolo ecco il [QA di App](https://pontoon.mozilla.org/it/firefox-monitor-website/app.ftl/?status=unreviewed&string=191890). Ho solo messo qualche suggerimento che mi sembra un po' più indicato in contesto, ma le originali vanno già benissimo.
Più tardi mi occupo del resto.

**Comment by kitsunenosaraT** [comment]
Ecco qui [Suggerimenti per Data Classes](https://pontoon.mozilla.org/it/firefox-monitor-website/data-classes.ftl/?status=unreviewed&string=191967): alcune cose sono un po' dubbiose, lascio alla tua interpretazione finale. Poi credo sia rimasta da revisionare solo una controproposta di AndyUrby in Email strings. 

Ps. Ho visto che ci sono nuove stringhe per la settimana, aprirò più tardi lo issue apposito.

**Comment by kitsunenosaraT** [comment]
> Vedi un paio di commenti sopra

Ok!



>URL delle home page
L'home page è una, sono gli URL plurale. "Indirizzi delle home page"?

Penso sia meglio la tua iniziale "URL della home page" (più specifico.

>Nomi utente (nickname)
Il nome utente è una cosa diversa dal nickname, secondo me rischiamo di creare confusione.

Allora sono un po' confusa… cosa intendiamo per nickname?
Sembra che la violazione riguardi i soprannomi che ti affibbiano gli amici.
Forse semplicemente "Nickname"?

**Comment by flodolo** [comment]
Il nome utente lo usi per accedere a un sistema o un sito, il nickname è un soprannome che usi su social, ecc.

> A user-friendly name displayed in place of a network location, e-mail address, contact name, or other, more formal name.

**Comment by flodolo** [comment]
@AndyUrbi 
Per ora ho approvato la [versione senza inciso](https://pontoon.mozilla.org/it/firefox-monitor-website/email-strings.ftl/?search=breach-alert-subhead&string=192006), possiamo comunque cambiarla più avanti ;-)

**Comment by kitsunenosaraT** [comment]
> Il nome utente lo usi per accedere a un sistema o un sito, il nickname è un soprannome che usi su social, ecc.

In effetti nome utente e nickname non coincidono sempre, non ci avevo pensato.
Comunque, mi è venuto in mente adesso, "Pseudonimi (nickname)" mi sembra più appropriato, visto che lo pseudonimo è un nome che scegli tu per non rivelare la tua vera identità, mentre il soprannome è di solito qualcosa che ti attribuiscono gli altri.
Ho messo un suggerimento. Comunque per me anche "Nickname" da solo è accettabile.

**Comment by flodolo** [comment]
Accettata. Vogliamo lasciare questa issue aperta per il QA?

**Comment by AndyUrbi** [comment]
Mi sto impegnando a cercare quel _maledetto_ apostrofo curvo e, naturalmente, ho ripescato la vostra discussione al riguardo.
https://forum.mozillaitalia.org/index.php?topic=59061.0
Sebbene in un sito sia indicata la combinazione `AltGr + ,,` che diventa così `´ `nella vostra discussione c'era il link a Wikipedia che riporta `AltGr + shift + b` che diventa così `’`

Ci capisco ancora meno....

**Comment by flodolo** [comment]
Il secondo è corretto, il primo è un altro carattere (tick?)

**Comment by AndyUrbi** [comment]
Già. Peccato perché il primo sarebbe quello che si ricorda meglio :smile:

**Comment by AndyUrbi** [comment]
Questa direi che si può chiudere, che ne dici @kitsunenosaraT ?

**Comment by kitsunenosaraT** [comment]
Chiudiamo, dato che Firefox Monitor è passato nello issue settimanale di Pontoon.
