### ISSUE TITLE
Weekly Traslation for Pontoon Projects (Week 49)

### ISSUE THREAD

**Issue by Sav22999** [MozillaItalia/Mozilla-Italia-l10n-guide#144]
# Stringhe della settimana
- [x] [AMO](https://pontoon.mozilla.org/it/amo/all-resources/?status=missing) 5 stringhe - @AndyUrbi 
- [x] [Firefox Accounts](https://pontoon.mozilla.org/it/firefox-accounts/all-resources/?status=missing&string=192951) 5 stringhe - @Sav22999
- [x] [mozilla.org](https://pontoon.mozilla.org/it/mozillaorg/all-resources/?status=missing) 27 stringhe (scadenza 13 dicembre) - @dag7dev
- [x] [Firefox for iOS](https://pontoon.mozilla.org/it/firefox-for-ios/all-resources/?status=missing) 25 stringhe (scadenza 11 gennaio) - @Sav22999 
- [x] [Firefox Monitor Website](https://pontoon.mozilla.org/it/firefox-monitor-website/all-resources/?status=missing&string=193003) 11 stringhe - @AndyUrbi 
- [ ] [Thimble](https://pontoon.mozilla.org/it/thimble/all-resources/?status=missing&string=193417) 36 stringhe - @eliogi 
- [x] [AMO (2)](https://pontoon.mozilla.org/it/amo/all-resources/?status=missing&string=193408) 7 stringhe - @Sav22999

❗️  La lista delle stringhe da tradurre viene aggiornata più volte nell'arco della settimana

## Informazioni sul progetto
Questo issue serve a gestire le traduzioni dei siti Mozilla sulla piattaforma [Pontoon](https://pontoon.mozilla.org/it/).

Ogni settimana uscirà un nuovo issue con una lista dei progetti che contengono stringhe mancanti. Puoi sempre trovare lo issue della settimana corrente sulla [bacheca del progetto](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/projects/5).
Chi vuole farsi avanti, a seconda della propria disponibilità, si "prenoterà" per le stringhe.
Questo per organizzare meglio l'attività di traduzione ed evitare che più persone lavorino sulle stesse stringhe.

#### Prima di iniziare:
* [Registrati](https://accounts.firefox.com/oauth/signin?response_type=code&scope=profile%3Auid%20profile%3Aemail%20profile%3Adisplay_name%20profile%3Auid%20profile%3Adisplay_name%20profile%3Aemail&state=yrvTUh3o4F4c&redirect_uri=https%3A%2F%2Fpontoon.mozilla.org%2Faccounts%2Ffxa%2Flogin%2Fcallback%2F&client_id=76ab66239b5585ad) sulla piattaforma di traduzione Pontoon
  - (facoltativo) Installa il componente aggiuntivo [Pontoon Tools](https://addons.mozilla.org/it/firefox/addon/pontoon-tools/) per ricevere le notifiche delle stringhe mancanti in tempo reale (più altre chicche)
* **Leggi i capitoli della guida**, se lo desideri, lascia un feedback nel relativo issue:
  - Capitolo 1 – [Buone norme di traduzione tecnica](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/1-Buone_norme_di_traduzione.md) Feedback: issue #91 
  - Capitolo 2 – [Linee guida di Mozilla Italia](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/2-Linee_guida_di_Mozilla_Italia.md) Feedback: issue #138
  - Capitolo 3 – [Flusso di lavoro](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/3-Flusso_di_lavoro.md) Feedback: issue #24 
  - Capitolo 4 – [Tipi di file](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/4-Tipi_di_file.md) Feedback: issue #31 
  - Capitolo 5  – [Risorse esterne](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/5-Risorse_esterne.md) Feedback: issue #36

#### Prendere in carico il progetto:
* lascia un messaggio nella sezione Commenti, scrivendo di quale progetto vuoi occuparti (importante per avvisare gli altri che ci stai lavorando tu). Scrivi anche il tuo nome utente accanto al nome del progetto sulla lista qui in alto (usa l'icona della matita per modificare il testo)
* attieniti alle istruzioni del [capitolo 3](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/3-Flusso_di_lavoro.md) e del [capitolo 4](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/4-Tipi_di_file.md)
* per qualsiasi problema o domanda scrivi pure in questo issue
* quando la tua traduzione è pronta, lascia un commento nello issue per dare l'OK al QA
* rimani a disposizione per il QA, ti verrà chiesto se vuoi confermare le modifiche del revisore o meno
* e buona traduzione! 🎊 

## Link Utili
* [Web Localization Dashboard](https://l10n.mozilla-community.org/webdashboard/?locale=it) -- Lista dei progetti Pontoon con relative scadenze
* Server di test -- Per vedere dove andranno a finire le vostre traduzioni
  - per le singole pagine di [mozilla.org](https://l10n.mozilla-community.org/langchecker/?action=listpages) 
  - per [AMO](https://addons-dev.allizom.org/it/)
  - per [MDN](https://developer.allizom.org/it/)
  - per [Test Pilot](https://testpilot-l10n.dev.mozaws.net/)
  - per [Common Voice](https://voice.allizom.org/it)
  - per [Thunderbird.net](https://www.thunderbird.net/it/) *sito produzione
* [mozilla.dev.l10n.web](https://groups.google.com/forum/#!forum/mozilla.dev.l10n.web) -- Un newsgroup internazionale di riferimento per le stringhe della settimana. Condivide informazioni sui progetti correnti, anche utile per porre domande e segnalare bug ecc.

**Comment by Sav22999** [comment]
Potete procere al QA di Ffx Accounts

**Comment by AndyUrbi** [comment]
@Sav22999 Mi sono permesso di guardarle e credo ci sia ben poco da dire. Secondo me potresti auto-approvartele ma so che non lo faresti mai :smile: 
Nel frattempo mi sono fatto quelle di AMO: ci daresti una occhiata? Ho ricamato un pò ma credo di essermi avvicinato meglio alla nostra lingua.

**Comment by Sav22999** [comment]
Immagino anche flodolo abbia lavori da sbricare... immagino che possano rimanere invariati... mi prenoto io e lo riporto uguali. Nel caso è sufficiente solo approvarle, dai

**Comment by Sav22999** [comment]
Rettifico. Non si può tradurre 😂😂 @flodolo dovrà spiegarci la motivazione.

**Comment by Sav22999** [comment]
@AndyUrbi mi fa piacere che tu le abbia guardate e anzi, non farti problemi, correggimi pure nel caso 😁

**Comment by flodolo** [comment]
Firefox per Android, come Firefox, non viene tradotto via Pontoon. Ignoratelo, quella stringa non manca (è Pontoon che non sa di doverla ignorare) ;-)

**Comment by AndyUrbi** [comment]
> Rettifico. Non si può tradurre.

La prossima volta che metti in dubbio quello che dico @Sav22999 ti faccio mettere una nota sul registro.
Per punizione vai al vecchio issue ad accettare e poi mettere la spunta alle mie fuzzy. Inoltre devi mettere questo issue in questa pagina:
https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/projects/5

PS: scherzo anche io.

**Comment by Sav22999** [comment]
@AndyUrbi le accetto subito e inserisco anche l'issue nel project.
@flodolo allora è colpa mia... non sapevo. Però altre volte abbiamo tradotto su Pontoon Firefox for Android 🤔 boh

**Comment by flodolo** [comment]
>  @flodolo allora è colpa mia... non sapevo. Però altre volte abbiamo tradotto su Pontoon Firefox for Android 🤔 boh

Fidati, no. Non è mai stato attivo, l'abbiamo attivato un paio di mesi fa quando è stata aggiunta la modalità sola lettura.

**Comment by Sav22999** [comment]
No, certo. Ricordo male allora... :) rimuovo le stringhe dall'issue

**Comment by flodolo** [comment]
(approvato io FxA)

**Comment by AndyUrbi** [comment]
@flodolo visto che sei disponibile ci sarebbe da guardare quelle di Saverio della settimana passata.

**Comment by Sav22999** [comment]
Potete procedere al QA anche di Firefox for iOS :)
(comunque @flodolo ora che ci penso quello che ricordavo era Focus for Android)

**Comment by flodolo** [comment]
Disponibile è una parola grossa (sono negli USA, e mi sto addormentando sulla tastiera) ;-)

Vedo se riesco a dargli un'occhiata.

**Comment by flodolo** [comment]
> Potete procedere al QA anche di Firefox for iOS :)

Ricordati di controllare MACHINERY, in 2/3 casi c'erano corrispondenza da prodotti già tradotti in italiano.

**Comment by Sav22999** [comment]
https://pontoon.mozilla.org/it/firefox-for-ios/all-resources/?status=missing&string=193229 qui avevo utilizzato la forma "Effetto > procedura piuttosto che Procedura > effetto."
Il resto delle stringhe le ho approvate tutte quante.

**Comment by flodolo** [comment]
> https://pontoon.mozilla.org/it/firefox-for-ios/all-resources/?status=missing&string=193229 qui avevo utilizzato la forma "Effetto > procedura piuttosto che Procedura > effetto."
> Il resto delle stringhe le ho approvate tutte quante.

È una delle stringhe che apparivano in Machinery, ma non riesco a capire da dove venga.

> Per continuare è necessario aprire Firefox ed effettuare l’accesso dalle impostazioni.

Non credo sia corretta (Firefox è già aperto). "Per continuare è necessario aprire le impostazioni di Firefox ed effettuare l’accesso." potrebbe funzionare, ma trovo "Apri le impostazioni di Firefox ed effettua l’accesso per continuare." più leggibile.

**Comment by Sav22999** [comment]
Certo, va bene 😁 io avevo applicato solo la regola. Accetto anche questa frase, allora 👍 grazie del QA e ti lascio libero, immagino tu abbia somno o altro da fare 😁😁

**Comment by AndyUrbi** [comment]
Si può procedere al QA di AMO e mi prendo il rimanente.

**Comment by Sav22999** [comment]
Caspita! Abbiamo già finito questa settimana. Perfetto :+1:

**Comment by Sav22999** [comment]
@AndyUrbi QA di AMO fatto. Aspetto riscontro :)

**Comment by AndyUrbi** [comment]
Puoi accettare tutto e mettere la spunta su AMO.
Pronto per il QA di FF Monitor.

**Comment by Sav22999** [comment]
@AndyUrbi Detto fatto :)
AMO Accettate e QA di Ffx Monitor fatto :) ho lasciato alcuni suggerimenti e approvato alcune frasi.

**Comment by AndyUrbi** [comment]
Le accetto tutte tranne questa:
https://pontoon.mozilla.org/it/firefox-monitor-website/all-resources/?status=missing&string=193007
Scritta così sembra che puoi scoprire violazioni dei dati anche sugli account degli altri. Per la prima parte ok, ma per quella dopo il punto perché non attenersi all'originale?

**Comment by dag7dev** [comment]
Potete procedere al QA. Ero fortemente indeciso se tradurre o no lo slogan in inglese così ho suggerito entrambe :)

**Comment by Sav22999** [comment]
@AndyUrbi scusa se rispondo solo ora. Ho aggiornato :) cosa ne pensi ora?

**Comment by Sav22999** [comment]
@dag7dev Scusami anche tu per l'orario.
Dunque ho fatto il QA di mozilla.org.
Non mi convince molto questa frase... https://pontoon.mozilla.org/it/mozillaorg/all-resources/?status=missing&string=192980... tradotta "letteralmente" non dà molto significato...
Ho lasciato alcuni suggerimenti e approvato alcune stringhe. Attendo tuo riscontro :) Notte

**Comment by AndyUrbi** [comment]
Ok @Sav22999 il mio lo puoi approvare. Scusa se ti ho fatto fare tardi ma io a quell'ora non ero più in grado di dare alcun suggerimento.
Sai, alla mia età... vedi Flodolo l'altra sera :smile:

**Comment by Sav22999** [comment]
@AndyUrbi ahahah. Nessun problema. L'età che conta è quella interna, non quella esterna.
Approvata e "tickettata"

**Comment by dag7dev** [comment]
@Sav22999 sto guardando il QA:
- Sul QR metterei subito il nome dell'applicazione (senza usare esplicitamente la parola "applicazione", in fine dei conti scannerizzi il QR per fornire di un certo servizio)
- [https://pontoon.mozilla.org/it/mozillaorg/firefox/accounts-2018.lang/?string=192991 ](questa qui) l'ho tradotta con "i tuoi contenuti" poiché "metti contenuti di qualità" non aveva senso secondo me, totalmente decontestualizzata...

- per [https://pontoon.mozilla.org/it/mozillaorg/all-resources/?status=missing&string=192980](questa) frase, l'ho voluta tradurre così poiché appunto sta a significare "universalità" e volevo intendere qualcosa come "porta i tuoi dati sempre con te" 

A parte queste cosine qui puoi procedere al merging ^^

**Comment by Sav22999** [comment]
@dag7dev 

2 - in inglese c'è "quality content" presumo intenda che carichi su pocket solo ciò che ritieni "di qualità"
3 - Sì, capisco. Però personalmente non reputo abbia molto senso "Porta la tua vita con te" ... io la riformulerei. Nel caso, chiedo l'intervento del capo supremo :)

(1 -) Per il problema delle app chiedo l'intervento di @kitsunenosaraT.

**Comment by Sav22999** [comment]
Nuove stringhe @eliogi ti ho assegnato il tuo progetto (Thimble).
Io mi sono "auto-assegnato" AMO :) spero non vi dispiaccia: sono poche stringhe

**Comment by Sav22999** [comment]
Potete procedere al QA di AMO

**Comment by kitsunenosaraT** [comment]
@Sav22999 Grazie (anche per tutto il lavoro di revisione).
Ho solo cambiato un po' [codesta stringa](https://pontoon.mozilla.org/it/amo/all-resources/?status=unreviewed&string=193399)

**Comment by Sav22999** [comment]
Perfetta. Ho aggiunto il "doppio spazio"
________________________________

**Comment by kitsunenosaraT** [comment]
> Perfetta. Ho aggiunto il "doppio spazio"

Quel doppio spazio è un errore nella stringa sorgente, comunque non va riprodotto, anche se il quality check te lo segnala. 
Se dovesse ricapitarti questo o un altro errore evidente, ignoralo pure senza indugio. A volte capita anche a chi scrive le stringhe originali di sbagliare 😆 

Intanto ho accettato la stringa senza doppio spazio e ticchettato AMO. Buona serata!

**Comment by kitsunenosaraT** [comment]
@dag7dev  @Sav22999 

Scusate, mi era sfuggito il vostro appello.

> Sulle frasi relative ai QR metterei subito il nome dell'applicazione (senza usare esplicitamente la parola "applicazione", in fine dei conti scannerizzi il QR per fornire di un certo servizio)

> (1 -) Per il problema delle app chiedo l'intervento di @kitsunenosaraT.

Direi che, anche se la versione di Sav2999 è più puntuale e andrebbe benissimo lo stesso, la versione di dag7 alla fine non omette informazioni importanti (essendo il download di un'"app" implicito nella procedura di scansione del QR), in più ha il vantaggio della brevità.
Siccome non sappiamo esattamente dove andrà a finire la stringa, opto questa volta per la versione più concisa.

>questa qui l'ho tradotta con "i tuoi contenuti" poiché "metti contenuti di qualità" non aveva senso secondo me, totalmente decontestualizzata...

Pocket vanta tra i suoi servizi quello di proporre contenuti "di qualità" (qualsiasi cosa significhi). Diciamo che è ciò che lo differenzia da altri servizi simili. Per questo non toglierei il riferimento. Però metterei "Salva" invece di "Metti".

> 3 - Sì, capisco. Però personalmente non reputo abbia molto senso "Porta la tua vita con te" ... io la riformulerei. Nel caso, chiedo l'intervento del capo supremo :)

Mah, a me non dispiace. Anche l'originale infondo mira  a essere abbastanza poetico. Visto che non ci sono suggerimenti alternativi, la ho accettata,

E ho messo anche alcune piccole modifiche. 
Per esempio in [questa](https://pontoon.mozilla.org/it/mozillaorg/firefox/accounts-2018.lang/?status=missing&string=192986) "power" anche in inglese non ha molto senso nel contesto.

Potreste ricontrollarle per favore? [Ecco qui](https://pontoon.mozilla.org/it/mozillaorg/firefox/accounts-2018.lang/?status=missing&string=192986)

**Comment by Sav22999** [comment]
Per me va bene, ma il traduttore è @dag7dev attendiamo suo parere :)

**Comment by dag7dev** [comment]
@kitsunenosaraT @Sav22999 a parte il link non funzionante, potete procedere al merging

**Comment by kitsunenosaraT** [comment]
Bene, grazie a tutti. Questo issue lo chiudiamo qui e ne aprirò uno settimana prossima appena ci sono le stringhe. Per quanto riguarda Thible, chiederò a Elio se vuole continuare a occuparsene.
Se dice di sì potremmo riaprire lo issue dedicato a Thimble, così se le gestisce coi suoi tempi e non entrano negli issue settimanali, altrimenti le riassegniamo.
Intanto buona serata!
