### ISSUE TITLE
Translating Mozilla AllHands 2018 Participation Guidelines

### ISSUE THREAD

**Issue by kitsunenosaraT** [MozillaItalia/Mozilla-Italia-l10n-guide#152]
Questo issue serve per tradurre un breve volantino che elenca le linee guida di partecipazione agli eventi Mozilla. L'originale menziona l'evento [All Hands](https://wiki.mozilla.org/All_Hands), ma noi sostituiremo genericamente "evento" perché sia valido per ogni tipo di iniziativa. La traduzione è stata richiesta da @Mte90 che, una volta ottenuto il testo in italiano, lo impaginerà su un volantino.
 
## Informazioni sul file da tradurre
**Nome**: Mozilla AllHands 2018 Participation-Guidelines
**File**: [Google Drive](https://docs.google.com/document/d/1ga-wRzWYv0IsDmEDUHp6z1HvbuaxRN4DD3-rTKyyqxA/edit?usp=sharing)
**Tipo**: google docs
**Strumento di traduzione**: A scelta:
- scaricare il file e tradurlo con il proprio editor di testo preferito. Dal menu di Drive: File > Download as > scegli il formato, poi allegarlo nello issue
- lavorare direttamente sul file online

❗️ Dato che la traduzione è suddivisa in celle di tabella, è possibile tradurre anche solo qualche riga, a seconda della propria disponibilità.

## Istruzioni
* lascia un messaggio nella sezione Commenti, chiedendo che ti venga assegnato il progetto.
* vai al file e procedi alla traduzione (scaricando una tua copia o direttamente sul google doc)
* il testo originale è nella colonna di sinistra, scrivi la traduzione nella colonna di sinistra
* il termine All Hands (nome di un evento) deve essere sostituito con un generico "evento"
* per qualsiasi problema o domanda scrivi pure in questo issue
* quando la tua traduzione è pronta, lascia un commento nello issue e, se hai lavorato sulla tua copia, allega direttamente il file tradotto (trascina il documento nel riquadro del commento), oppure caricalo su un servizio cloud (Google Drive, Dropbox ecc.) e inserisci qui il link.
* **rimani a disposizione per il QA**, ti verrà chiesto se vuoi confermare le modifiche del revisore o meno
* e buona traduzione! 🎊 

## Link Utili
* La [memoria di traduzione](https://transvision.mozfr.org/) di Mozilla, da consultare per garantire consistenza terminologica

**Comment by kitsunenosaraT** [comment]
Il bug è stato preso da dag7dev.

**Comment by kitsunenosaraT** [comment]
@Mte90 Le linee guida, tradotte e revisionate, sono pronte per te al link in cima allo issue. Se vuoi, magari, sarebbe carino postare qui un link al volantino finito. 😁

**Comment by Mte90** [comment]
Sto vedendo chi puó fare le modifiche al file originale che ho dei problemi nella modifica su Linux.
Vi tengo aggiornati :-)

**Comment by Mte90** [comment]
https://forum.mozillaitalia.org/index.php?topic=72156.0 ecco qui l'annuncio sul forum con i link per scaricarla in italiano :-D

Direi che si puó chiudere!

**Comment by kitsunenosaraT** [comment]
Splendido! Allora chiudiamo.
