### ISSUE TITLE
Weekly Translation of Pontoon Projects (Week #11/19)

### ISSUE THREAD

**Issue by kitsunenosaraT** [MozillaItalia/Mozilla-Italia-l10n-guide#158]
# Stringhe della settimana
- [x] [Engagement](https://pontoon.mozilla.org/it/engagement/all-resources/?status=missing%2Cfuzzy%2Cerrors&string=196461) 44 stringhe
In caso vogliate dividervi le stringhe, mettete i vostri nomi qui sotto
   - [x] @AndyUrbi  # stringhe varie, una trentina.
   - [x] @kitsunenosaraT  11 stringhe
- [x] [Common Voice](https://pontoon.mozilla.org/it/common-voice/all-resources/?status=missing%2Cfuzzy%2Cerrors&string=196473) 3 stringhe - @Sav22999

**Altre traduzioni in corso**
#141 Mozilla Activate (bassa priorità)

❗️  La lista delle stringhe da tradurre viene aggiornata più volte nell'arco della settimana

## Informazioni sul progetto
Questo issue serve a gestire le traduzioni dei siti Mozilla sulla piattaforma [Pontoon](https://pontoon.mozilla.org/it/).

Ogni settimana uscirà un nuovo issue con una lista dei progetti che contengono stringhe mancanti. Puoi sempre trovare lo issue della settimana corrente sulla [bacheca del progetto](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/projects/5).
Chi vuole farsi avanti, a seconda della propria disponibilità, si "prenoterà" per le stringhe.
Questo per organizzare meglio l'attività di traduzione ed evitare che più persone lavorino sulle stesse stringhe.

#### Prima di iniziare:
* [Registrati](https://accounts.firefox.com/oauth/signin?response_type=code&scope=profile%3Auid%20profile%3Aemail%20profile%3Adisplay_name%20profile%3Auid%20profile%3Adisplay_name%20profile%3Aemail&state=yrvTUh3o4F4c&redirect_uri=https%3A%2F%2Fpontoon.mozilla.org%2Faccounts%2Ffxa%2Flogin%2Fcallback%2F&client_id=76ab66239b5585ad) sulla piattaforma di traduzione Pontoon
  - (facoltativo) Installa il componente aggiuntivo [Pontoon Tools](https://addons.mozilla.org/it/firefox/addon/pontoon-tools/) per ricevere le notifiche delle stringhe mancanti in tempo reale (più altre chicche)
* **Leggi i capitoli della guida**, se lo desideri, lascia un feedback nel relativo issue:
  - Capitolo 1 – [Buone norme di traduzione tecnica](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/1-Buone_norme_di_traduzione.md) Feedback: issue #91 
  - Capitolo 2 – [Linee guida di Mozilla Italia](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/2-Linee_guida_di_Mozilla_Italia.md) Feedback: issue #138
  - Capitolo 3 – [Flusso di lavoro](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/3-Flusso_di_lavoro.md) Feedback: issue #24 
  - Capitolo 4 – [Tipi di file](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/4-Tipi_di_file.md) Feedback: issue #31 
  - Capitolo 5  – [Risorse esterne](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/5-Risorse_esterne.md) Feedback: issue #36

#### Prendere in carico il progetto:
* lascia un messaggio nella sezione Commenti, scrivendo di quale progetto vuoi occuparti (importante per avvisare gli altri che ci stai lavorando tu). Scrivi anche il tuo nome utente accanto al nome del progetto sulla lista qui in alto (usa l'icona della matita per modificare il testo. Se non sei ancora tra i [Collaborators](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/settings/collaboration) non hai i permessi per modificare la lista. Scrivi solo nei commenti e qualcuno con i permessi aggiungerà il tuo nome alla lista.)
* attieniti alle istruzioni del [capitolo 3](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/3-Flusso_di_lavoro.md) e del [capitolo 4](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/4-Tipi_di_file.md)
* per qualsiasi problema o domanda scrivi pure in questo issue
* quando la tua traduzione è pronta, lascia un commento nello issue per dare l'OK al QA
* rimani a disposizione per il QA, ti verrà chiesto se vuoi confermare le modifiche del revisore o meno
* e buona traduzione! 🎊 

## Link Utili
* [Web Localization Dashboard](https://l10n.mozilla-community.org/webdashboard/?locale=it) -- Lista dei progetti Pontoon con relative scadenze
* Server di test -- Per vedere dove andranno a finire le vostre traduzioni
  - per le singole pagine di [mozilla.org](https://l10n.mozilla-community.org/langchecker/?action=listpages) 
  - per [AMO](https://addons-dev.allizom.org/it/)
  - per [MDN](https://developer.allizom.org/it/)
  - per [Test Pilot](https://testpilot-l10n.dev.mozaws.net/)
  - per [Common Voice](https://voice.allizom.org/it)
  - per [Thunderbird.net](https://www.thunderbird.net/it/) *sito produzione
  - per [Firefox Monitor](https://fx-breach-alerts.herokuapp.com/) + [Modelli email](https://fx-breach-alerts.herokuapp.com/email-l10n)
  - per [Firefox Send](https://send.firefox.com/) *sito produzione
* [mozilla.dev.l10n.web](https://groups.google.com/forum/#!forum/mozilla.dev.l10n.web) -- Un newsgroup internazionale di riferimento per le stringhe della settimana. Condivide informazioni sui progetti correnti, anche utile per porre domande e segnalare bug ecc.

**Comment by kitsunenosaraT** [comment]
Ciao a tutti!
Eccezionalmente anticipo lo issue per la prossima settimana, perché sono appena spuntate un sacco di nuove stringhe per il progetto Engagement (alta priorità) e io non ci sarò per tutta domenica.
Sentitevi liberi di iniziarle quando volete, lunedì o prima.
Visto che sono ben 44, se volete spartirvele, ho messo sotto la casella un elenco puntato dove ciascuno può scrivere il suo nome e il numero di stringhe che prende, in modo da non fare confusione.

Buon week-end!

**Comment by AndyUrbi** [comment]
Qualcuna me la prendo io.

**Comment by AndyUrbi** [comment]
@kitsunenosaraT Se hai tempo puoi fare il QA anche di queste.

**Comment by kitsunenosaraT** [comment]
Grazie mille @AndyUrbi Hai fatto un gran bel lavoro!
Ecco il [QA](https://pontoon.mozilla.org/it/engagement/all-resources/?status=missing%2Cfuzzy%2Cerrors&author=openlib%40email.it&string=196454). Ho più che altro fatto piccoli adattamenti per farlo scorrere meglio in italiano.
- Per le formule di saluto (Dear...) purtroppo dobbiamo tener presente la differenza maschile/femminile di cui in inglese non devono preoccuparsi.
- Per PayPal ho usato la terminologia presente sul loro sito.
- dd/mm/yyyy per errore "dd" non è stato preso come tag da Pontoon, comunque è una variabile e non va tradotto.
- La stringa con 1st|2nd| ecc.: dovrebbe essere 1° giorno, 2° giorno ecc. (vedi commento sotto la stringa)

Credo sia tutto, ma se ho tralasciato qualcosa scrivi pure!

**Comment by kitsunenosaraT** [comment]
>Per la data: scusa ma la stringa o è tutta un tag, oppure non lo è per niente. Una forma mista non credo porti ad un risultato corretto. Ri-sbaglio?

Come scrivevo sopra, sì, si tratta di un errore di Pontoon. Dovrebbe essere tutto un tag, oppure tutto modificabile.
In questo caso ti chiede di ordinare il formato della data secondo l'usanza del tuo paese, ovvero in Italia dd/mm/yyyy (giorno / mese / anno), quindi a rigor di logica dovrebbe essere tutto modificabile. Gli elementi d,m,y non vanno tradotti perché sono variabili che andranno sostituite con i numeri della data.

> Per i giorni: stavo traducendo come hai fatto te ma poi qualcosa non mi convinceva. Si può sapere dove finisce la stringa?

Ne so quanto te 😁 Suppongo una specie di conteggio per la campagna di donazioni. Comunque seguiamo i commenti della stringa.

**Comment by AndyUrbi** [comment]
Capito, puoi accettare tutto.

**Comment by kitsunenosaraT** [comment]
Accettate!
Visto che questo progetto è ad alta priorità e sarebbe bene non farlo aspettare troppo, mi prendo le ultime 11 stringhe, e invito chi vuole tradurre a spostarsi nello issue #141 dove troverà un sacco di stringhe del progetto Activate Mozilla 😁

**Comment by kitsunenosaraT** [comment]
Pronte per il [QA](https://pontoon.mozilla.org/it/engagement/all-resources/?status=unreviewed&string=196427) di qualche anima pia.

@AndyUrbi abbiamo scoperto dove vanno a finire quei numeri…
Sostituiscono il [tag nth](https://pontoon.mozilla.org/it/engagement/all-resources/?status=missing&search=%7Bnth%7D+&string=196426).

**Comment by kitsunenosaraT** [comment]
QA della seconda parte di Engagement fatta da flod tramite Telegram.
Rimangono solo 3 stringhe di Common Voice per il week-end.

**Comment by Sav22999** [comment]
Mi prendo Common Voice :)

**Comment by Sav22999** [comment]
Common Voice pronto per il QA.

**Comment by kitsunenosaraT** [comment]
@Sav22999 Grazie! 😁 Per lo più [alternative e suggerimenti](https://pontoon.mozilla.org/it/common-voice/all-resources/?status=missing%2Cfuzzy%2Cerrors&string=196473).

**Comment by Sav22999** [comment]
Accettati 👍  grazie.
Non sapevo se tradurre (e come) "sentence collector tool"

**Comment by kitsunenosaraT** [comment]
È un dubbio legittimo. Ho scelto di tradurlo perché non è un nome proprio e penso che il lettore in questo modo capisca meglio di cosa si tratti.
Allora, benissimo! Per questa settimana abbiamo concluso. Chiudo e ci sentiamo alla prossima.
Grazie ancora a tutti!
