### ISSUE TITLE
Translating Android l10n

### ISSUE THREAD

**Issue by kitsunenosaraT** [MozillaItalia/Mozilla-Italia-l10n-guide#160]
Questo issue si occupa della traduzione del progetto [Android l10n](https://pontoon.mozilla.org/it/android-l10n/all-resources/?status=missing%2Cfuzzy%2Cerrors&string=196915) su [Pontoon](https://pontoon.mozilla.org/it/)

## Informazioni sul progetto
La base per il nuovo browser per Android (Fenix).
Fenix sostituisce Fennec (Firefox per Android), con la differenza che utilizza componenti riutilizzabili per altri browser (FireTV, Echo Show, Focus, Reality, etc.).
Dovrebbero esserci molte corrispondenze in stringhe esistenti.

## Istruzioni

* **Leggi i capitoli della guida**, se lo desideri, lascia un feedback nel relativo issue:
  - Capitolo 1 – [Buone norme di traduzione tecnica](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/1-Buone_norme_di_traduzione.md) Feedback: issue #91 
  - Capitolo 2 – [Linee guida di Mozilla Italia](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/2-Linee_guida_di_Mozilla_Italia.md) Feedback: issue #138
  - Capitolo 3 – [Flusso di lavoro](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/3-Flusso_di_lavoro.md) Feedback: issue #24 
  - Capitolo 4 – [Tipi di file](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/4-Tipi_di_file.md) Feedback: issue #31 
  - Capitolo 5  – [Risorse esterne](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/5-Risorse_esterne.md) Feedback: issue #36 

* lascia un messaggio nei commenti avvisando che stai per tradurre il progetto
* vai su Pontoon e traduci quante stringhe desideri.
* per qualsiasi problema o domanda scrivi pure in questo issue o contatta @flodolo 
* quando la tua traduzione è pronta, lascia un commento nello issue per dare l'OK al QA, **menzionando @flodolo**
* rimani a disposizione per il QA, ti verrà chiesto se vuoi confermare le modifiche del revisore o meno
* e buona traduzione! 🎊 

## Link Utili
* [Link diretto alle stringhe mancanti](https://pontoon.mozilla.org/it/android-l10n/all-resources/?status=missing&string=196915)
* [Link ai suggerimenti in attesa di approvazione](https://pontoon.mozilla.org/it/android-l10n/all-resources/?status=unreviewed)
* [Link a tutte le stringhe del progetto](https://pontoon.mozilla.org/it/android-l10n/all-resources/?string=196915)
* [Memorie di traduzione di Mozilla](https://transvision.mozfr.org/) -- Per ricerche terminologiche (come sono stati tradotti precedentemente prodotti e iniziative Mozilla)

**Comment by AndyUrbi** [comment]
Ok, vediamo cosa combino con queste stringhe....

**Comment by AndyUrbi** [comment]
@flodolo  Qualcuno ha approvato le stringhe che avevo fatto ieri? Perché non le vedo...

**Comment by flodolo** [comment]
> @flodolo Qualcuno ha approvato le stringhe che avevo fatto ieri? Perché non le vedo...

Scusami :-\ Volevo controllare le stringhe del traduttore anonimo, e ho approvato/modificato anche le tue senza accorgermi che non erano pronte.

Puoi dare un'occhiata alle modifiche e vedere se hanno senso?
https://pontoon.mozilla.org/it/android-l10n/all-resources/?author=openlib%40email.it&string=196934

In generale:
* Per i menu si evitano gli articoli. In particolare, su Android lo spazio è limitato, ed è una ragione in più per evitarli.
* "tua/o" può essere evitato (è implicito) in molti casi.
* "private tab" è una scheda anonima in Firefox, non private.
* "crash" -> "arresto anomalo"
* "Download file" è abbastanza orribile, ma è un titolo, e ci va il sostantivo, non il verbo.

**Comment by AndyUrbi** [comment]
> Puoi dare un'occhiata alle modifiche e vedere se hanno senso?

@flodolo 
Direi proprio di si. Per le restanti ieri avevo un problema con i caratteri come apostrofo e puntini vari e alcune frasi non sono in grado di tradurle, quindi io mi fermo qui.

**Comment by AndyUrbi** [comment]
@flodolo Scomparso il problema, altre stringhe da controllare...

**Comment by flodolo** [comment]
> @flodolo Scomparso il problema, altre stringhe da controllare...

Approvata la maggior parte delle stringhe, puoi dare un'occhiata ai suggerimenti in sospeso? In alcuni casi ho scelto una versione più corta, perché non sono sicuro di quanto spazio sia disponibile.

**Comment by AndyUrbi** [comment]
Quelle in sospeso le hai rese quasi tutte più lunghe, mi confondi :smile: 
1. _Segnala un problema_ è diventato _Segnala un problema con il sito_: per me è sottointeso e anche più lungo, fai come credi
2. _Apri con_ invece di _Apri in_ non rende meglio in italiano?
3. _Impostazioni del motore di ricerca_ in inglese leggo impostazioni al plurale e motore al singolare ma forse non avrebbe senso...
4. _Votami su Google Play_ sapevo che lo avresti cassato, ma si tratta di votare l'app e non una votazione da fare in un sito. Mi pare che alcune app scrivono proprio così.
5. _Sincronizzazione in corso_ l'ho scritto per via della descrizione (that sync is in progress)
Le altre ok. Dimmi cosa ne pensi.

**Comment by flodolo** [comment]
> Quelle in sospeso @flodolo le hai rese quasi tutte più lunghe, mi confondi 😄

E c'hai ragione pure tu. Dove allungo, è perché spero che non si tratti di un menu con spazio limitato, ma, ad esempio, di un titolo in mezzo a una pagina.

> _Apri con_ invece di _Apri in_ non rende meglio in italiano?

L'ho messo per uniformità con traduzioni esistenti. @kitsunenosaraT il tuo parere?

> Impostazioni del motore di ricerca_ in inglese leggo impostazioni al plurale e motore al singolare ma forse non avrebbe senso...

Credo che le impostazioni siano per tutti i motori di ricerca, non per uno solo, ma è da verificare nell'app.

> Votami su Google Play sapevo che lo avresti cassato, ma si tratta di votare l'app e non una votazione da fare in un sito. Mi pare che alcune app scrivono proprio così.

È che suona tanto come "vota l'utente"…

> Sincronizzazione in corso l'ho scritto per via della descrizione (that sync is in progress)

Anche in questo caso il dubbio è lo spazio, magari aggiungere i … aiuta.

**Comment by Karm46** [comment]
Buongiorno a tutti. Vedo che questo progetto è classificato giustamente con la massima priorità e pertanto ritengo di dover mettermi subito anche io a disposizione per tutto l'aiuto che posso dare. Pero vorrei offrire il mio contributo contestualmente allo stesso lavoro che intenderei svolgere per interlingua (dove avevamo già localizzato al 100% Firefox per Android senza che questo sia mai passato opertativo). In seguito anche per il siciliano.
Ora, scusandomi per il parziale OT, chiedo a chi può (@flodolo @Mte90 @kitsunenosaraT @AndyUrbi , ???), di inserire questo progetto nel team ia dove non è contemplato nelle richieste che posso fare io come, e magari nel team scn. Chiedo ancora scusa per il parziale OT e grazie anticipate per l'attenzione.

**Comment by flodolo** [comment]
Scusa ma la richiesta relativa a nuove lingue in questi progetti è veramente off-topic. Anche inviare ping a persone "a caso" (cosa c'entra Daniele?) ha poco senso.

Per il futuro, esistono canali appositi per chiedere queste informazioni, non abusare di discussioni esistenti, specialmente quando sono relative in modo specifico alla traduzione in italiano.

Fenix e android-components. Non sono aperti a nuove lingue al momento
https://groups.google.com/forum/#!topic/mozilla.dev.l10n/18JYpiyaZcU
https://groups.google.com/forum/#!topic/mozilla.dev.l10n/uh-Q4ypOklk

Per ogni progetto, in Pontoon c'è specificato un PM che puoi contattare per chiedere informazioni.

**Comment by flodolo** [comment]
@dag7dev 
Puoi dare un'occhiata ai 2 suggerimenti? "Sorry! bla bla" di solito lo traduciamo con "Ci dispiace, bla bal".

**Comment by kitsunenosaraT** [comment]
@flodolo @AndyUrbi 
> Apri con invece di Apri in non rende meglio in italiano?
> L'ho messo per uniformità con traduzioni esistenti. @kitsunenosaraT il tuo parere?

Scusate, la menzione mi era proprio sfuggita. Me la ha fatta notare Andrea in privato.
Io direi che suonano corrette e naturali entrambe, dunque propendo per la versione "Apri in [Fenix]" in modo da uniformare alle traduzioni precedenti.

**Comment by flodolo** [comment]
Grazie, approvata.

**Comment by dag7dev** [comment]
@flodolo vai approvato tutto!

**Comment by flodolo** [comment]
Ho tradotto un po' di stringhe per Fenix
https://pontoon.mozilla.org/it/android-l10n/all-resources/?status=unreviewed&string=198028

Qualcuno ha tempo di dare un'occhiata? Ci sono anche stringhe per Firefox Reality.

**Comment by AndyUrbi** [comment]
@flod ti ho lasciato 2 suggerimenti presi da machinery che mi sembravano migliori.
Poi ne ho fatte alcune di mie....

**Comment by flodolo** [comment]
> @flod ti ho lasciato 2 suggerimenti presi da machinery che mi sembravano migliori.

Grazie

> Show visited sites and bookmarks

Secondo me i segnalibri vengono visualizzati a prescindere dal fatto che vengano visitati, "Mostra siti e segnalibri visitati" fa pensare che i segnalibri appaiano solo se visitati, e non credo sia il caso.

> Bookmark saved!

L'ordine utilizzato per questo tipo di frasi è normalmente verbo + oggetto.

>  Poi ne ho fatte alcune di mie....

Approvate la maggior parte, lasciato qualche suggerimento:
* Permissions -> [Permessi](https://transvision.mozfr.org/?recherche=permission&repo=gecko_strings&sourcelocale=en-US&locale=it&search_type=strings_entities)
* Disabled -> Disattivato

> Read External Storage

Secondo me viene usata in una [lista di permessi](https://github.com/MozillaReality/FirefoxReality/blob/1065b9c08f0fcb79ffbe258748fe5838eb1daeaf/app/src/main/res/layout/options_privacy.xml#L98) che puoi attivare/disattiva, per cui "Lettura memoria esterna" dovrebbe essere corretto (ma è da verificare nell'app).

**Comment by flodolo** [comment]
Già che c'ero, ho lasciato suggerimenti anche per le altre stringhe (e scoperto un nuovo termine, [foveazione](https://www.zanichelli.it/scuola/dieci-in-leggibilita)).

**Comment by AndyUrbi** [comment]
> L'ordine utilizzato per questo tipo di frasi è normalmente verbo + oggetto

In italiano mi sembra proprio brutta e non comprendo la regola a cui ti riferisci. Mi puoi illuminare?

> "Lettura memoria esterna" dovrebbe essere corretto

ok per lettura, errore mio, ma perché preferisci memoria invece di archivio? Mi pare che in italiano si possano usare come sinonimi.

**Comment by flodolo** [comment]
> In italiano mi sembra proprio brutta e non comprendo la regola a cui ti riferisci. Mi puoi illuminare?

Perché? Normalmente diresti "Ho aggiunto un segnalibro" -> "Aggiunto segnalibro". È semplicemente una convenzione che si può cambiare.

> ok per lettura, errore mio, ma perché preferisci memoria invece di archivio? Mi pare che in italiano si possano usare come sinonimi.

Credo che le alternative siano "archiviazione" (es. spazio di archiviazione), o "memoria", non "archivio".
Ho dato un'occhiata al mio telefono con Android e usano entrambi in modo confuso (es. "Gestione memoria", "Gestione spazio di archiviazione", "Gestione archiviazione"). 

"Internal storage" è comunque "memoria interna".

**Comment by flodolo** [comment]
> Perché? Normalmente diresti "Ho aggiunto un segnalibro" -> "Aggiunto segnalibro". È semplicemente una convenzione che si può cambiare.

@kitsunenosaraT
Direi che questa va risolta una volta per tutte e documentata da qualche parte.

"Deleted bookmark" in una notifica: "Eliminato/aggiunto segnalibro" o "Segnalibro eliminato/aggiunto"?

**Comment by kitsunenosaraT** [comment]
@flodolo Non riesco a trovare la stringa in questione, ma mi sembra più chiaro e naturale "Segnalibro eliminato/aggiunto".
Suppongo che il procedimento sia più o meno questo:
L'utente vuole eliminare il segnalibro > fa clic su "Elimina segnalibro"
Come conseguenza logica il segnalibro scompare > appare la notifica "Segnalibro eliminato".

Comparandolo anche con stringhe già approvate:
- [Segnalibro aggiunto.](https://pontoon.mozilla.org/it/android-l10n/all-resources/?search=Bookmark&string=197553)
- [Segnalibro salvato](https://pontoon.mozilla.org/it/android-l10n/all-resources/?search=Bookmark&string=198023).

**Comment by AndyUrbi** [comment]
> Ho dato un'occhiata al mio telefono con Android e usano entrambi in modo confuso (es. "Gestione memoria", "Gestione spazio di archiviazione", "Gestione archiviazione").

@flodolo 
Tenendo in considerazione che stiamo parlando di Android opterei per memoria esterna come hai scritto te. Immagino che in questo caso ci si riferisca ad una scheda SD, dovevo pensare di più al contesto.
A questo punto credo che si possano approvare tutte.
PS: una tua stringa si riferisce ai nuovi schermi ricurvi? Argomento complicato da rendere in italiano....

**Comment by flodolo** [comment]
@kitsunenosaraT 
Sì, è una notifica che appare sullo schermo dopo che hai eliminato il segnalibro. A questo punto, forse è il caso di segnarselo da qualche parte nella guida di stile, visto che in Firefox facevamo il contrario. Man mano che trovo stringhe simili, le aggiorno.

@AndyUrbi 
No, credo si tratti di un tipo di visualizzazione in un visore VR (che personalmente non ho mai provato).

**Comment by kitsunenosaraT** [comment]
> A questo punto, forse è il caso di segnarselo da qualche parte nella guida di stile, visto che in Firefox facevamo il contrario. 

Me lo sono segnato nello issue #91 dove segnaliamo tutte le modifiche da implementare per la nuova versione del capitolo 1. Appena rimetto mano al capitolo aggiungo anche quella.

**Comment by AndyUrbi** [comment]
> No, credo si tratti di un tipo di visualizzazione in un visore VR (che personalmente non ho mai provato).

Quindi sostanzialmente si tratta della visualizzazione a 360°? Diventerebbe: _Attiva visualizzazione a 360°_

**Comment by flodolo** [comment]
> Quindi sostanzialmente si tratta della visualizzazione a 360°? Diventerebbe: _Attiva visualizzazione a 360°_

Non credo sia a 360°, semplicemente curva invece di piatta.

**Comment by flodolo** [comment]
Ci sono un po' di traduzioni da controllare
https://pontoon.mozilla.org/it/android-l10n/all-resources/?status=unreviewed&string=198474

**Comment by flodolo** [comment]
> > Name collection
> 
> Basandomi sul commento, secondo qui "name" è un verbo"

Nei titoli delle finestre di dialogo dovrebbe andare il sostantivo, non il verbo.

**Comment by flodolo** [comment]
Dimenticavo, accettato tutto il resto nel frattempo, grazie per la revisione al volo :)

**Comment by kitsunenosaraT** [comment]
> Nei titoli delle finestre di dialogo dovrebbe andare il sostantivo, non il verbo.

Questo è vero di norma, però siccome illustra un passaggio nella creazione di una raccolta, ho pensato che in questo caso mantenere l'azione sarebbe più esplicativo per l'utente.
Comunque sono sottigliezze, "Nome raccolta" va benissimo. :+1

**Comment by flodolo** [comment]
Ci sono 112 stringhe di Lockwise (password manager) da controllare ;-)
https://pontoon.mozilla.org/it/android-l10n/all-resources/?status=missing&string=198688

Questione terminologica: come traduciamo "logins"? [In Firefox](https://transvision.mozfr.org/?recherche=Logins&repo=gecko_strings&sourcelocale=en-US&locale=it&search_type=strings_entities), è un misto di "accessi", "credenziali", "credenziali di accesso". Personalmente vorrei eliminare "accessi", ma prima vorrei capire cosa ne pensano gli altri.

**Comment by kitsunenosaraT** [comment]
Mi ci metto 👍

**Comment by kitsunenosaraT** [comment]
Eccomi.
Ho lasciato non confermate quelle che contengono la parola "logins" in caso decidessimo di cambiarla.
Comunque io voto +1 per "credenziali" e basta.
Scrivere ogni volta "credenziali di accesso" risulta in effetti pesante, inoltre penso che il concetto sia chiaro lo stesso, forse addirittura più dell'inglese.

Invece, per quanto riguarda il resto del QA, ho lasciato pochi suggerimenti, molti sono mere preferenze.
Queste due in particolare, però:
- "Autofill" mi sembra che la traduzione ufficiale sia [compilazione automatica](https://transvision.mozfr.org/?recherche=autofill&repo=gecko_strings&sourcelocale=en-US&locale=it&search_type=strings)
- "fingerprint sensor": "lettore" mi dà l'idea di un dispositivo esterno. Per lo smartphone, non è più comune usare "sensore"?

**Comment by flodolo** [comment]
> "Autofill" mi sembra che la traduzione ufficiale sia [compilazione automatica](https://transvision.mozfr.org/?recherche=autofill&repo=gecko_strings&sourcelocale=en-US&locale=it&search_type=strings)

Ci serve la traduzione di Android, non la nostra. Però mi sono appena reso conto che ho guardato quella di [Apple](https://support.apple.com/it-it/guide/safari/use-autofill-ibrw1103/mac), visto che parlavo l'altro giorno di quello con Delphine 😒

Sul mio cellulare Android è "Compilazione automatica", per cui devo correggere.

>     * "fingerprint sensor": "lettore" mi dà l'idea di un dispositivo esterno. Per lo smartphone, non è più comune usare "sensore"

Sul mio cellulare è chiamata "area di identificazione dell’impronta", perché non è un sensore (appoggi il dito sul vetro). [Samsung](https://www.samsung.com/it/support/mobile-devices/come-utilizzare-il-lettore-di-impronte-digitali-di-samsung-galaxy-s5/) lo chiama lettore, ad esempio.

Su *logins*: aspetto il weekend. Se non arrivano opinioni contrarie, approvo "credenziali", così dovremmo avere una build di prova.

**Comment by kitsunenosaraT** [comment]
Confermo anche io "Compilazione automatica" per Android.
Invece, a titolo di comparazione, il mio Honor lo chiama "sensore impronta".

**Comment by flodolo** [comment]
Ancora su sensore vs lettore.

Google usa sensore: https://support.google.com/pixelphone/answer/6285273?hl=it
Sony use sensore: https://support.sonymobile.com/it/xperiax/userguide/fingerprint-manager/#gref
HTC usa "scanner" (meh): https://www.htc.com/it/support/htc-10/howto/fingerprint-sensor.html

Andiamo con sensore ;-)

**Comment by flodolo** [comment]
> Su _logins_: aspetto il weekend. Se non arrivano opinioni contrarie, approvo "credenziali", così dovremmo avere una build di prova.

Sto per approvare credenziali, nel caso è semplice cercare le stringhe e cambiare idea.

**Comment by flodolo** [comment]
Tradotte [altre 5 stringhe](https://pontoon.mozilla.org/it/android-l10n/all-resources/?status=unreviewed%2Cmissing&string=199248) in Fenix, se qualcuno ha tempo di dargli un'occhiata.

**Comment by flodolo** [comment]
@kitsunenosaraT 
Riesci a dare un'occhiata veloce a queste?

**Comment by kitsunenosaraT** [comment]
Ho messo solo [un suggerimento](https://pontoon.mozilla.org/it/android-l10n/all-resources/?status=missing%2Cfuzzy%2Cerrors&string=199245).
Trovo più chiaro quando si danno istruzioni all'utente mettere prima che risultato ottengono, poi la procedura:
Per ottenere x fai y.
vs.
Fai y per ottenere x. 

Questo è valido soprattutto  quando ci sono lunghe spiegazioni, in questo caso è praticamente uguale.

**Comment by flodolo** [comment]
Grazie, approvata la tua versione :)

**Comment by flodolo** [comment]
[29 stringhe](https://pontoon.mozilla.org/it/android-l10n/all-resources/?status=unreviewed&string=199513) da controllare per Fenix.

Nota: ho lasciato "quick fox" in inglese, perché lo scopo di quella frase è visualizzare tutti i caratteri dell'alfabeto, e i [pangrammi](https://it.wikipedia.org/wiki/Pangramma) [italiani](https://medium.com/@OniceDesign/davvero-usate-ancora-la-frase-the-quick-brown-fox-jumps-over-the-lazy-dog-2913768be02f) sono abbastanza orribili.

**Comment by kitsunenosaraT** [comment]
Solo un [suggerimento](https://pontoon.mozilla.org/it/android-l10n/all-resources/?status=unreviewed&string=199507) per chiarificare la frase.
Non sapevo di questi panagrammi, ho imparato qualcosa di nuovo. (Tra l'altro un panagramma italiano non dovrebbe includere anche le lettere accentate? Sono proprio quelle che ti fregano nella visualizzazione dei caratteri...)

**Comment by flodolo** [comment]
Grazie, approvata. E sì, dovrebbero decisamente avere le lettere accentate,
e magari apostrofi e virgolette.

Il sab 25 mag 2019, 17:25 sara_t <notifications@github.com> ha scritto:

**Comment by flodolo** [comment]
Altro giro: [6 stringhe](https://pontoon.mozilla.org/translate/it/android-l10n/all-resources/?status=missing&string=199579).

Non sono convintissimo di "media", nel senso che non capisco a cosa si riferisca. Il link punta a https://developer.android.com/training/notify-user/channels che utilizza "medium", e non trovo nessuna occorrenza in Android 9

**Comment by kitsunenosaraT** [comment]
Accettate tutte tranne "Media".
Non ho Oreo e non sono riuscita a trovare screenshot in italiano su come viene tradotto quel canale di notifica. Nel dubbio comunque terrei "Media".

**Comment by flodolo** [comment]
Per il momento ho approvato media. Come vedi dagli screenshot in quella pagina, non c'è traccia da nessun parte di "medium" o "media".

**Comment by flodolo** [comment]
[46 stringhe](https://pontoon.mozilla.org/it/android-l10n/all-resources/?status=missing&status=suggested) per android-l10n. In teoria, questa settimana doveva esserci lo *string freeze* per la versione iniziale di Fenix. Non che ci creda molto :)

Una volta rilasciata quella versione, possiamo chiuedere questa issue e tradurre android-l10n con il resto dei progetti.

**Comment by kitsunenosaraT** [comment]
Qualche [piccolo suggerimento](https://pontoon.mozilla.org/it/android-l10n/all-resources/?status=missing&string=199663).

**Comment by flodolo** [comment]
Grazie, ho approvato le altre tre. Non sono convintissimo di "fa meglio" :-\

**Comment by kitsunenosaraT** [comment]
"Fa bene alla batteria e agli occhi?"

**Comment by flodolo** [comment]
Decisamente meglio. Vediamo se ci sono altri suggerimenti, altrimenti
accetto con "fa bene"

Il ven 31 mag 2019, 10:09 sara_t <notifications@github.com> ha scritto:

**Comment by flodolo** [comment]
Ho approvato. Per i posteri:

```
Try dark theme: easier on your battery and your eyes.
Prova il tema scuro: fa bene alla batteria e ai tuoi occhi.
```

Se ci sono idee migliori, abbiamo tempo per cambiare la traduzione :)

**Comment by kitsunenosaraT** [comment]
Bene, qui chiudiamo. Le prossime stringhe di questo progetto confluiranno nello issue settimanale.
Grazie a tutti!
