### ISSUE TITLE
Weekly Translation of Pontoon Projects (Week 42/19)

### ISSUE THREAD

**Issue by AndyUrbi** [MozillaItalia/Mozilla-Italia-l10n-guide#192]
# **Stringhe della settimana**
- [x] [Mozilla Donate website](https://pontoon.mozilla.org/translate/it/mozilla-donate-website/all-resources/?status=fuzzy%2Cmissing%2Cunreviewed&string=204789) 39+2 fuzzy **Sacedenza 4 nov.**
  - [x] parte 1 `@Karm46` 20 stringhe
  - [x] parte 2 `@Karm46` 21 stringhe
- [~~Firefox~~](https://pontoon.mozilla.org/translate/it/firefox/all-resources/?status=missing&string=204762) 23 stringhe - _Read only_
- [~~Firefox for Android~~](https://pontoon.mozilla.org/translate/it/firefox-for-android/all-resources/?status=missing&string=71236) 2 stringhe - _Read only_
- [x] [MDN](https://pontoon.mozilla.org/translate/it/mdn/all-resources/?status=missing&string=204679) 1 stringa - @michrogit 
- [x] [Thunderbird](https://pontoon.mozilla.org/translate/it/thunderbird/all-resources/?status=missing&string=204781) 2 stringhe - @Sav22999 
- [x] [Mozilla.org](https://pontoon.mozilla.org/translate/it/mozillaorg/all-resources/?status=fuzzy%2Cmissing%2Cunreviewed&string=204745) 33 stringhe
   - [x] parte 1 @Karm46 20 stringhe
   - [x] parte 2 @Karm46 13 stringhe
- [x] [Common Voice](https://pontoon.mozilla.org/translate/it/common-voice/all-resources/?status=fuzzy%2Cmissing%2Cunreviewed&string=204805) 3 stringhe - @fortym2 
- [x] [Android L10N](https://pontoon.mozilla.org/translate/it/android-l10n/all-resources/?status=fuzzy%2Cmissing%2Cunreviewed&string=204809) 2 stringhe - @michrogit 
- [MDN II](https://pontoon.mozilla.org/translate/it/mdn/all-resources/?status=fuzzy%2Cmissing%2Cunreviewed&string=204825) 23 stringhe + 3 fuzzy ▶️ issue #193 
- [x] [Android L10N](https://pontoon.mozilla.org/translate/it/android-l10n/all-resources/?status=missing&string=204846) 10 stringhe - @michrogit 

❗️  La lista delle stringhe da tradurre viene aggiornata più volte nell'arco della settimana

## Informazioni sul progetto
Questo issue serve a gestire le traduzioni dei siti Mozilla sulla piattaforma [Pontoon](https://pontoon.mozilla.org/it/).

Ogni settimana uscirà un nuovo issue con una lista dei progetti che contengono stringhe mancanti. Puoi sempre trovare lo issue della settimana corrente sulla [bacheca del progetto](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/projects/5).
Chi vuole farsi avanti, a seconda della propria disponibilità, si "prenoterà" per le stringhe.
Questo per organizzare meglio l'attività di traduzione ed evitare che più persone lavorino sulle stesse stringhe.

#### Prima di iniziare:
* [Registrati](https://accounts.firefox.com/oauth/signin?response_type=code&scope=profile%3Auid%20profile%3Aemail%20profile%3Adisplay_name%20profile%3Auid%20profile%3Adisplay_name%20profile%3Aemail&state=yrvTUh3o4F4c&redirect_uri=https%3A%2F%2Fpontoon.mozilla.org%2Faccounts%2Ffxa%2Flogin%2Fcallback%2F&client_id=76ab66239b5585ad) sulla piattaforma di traduzione Pontoon
  - (facoltativo) Installa il componente aggiuntivo [Pontoon Tools](https://addons.mozilla.org/it/firefox/addon/pontoon-tools/) per ricevere le notifiche delle stringhe mancanti in tempo reale (più altre chicche)
* **Leggi i capitoli della guida**, se lo desideri, lascia un feedback nel relativo issue:
  - Capitolo 1 – [Buone norme di traduzione tecnica](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/1-Buone_norme_di_traduzione.md) Feedback: issue #91 
  - Capitolo 2 – [Linee guida di Mozilla Italia](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/2-Linee_guida_di_Mozilla_Italia.md) Feedback: issue #138
  - Capitolo 3 – [Flusso di lavoro](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/3-Flusso_di_lavoro.md) Feedback: issue #24 
  - Capitolo 4 – [Tipi di file](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/4-Tipi_di_file.md) Feedback: issue #31 
  - Capitolo 5  – [Risorse esterne](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/5-Risorse_esterne.md) Feedback: issue #36

#### Prendere in carico il progetto:
* lascia un messaggio nella sezione Commenti, scrivendo di quale progetto vuoi occuparti (importante per avvisare gli altri che ci stai lavorando tu). Scrivi anche il tuo nome utente accanto al nome del progetto sulla lista qui in alto (usa l'icona della matita per modificare il testo. Se non sei ancora tra i [Collaborators](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/settings/collaboration) non hai i permessi per modificare la lista. Scrivi solo nei commenti e qualcuno con i permessi aggiungerà il tuo nome alla lista.)
* attieniti alle istruzioni del [capitolo 3](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/3-Flusso_di_lavoro.md) e del [capitolo 4](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/4-Tipi_di_file.md)
* per qualsiasi problema o domanda scrivi pure in questo issue
* quando la tua traduzione è pronta, lascia un commento nello issue per dare l'OK al QA
* rimani a disposizione per il QA, ti verrà chiesto se vuoi confermare le modifiche del revisore o meno
* e buona traduzione! 🎊 

## Link Utili
* [Web Localization Dashboard](https://l10n.mozilla-community.org/webdashboard/?locale=it) -- Lista dei progetti Pontoon con relative scadenze
* Server di test -- Per vedere dove andranno a finire le vostre traduzioni
  - per le singole pagine di [mozilla.org](https://l10n.mozilla-community.org/langchecker/?action=listpages) 
  - per [AMO](https://addons-dev.allizom.org/it/)
  - per [MDN](https://developer.allizom.org/it/)
  - per [Test Pilot](https://testpilot-l10n.dev.mozaws.net/)
  - per [Common Voice](https://voice.allizom.org/it)
  - per [Thunderbird.net](https://www.thunderbird.net/it/) *sito produzione
  - per [Firefox Monitor](https://fx-breach-alerts.herokuapp.com/) + [Modelli email](https://fx-breach-alerts.herokuapp.com/email-l10n)
  - per [Firefox Send](https://send.firefox.com/) *sito produzione
  - per [Mozilla Donate website](https://donate-wagtail.mofostaging.net/it/)
* [mozilla.dev.l10n.web](https://groups.google.com/forum/#!forum/mozilla.dev.l10n.web) -- Un newsgroup internazionale di riferimento per le stringhe della settimana. Condivide informazioni sui progetti correnti, anche utile per porre domande e segnalare bug ecc.
* [Transvision](https://transvision.mozfr.org/) -- Motore di ricerca esterno per le stringhe Mozilla, complementare a  Pontoon
* [Transvision Access Key](https://transvision.mozfr.org/accesskeys/) -- Rileva eventuali errori nelle access key (da controllare ogni volta che si traduce una stringa contenente access key)

**Comment by michrogit** [comment]
@AndyUrbi, ho aggiunto Thunderbird (2 stringhe). Quelle Android sono da levare perché "This is a read-only localization." Ne avevamo discusso in uno issue precedente ;-)

**Comment by AndyUrbi** [comment]
Grazie a te Michele.
Mi prendo FF

**Comment by michrogit** [comment]
Ho localizzato l'unica stringa MDN.

**Comment by Sav22999** [comment]
@michrogit ti ho fatto il QA, ho corretto solamente l'apostrofo `'` in favore di `’`

**Comment by Sav22999** [comment]
Io prendo le due stringhe di Thunderbird

**Comment by Sav22999** [comment]
Pronte per il QA (le stringhe Thunderbird)

**Comment by kitsunenosaraT** [comment]
Grazie prode ser @AndyUrbi per aver aperto lo issue!
Ho aggiunto un nuovo progetto, Mozilla.org, inoltre ho aggiornato le stringhe di Mozilla Donate: c'erano dei suggerimenti da un estraneo (probabilmente un utente straniero, ho visto dal suo profilo che suggerisce in varie lingue). Erano tutte stringhe già in memoria, quindi le ho accetate per togliercele dai piedi.
Per i progetti un po' più lunghetti, ho messo la possibilità di dividerseli.

Infine @Sav22999 Accettato Thunderbird. Grazie!

**Comment by michrogit** [comment]
Ho localizzato l'unica stringa MDN.

> @michrogit ti ho fatto il QA, ho corretto solamente l'apostrofo `'` in favore di `’`

Grazie, non mi ero accorto dell'apostrofo errato. È strano perché l'ultima volta che avevo utilizzato l'apostrofo "dritto" `'`, Pontoon me lo aveva segnalato con un'avviso 
“The following checks have failed
Apostrophe must be escaped” 
e non mi lasciava inserire il suggerimento. Mah! ;-)

**Comment by flodolo** [comment]
> Infine @Sav22999 Accettato Thunderbird. Grazie!

Non è meglio "Il nome della lista" (o "Il nome di una lista") al posto di "Un nome lista"? Peraltro, vedo che Saverio aveva entrambe le forme.

**Comment by kitsunenosaraT** [comment]
Per me vanno bene entrambe le versioni. Allora approvo l'altro
suggerimento.

Il mar 15 ott 2019, 13:19 Francesco Lodolo <notifications@github.com> ha
scritto:

**Comment by kitsunenosaraT** [comment]
- Aggiunti due piccoli progetti.
- Aggiunto il server di test del sito Mozilla Donate alla lista dei link utili.
- Accettata la stringa di MDN.

**Comment by michrogit** [comment]
@kitsunenosaraT, stavo proprio dando un'occhiata quando hai aggiornato. Ho localizzato le due stringhe L10n... una faticaccia!

**Comment by fortym2** [comment]
Prendo Common Voice

**Comment by kitsunenosaraT** [comment]
Aggiunta una seconda tranche per MDN.

**Comment by kitsunenosaraT** [comment]
@fortym2 Accettate, grazie!

**Comment by Karm46** [comment]
Pronte Mozilla.org 33 stringhe. Grazie.

**Comment by kitsunenosaraT** [comment]
Grazie a te @Karm46 
Dunque, [qui](https://www-dev.allizom.org/it/firefox/welcome/2/) c'è il sito di testo per vedere il tuo operato e [qui](https://pontoon.mozilla.org/translate/it/mozillaorg/all-resources/?status=unreviewed&string=204745) il mio QA.

Ho corretto alcune espressioni idiomatiche, per il resto rimango aperta a nuove interpretazioni 😁 
-["privacy first"](https://pontoon.mozilla.org/it/mozillaorg/all-resources/?string=204745)  è un nostro slogan ricorrente. Non è tanto "prodotti di punta nella difesa della privacy" (anche se ovviamente ci auguriamo che lo siano) quanto "prodotti che mettono la privacy al primo posto".
- [Qui](https://pontoon.mozilla.org/it/mozillaorg/all-resources/?string=204739) la "Personal Data Promise" e lo slogan sui dati erano già stati tradotti, quindi ho usato la traduzione preesistente per continuità. Tra l'altro mi sembra che "garanzia" abbia implicazioni legali, al contrario di "promessa" che è più vago. Quindi penso sia meglio non complicarci la vita.
- [Qui](https://pontoon.mozilla.org/it/mozillaorg/all-resources/?string=204736) attenzione a tradurre  "content" con "articoli": i contenuti potrebbero essere anche video, immagini, snippet, link o altre risorse. Inoltre ho trovato che un termine abbastanza riconosciuto in italiano per clickbait sia "acchiappaclic", quindi lo ho proposto nel mio suggerimento.
- [Questo slogan di Pocket](https://pontoon.mozilla.org/it/mozillaorg/all-resources/?string=204753) è un po' astruso. "Proteggere il tempo" immagino significhi non sprecarlo, ma utilizzarlo al massimo grazie alla funzione "salva per dopo" di Pocket.
- In ultimo, come al solito, ti ricordo di usare gli apostrofi orientati ’

**Comment by Karm46** [comment]
@kitsunenosaraT tutto 100% OK! Come al solito. Grazie. Sto solo avendo qualche difficoltà con l'apostrofo, pare che l'editor di OmegaT lo preferisca dritto. Per caso hai a portata di mano il riferimento relativo della guida per studiarmelo? In ogni caso vedrò ogni volta di correggerlo manualmente se non riesco a 'educare' il CAT.

**Comment by kitsunenosaraT** [comment]
@Karm46 grazie a te, accettate!
Per l'apostrofo, avevamo raccolto una tabella con le [scorciatoie da tastiera dei caratteri](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/resources/caratteri.md) proprio su questo repository. Spero possa esserti d'aiuto.

Riguardo a come immettere l'apostrofo curvo in OmegaT automaticamente, premetto che non uso quel programma da anni, ma:
- l'opzione per correggere automaticamente apostrofi e virgolette curvi si trova normalmente sotto le impostazioni di Autocorrezione nella maggior parte degli Editor.
- mi sembra che anche OmegaT abbia una funzione di Trova/Rimpiazza. Se non funziona il sistema di prima, potresti rimpiazzare gli apostrofi dritti tutti insieme alla fine della traduzione (attento però a non modificare gli apostrofi dritti dei tag e del codice)

**Comment by michrogit** [comment]
Ho visto che erano comparse 10 stringhe da tradurre per Android L10n (Firefox Reality), le ho aggiunte alle stringhe della settimana e ho lasciato i miei [suggerimenti](https://pontoon.mozilla.org/translate/it/android-l10n/all-resources/?status=missing&string=204846) ;-)

**Comment by kitsunenosaraT** [comment]
Grazie @michrogit Accettate al volo. Buona serata 🍻

**Comment by Karm46** [comment]
Mozilla Donate website 39+2 fuzzy  pronte per QA - sono servite per attualizzare la sperimentazione OmegaT. Dettagli su [#163](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/issues/163)

**Comment by kitsunenosaraT** [comment]
@Karm46 Grazie per aver terminato questo progetto.
Ecco il mio [QA](https://pontoon.mozilla.org/translate/it/mozilla-donate-website/all-resources/?status=unreviewed&string=204553). Come al solito ho fatto la revisione con il [sito di test](https://donate-wagtail.mofostaging.net/it/) sott'occhio per interpretate le stringhe al meglio secondo contesto.

Un appunto sull'"annullare le donazioni" nel caso delle donazioni mensili.
Anche se abitualmente traduciamo "cancel" con "annulla", annullare può essere interpretato come "riprendersi indietro i soldi". A scanso di spiacevoli equivoci, in questo caso è più esatto parlare di "interrompere le donazioni", ovvero da un certo momento l'utente smette di versare mensilmente denaro a Mozilla, ma non riceve indietro i soldi già donati.

**Comment by Karm46** [comment]
Vista l'importanza della traduzione non mi resta che fare come al solito tesoro degli affinamenti del QA per aggiornare le mie capacità di traduttore e gli archivi che vado aggiornando per il CAT. Grazie, sono riuscito a trovare solo una ripetizione corretta su due stringe. Chiudi pure tutto. Grazie. Io continuo a cercare di alleggerirti il lavoro e appena possibile approfondirò anche la questione degli apostrofi cercando una soluzione razionale.

**Comment by kitsunenosaraT** [comment]
Grazie @Karm46 ho accettato i tuoi due suggerimenti e continuo a seguire i tuoi progressi.
Qui chiudiamo e ci vediamo nello issue #193 😁
