### ISSUE TITLE
QA di Firefox Monitor

### ISSUE THREAD

**Issue by flodolo** [MozillaItalia/Mozilla-Italia-l10n-guide#207]
Apro una nuova discussione, visto che rimarrà in circolazione per più di una settimana.

La funzione per risolvere le violazioni di dati non è ancora sul server DEV, è solo disponibile su un server demo temporaneo: https://monitor-v2.herokuapp.com/

In termini pratici, significa che le correzioni fatte in Pontoon e confermate non saranno disponibili automaticamente, e potremmo dover aspettare qualche giorno per verificarle.

**Comment by flodolo** [comment]
Una cosa che ho notato: "known data breach" è tradotto qualche volta come "violazione di dati nota" e altre come "violazione di dati conosciuta". Ho cercato di uniformare con la seconda, visto che è la più usata.

Le correzioni sono pronte da controllare
https://pontoon.mozilla.org/it/firefox-monitor-website/all-resources/?status=unreviewed&string=198897

Ce ne sono un paio dove ho cercato di sfruttare Fluent.

https://pontoon.mozilla.org/it/firefox-monitor-website/all-resources/?search=progress-status&string=206968

```
progress-status =
    { $numResolvedBreaches ->
        [one] { $numResolvedBreaches } violazione su { $numTotalBreaches } contrassegnata come risolta
       *[other] { $numResolvedBreaches } violazioni su { $numTotalBreaches } contrassegnate come risolte
    }
```

Questa produce traduzioni abbastanza orribili, perché il plurale è determinato dal numero totale di violazioni risolte (es. "1 violazioni su 2 contrassegnate come risolte"). Ho provato a usare il numero di violazioni totale al suo posto. Dovrebbe funzionare, ma è da verificare.

```
progress-status =
    { $numTotalBreaches ->
        [one] { $numResolvedBreaches } su { $numTotalBreaches } violazioni contrassegnata come risolta
       *[other] { $numResolvedBreaches } su { $numTotalBreaches } violazioni contrassegnate come risolte
    }
```

https://pontoon.mozilla.org/it/firefox-monitor-website/all-resources/?search=appears-in-x-breaches&string=198897

```
appears-in-x-breaches =
    { $breachCount ->
        [one] È stato coinvolto in { $breachCount } violazione conosciuta.
       *[other] È stato coinvolto in { $breachCount } violazioni conosciute.
    }
```

`È stato coinvolto in 0 violazioni conosciute.` è orribile, ho aggiunto un caso `0`.

```
appears-in-x-breaches =
    { $breachCount ->
        [0] Non è stato coinvolto in alcuna violazione conosciuta.
        [one] È stato coinvolto in { $breachCount } violazione conosciuta.
       *[other] È stato coinvolto in { $breachCount } violazioni conosciute.
    }
```

**Comment by kitsunenosaraT** [comment]
Ho accettato i nuovi suggerimenti, vediamo come stanno 👍 
Ps. Per il sito temporaneo, ci sono delle credenziali "di prova" per accedere? Io ho provato col mio account Firefox, ma non me lo riconosce.

**Comment by flodolo** [comment]
> Ps. Per il sito temporaneo, ci sono delle credenziali "di prova" per accedere? Io ho provato col mio account Firefox, ma non me lo riconosce.

Purtroppo no. Io ho tre account FxA e me ne ha accettato solo uno :-(

In teoria dovrebbero metterlo sul DEV server la prima settimana di febbraio, per cui abbiamo tempo per correggere se necessario.

**Comment by flodolo** [comment]
La nuova versione dovrebbe andare online domani, mi sembra che tutto funzioni come previsto.
