### ISSUE TITLE
Traduzione articolo "Publishing your website"

### ISSUE THREAD

**Issue by Sav22999** [MozillaItalia/Mozilla-Italia-l10n-guide#223]
Questo è lo issue dedicato alla traduzione dell'articolo [
Publishing your website
](https://wiki.developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/Publishing_your_website).

**URL originale:** https://wiki.developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/Publishing_your_website
**URL traduzione:** https://wiki.developer.mozilla.org/it/docs/Learn/Getting_started_with_the_web/Pubbicare_sito
**Progresso:**
  -  [x] Pronto per la revisione
  -  [x] Pronto per la pubblicazione

### Prima di iniziare
- Crea un account GitHub (se non lo hai già): ti servirà sia per scrivere in questo issue, sia per accedere a MDN
  - (Facoltativo) Installa il componente aggiuntivo [MozIta L10n Addons] (https://addons.mozilla.org/it/firefox/addon/mozita-l10n-addons/) per accedere più facilmente ai caratteri speciali come `’ “ ” È` ecc.
- Leggi "[Come tradurre le pagine di MDN](https://developer.mozilla.org/it/docs/MDN/Contribute/Localize/Translating_pages)"

- Leggi i capitoli della guida. Se lo desideri, lascia un feedback nel relativo issue:
  - Capitolo 1 – [Buone norme di traduzione tecnica](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/1-Buone_norme_di_traduzione.md) Feedback: issue #91 
  - Capitolo 2 – [Linee guida di Mozilla Italia](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/2-Linee_guida_di_Mozilla_Italia.md) Feedback: issue #138
  - Capitolo 3 – [Flusso di lavoro](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/3-Flusso_di_lavoro.md) Feedback: issue #24 
  - Capitolo 4 – [Tipi di file](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/4-Tipi_di_file.md) Feedback: issue #31 
  - Capitolo 5  – [Risorse esterne](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/5-Risorse_esterne.md) Feedback: issue #36 

## Link Utili
* Motori di ricerca per la terminologia
  - [Pontoon: tutti i progetti](https://pontoon.mozilla.org/it/all-projects/all-resources/?utm_source=pontoon-addon&string=66616) -- Per gli elementi UI, le funzioni e altra terminologia dei prodotti Mozilla.
  - [Transvision](https://transvision.mozfr.org/) -- Motore di ricerca esterno per i software e i siti  Mozilla, complementare a Pontoon.
  - [Microsoft Language Portal](https://www.microsoft.com/en-us/language/Search?langID=408&Source=true&productid=0) -- Per gli elementi UI, le funzioni e altra terminologia dei prodotti Microsoft.

❗️ **N.B.** Per segnalare la traduzione di un nuovo articolo utilizzare lo issue indice #217.

**Comment by kitsunenosaraT** [comment]
@dag7dev Ciao! Ho letto sul gruppo Telegram che la tua traduzione è pronta ma riscontri dei problemi a pubblicarla. Però, se guardo la pagina MDN, non è ancora stata registrata la pagina italiana nel menu a discesa delle lingue.
Quando hai iniziato a tradurre, sei andato su "Languages" > "Add a translation" > "Italiano (it)"?
Perché se invece hai fatto semplicemente "Edit" significa che stai cercando di modificare l'articolo in inglese, e sarebbe questa la radice del problema.

**Comment by dag7dev** [comment]
Dopo mille peripezie: https://wiki.developer.mozilla.org/it/docs/Learn/Getting_started_with_the_web/Pubbicare_sito$edit

C'e' un errore nello slug purtroppo, per il resto sono riuscito a pubblicare, attendo revisione!

**Comment by Mte90** [comment]
Nella prima frase in italiano si parla della tua creazione ma la versione in inglese non ne parla.
I domini nella prima sezione nella lista non sono renderizzati come nella pagina in inglese.
C'è un riferimento a quanto costa ma non è un link, nei precedenti sono stati messi anche se puntano a pagine inesistenti.
Nella sezione consiglio domain names è rimasto in inglese ma direi di tradurre con "registra domini" che è uno dei termini usati in italia. I nostri ISP in italia non offrono più spazio per fare siti come 10 anni fà non so se è il caso di toglierla.

Non sono d'accordo con il resto di quella sezione ma nella versione in inglese che ha dei problemi ma non ci riguarda.

Publishing with github ha del testo che non è in corsivo come la versione originale.
` Per esempio, per il nome utente chrisdavidmills, go to chrisdavidmills.github.io.` l'ultima parte non è stata tradotta.
Gli approfondimenti non puntano a nessun link.

**Comment by kitsunenosaraT** [comment]
Grazie @Mte90 
Per tutti i problemi di formattazione e link mancanti ci penso io, lavorando sul codice sorgente. Per la barra laterale, non so come farla puntare agli articoli italiani perché non ci sono i soliti link, ma solo questo codice:

`{{PreviousMenuNext("Learn/Getting_started_with_the_web/JavaScript_basics", "Learn/Getting_started_with_the_web/How_the_Web_works", "Learn/Getting_started_with_the_web")}}`

OK per "registra domini".
Per "web server", non è il caso di scrivere "[server web](https://it.wikipedia.org/wiki/Server_web)" all'italiana?

> I nostri ISP in italia non offrono più spazio per fare siti come 10 anni fà non so se è il caso di toglierla.

Ti riferisci a questo passaggio, che nell'originale non c'era?

>Alcune volte le compagnie offrono soluzioni di hosting e dominio in un unico pacchetto. I servizi gratuiti di solito non hanno bisogno di software FTP per caricare i file— puoi semplicemente trascinare e rilasciare i file nella loro interfaccia web.

**Comment by Mte90** [comment]
Quel codice include i link, basta metterli in versione italiana e un domani quando quelle pagine saranno disponibili sarà tutto apposto, tanto come uno le apre che non esistono c'è una pagina ad hoc.
Onestamente per server web mi trovi ad usarli entrambi quindi non so qual'è la cosa migliore ma seguire wikipedia sicuramente è il modo più semplice.

Il punto sugli isp (come telecom o fastweb) è una citazione che c'è nella traduzione (e nella versione originale) riguardo al fatto che danno spazio web per i siti, da noi non lo fanno più da circa 10 anni.

**Comment by dag7dev** [comment]
@Mte90 non so se può interessarti, ma Tiscali ad esempio offre ancora questo servizio

**Comment by Mte90** [comment]
Allora c'è ancora qualcuno che lo fa, quindi lasciamolo allora.

**Comment by kitsunenosaraT** [comment]
@dag7dev ho fatto la revisione stilistica, [qui](https://wiki.developer.mozilla.org/it/docs/Learn/Getting_started_with_the_web/Pubbicare_sito$compare?locale=it&to=1623222&from=1622078) vedi il diff con le modifiche.

Se mi permetti, alcuni suggerimenti per la prossima volta:
- traduci / aggiungi i tag in fondo alla pagina di traduzione
- non omettere mai i link all'interno del testo. Le wiki sono fatte apposta per avere contenuti ipercollegati. In questo caso ho puntato i link agli articoli in italiano dove possibile, negli altri casi ho messo il link all'articolo inglese e lasciato il titolo inglese per far vedere che non è ancora stato tradotto (quando verrà tradotto, bisognerà sostituirlo con l'esatto titolo scelto dal traduttore).
- Fai attenzione anche alla formattazione, alle parole con enfasi o in stile codice. Se hai difficoltà, puoi sempre usare la visuale a "Sorgente" (pulsante in alto a sinistra nella barra degli strumenti dell'articolo) per visulazzare tutti i tag.
- Cerca di mantenere un tono uniforme per tutto l'articolo: in alcuni punti sei molto formale, in altri usi colloquialismi. Anche nella procedura che spiega come usare GitHub, hai tradotto un campo "Nome del repository" ma hai lasciato gli altri in inglese (la scelta giusta è lasciarli in inglese perché GithHub non ha l'interfaccia tradotta in italiano).


Hai aggiunto del tuo all'articolo in alcuni punti, e mi pare una cosa bella. Però in altri punti mi sembra che tu abbia semplificato un po' troppo. es. (chiedo anche a @Mte90 di ricontrollare questi punti):

---

- EN: GitHub has a very useful feature called GitHub Pages, which allows you to expose website code live on the web.
- Originale: GitHub ha una funzionalità molto utile chiamata GitHub Pages, che che ti permette di pubblicare un sito web.
- Modificata: GitHub ha una funzionalità molto utile chiamata GitHub Pages, che permette di generare un sito web dal codice in tempo reale.



---

- EN: Google App Engine is a powerful platform that lets you build and run applications on Google’s infrastructure — whether you need to build a multi-tiered web application from scratch or host a static website.
- Originale: Google App Engine è una piattaforma che ti permette di costruire ed eseguire applicazioni sui server di Google, sia se hai bisogno di costruire un'applicazione da zero sia se hai bisogno di creare una pagina statica.
- Modificata: Google App Engine è una piattaforma che permette di sviluppare ed eseguire applicazioni attraverso l'infrastruttura Google, sia per lo sviluppo da zero di applicazioni web multi-livello che per ospitare un sito web statico.

---
- EN: However, the features are limited, and these apps usually don't provide hosting space for assets (like images).
- Originale: Le funzionalità base sono però limitate e di solito non offrono spazio per ospitare i tuoi file (come le immagini).
- Modificata: Le funzionalità base sono però limitate e di solito non offrono spazio per ospitare risorse (come le immagini).

 Ancora per @Mte90

> Quel codice include i link, basta metterli in versione italiana e un domani quando quelle pagine saranno disponibili sarà tutto apposto, tanto come uno le apre che non esistono c'è una pagina ad hoc.

Questo è il codice della sidebar.

`{{PreviousMenuNext("Learn/Getting_started_with_the_web/JavaScript_basics", "Learn/Getting_started_with_the_web/How_the_Web_works", "Learn/Getting_started_with_the_web")}}`

Potresti farmi un esempio di come modificarlo per puntare all'italiano, oppure modificarlo direttamente tu?

> Nella sezione consiglio domain names è rimasto in inglese ma direi di tradurre con "registra domini" che è uno dei termini usati in italia.

Ho fatto qualche ricerca per "registrar", e a quanto pare è molto usato anche in [italiano](https://it.wikipedia.org/wiki/Registrar), per cui tenderei a lasciarlo.

Un'ultima cosa: **repository**. Mi sembra di averlo sentito sempre al maschile, cioé *il** repository.

Mi raccomando Dag, se hai dubbi o non sei d'accordo su qualcosa, non esitare a scrivere qui.

**Comment by Sav22999** [comment]
Non intervengo sulla parte stilistica, volevo solo dire che Repository io l'ho sempre sentita al femminile invece ("la repo", "la repository"). Ma lascio al revisore tecnico di questo articolo (daniele) decidere quale sia meglio

**Comment by Mte90** [comment]
Concordo con Sara meglio mantenere la versione originale che include più informazioni. Registrar va bene è tecnico com termine ma lo ho usato anch'io.
Per la questione repo io lo uso sempre al maschile, "il repo" ecc.

`{{PreviousMenuNext("Learn/Getting_started_with_the_web/Basi_di_JavaScript", "Learn/Getting_started_with_the_web/Come_funziona_-_il_web", "Learn/Getting_started_with_the_web")}}`

Però direi che prima di questo codice forse è il caso di creare tutte le varie pagine e definire la loro url.

**Comment by dag7dev** [comment]
@kitsunenosaraT 

Mia:
```Avrai sicuramente bisogno di acquistare: ```
Modificato:
```"Per gestire più liberamente i contenuti e l'aspetto del proprio sito, molti scelgono di acquistare"```
Di fatto sei obbligato ad avere quelle due cose, per questo ho scritto sicuramente!

Al paragrafo di Google App Engine: 
Modificato: ```"applicazioni web multi-livello"```
Ti riferisci al multi-tier? Ho dovuto cercare cosa fosse un applicazione web multi-livello, ho omesso quella parte perché é un po' complicata per qualcuno alle prime armi.

Per il resto tutto ok!

**Comment by kitsunenosaraT** [comment]
@dag7dev

Grazie per la risposta.

Allora,

> Di fatto sei obbligato ad avere quelle due cose, per questo ho scritto sicuramente!

In realtà non sei "obbligato", l'articolo stesso ti dice il contrario. 
L'articolo offre due alternative per iniziare a trafficare coi siti web:
1 - acquistarsi dominio e FTP per fare le cose come i professionisti (se vuoi personalizzare al massimo il tuo sito)
2 - partire accontentandoti di utilizzare GitHub Pages o simili (che non hanno bisogno di quelle due cose ma non ti permettono molta personalizzazione).

Ogni lettore deve scegliere in base alle sue esigenze, se dici "corri subito a comprarti il dominio" fraintendi l'intento dell'autore.


> Ti riferisci al multi-tier? Ho dovuto cercare cosa fosse un applicazione web multi-livello,

In realtà non sono molto ferrata in questo campo, ho usato la definizione di Microsoft ([qui trovi la definizione](https://www.microsoft.com/en-us/language/Search?&searchTerm=multi-tier%20application&langID=408&Source=true&productid=undefined) )
Tu come la tradurresti? Lasceresti multi-tier?

> ho omesso quella parte perché é un po' complicata per qualcuno alle prime armi.

Capisco cosa intendi, ma anche se un lettore è alle prime armi, si trova lì proprio per imparare quei concetti. Quindi, secondo me, in questi casi dovremmo piuttosto cercare di spiegarlo con parole nostre, ma non saltare a piè pari i concetti solo perché sono difficili.

**Comment by dag7dev** [comment]
@kitsunenosaraT 
Onestamente non so se sia giusto "multi-livello", non ho mai sentito né multi-livello né multi-tier, sarei più propenso per la controparte inglese.

(questo é uno dei motivi per il quale volevo omettere proprio l'intero vocabolo, tralasciando il dubbio su cosa usare, rende ad una persona non proprio esperta un po' più difficile la comprensione del testo, considerando che l'articolo è dedicato a chi non ha proprio esperienza sul web)

**Comment by kitsunenosaraT** [comment]
@dag7dev 
Per multi-tier ho trovato [questo articolo](https://it.wikipedia.org/wiki/Architettura_multi-tier) che spiega di cosa si tratta. Fa anche degli esempi di come il multi-tier venga impiegato nelle applicazioni web, quindi direi che combacia con quanto scritto nell'articolo MDN.

Nell'articolo questo tipo di architettura viene chiamata in vari modi: multi-tier, n-tier, multi-strato, multi-livello…

Se per te va bene, metterei "multi-tier".

**Comment by kitsunenosaraT** [comment]
Dopo consultazione su Telegram ho sistemato anche l'ultimo dettaglio:
> applicazioni web multi-livello
▶️ 
> applicazioni web multi-tier (un tipo di architettura client-server molto diffusa)

e dichiaro l'articolo pronto.
Grazie @dag7dev  e @Mte90 !
