### ISSUE TITLE
Translating MDN – HTTP

### ISSUE THREAD

**Issue by kitsunenosaraT** [MozillaItalia/Mozilla-Italia-l10n-guide#227]
Per i volontari interessati a cimentarsi nella traduzione di un articolo di Mozilla Developer Nework, ecco un breve articolo di introduzione all'HTTP.

## Informazioni sul progetto
**URL**: https://wiki.developer.mozilla.org/en-US/docs/Glossary/HTTP
**URL traduzione**: https://wiki.developer.mozilla.org/it/docs/Glossary/HTTP
**Formato di file** markup wiki (testo con tag)
**Strumenti** a scelta tra [interfaccia di traduzione MDN](https://developer.mozilla.org/) (online) / editor di testo semplice / [OmegaT](http://omegat.org/) (offline)

**Progresso:**
- [x] Pronto per la revisione tecnica
- [x] Pronto per la revisione linguistica
- [x] Pronto per la pubblicazione

Traduzione della definizione del termine "protocollo", collegato all'articolo
URL: https://wiki.developer.mozilla.org/en-US/docs/Glossary/protocol
URL traduzione: https://wiki.developer.mozilla.org/it/docs/Glossary/Protocollo
**Progresso:**
- [x] Pronto per la revisione tecnica
- [x] Pronto per la revisione linguistica
- [x] Pronto per la pubblicazione

Traduzione della definizione di "REST", collegato all'articolo
URL: https://wiki.developer.mozilla.org/en-US/docs/Glossary/REST
URL traduzione: https://wiki.developer.mozilla.org/it/docs/Glossary/REST
**Progresso:**
- [x] Pronto per la revisione tecnica
- [x] Pronto per la revisione linguistica
- [x] Pronto per la pubblicazione

### Prima di iniziare
- Crea un account GitHub (se non lo hai già): ti servirà sia per scrivere in questo issue, sia per accedere a MDN
  - (Facoltativo) Installa il componente aggiuntivo [MozIta L10n Addons] (https://addons.mozilla.org/it/firefox/addon/mozita-l10n-addons/) per accedere più facilmente ai caratteri speciali come `’ “ ” È` ecc.
- Leggi "[Come tradurre le pagine di MDN](https://developer.mozilla.org/it/docs/MDN/Contribute/Localize/Translating_pages)"

- Leggi i capitoli della guida. Se lo desideri, lascia un feedback nel relativo issue:
  - Capitolo 1 – [Buone norme di traduzione tecnica](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/1-Buone_norme_di_traduzione.md) Feedback: issue #225 
  - Capitolo 2 – [Linee guida di Mozilla Italia](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/2-Linee_guida_di_Mozilla_Italia.md) Feedback: issue #138
  - Capitolo 3 – [Flusso di lavoro](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/3-Flusso_di_lavoro.md) Feedback: issue #24 
  - Capitolo 4 – [Tipi di file](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/4-Tipi_di_file.md) Feedback: issue #31 
  - Capitolo 5  – [Risorse esterne](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/5-Risorse_esterne.md) Feedback: issue #36 

#### Prendere in carico il progetto
* Se non lo hai già fatto, [registra un account gratuito su GitHub](https://github.com/join?source=header-home)
* Scrivi nell’area commenti qui di seguito che vuoi occuparti di questo progetto
* Accedi a [MDN](https://developer.mozilla.org/) con il tuo account GitHub
* Attieniti alle [istruzioni per MDN del capitolo 3](https://github.com/kitsunenosaraT/Mozilla-Italia-l10n-guide/blob/master/it/3-Flusso_di_lavoro.md#mdn) e ai suggerimenti del resto della guida, in particolare [i consigli pratici del capitolo 2](https://github.com/kitsunenosaraT/Mozilla-Italia-l10n-guide/blob/master/it/2-Linee_guida_di_Mozilla_Italia.md#consigli-pratici)
* per qualsiasi problema o domanda scrivi pure in questo issue
* e buona traduzione! 🎊 

## Link Utili
* Motori di ricerca per la terminologia
  - [Pontoon: tutti i progetti](https://pontoon.mozilla.org/it/all-projects/all-resources/?utm_source=pontoon-addon&string=66616) -- Per gli elementi UI, le funzioni e altra terminologia dei prodotti Mozilla.
  - [Transvision](https://transvision.mozfr.org/) -- Motore di ricerca esterno per i software e i siti  Mozilla, complementare a Pontoon.
  - [Microsoft Language Portal](https://www.microsoft.com/en-us/language/Search?langID=408&Source=true&productid=0) -- Per gli elementi UI, le funzioni e altra terminologia dei prodotti Microsoft.

❗️ **N.B.** Per segnalare la traduzione di un nuovo articolo utilizzare lo issue indice #217.

**Comment by xplosionmind** [comment]
Nel corso della traduzione della [pagina iniziale di HTTP](https://wiki.developer.mozilla.org/en-US/docs/Glossary/HTTP), mi sono imbattuto in un termine non tradotto, di conseguenza, ho tradotto anche [la definizione di "protocollo" nel Glossario](https://wiki.developer.mozilla.org/it/docs/Glossary/Protocollo). Riporto di seguito un dubbio su slug e tag che ho scritto su Telegram.

>dato che la maggior parte dei termini a cui si fa riferimento nel glossario, la cui definizione è tradotta in italiano, rimangono invariati (es. Web, AJAX, Internet) non riesco a capire come fare per lo slug di termini come "protocol"-->"protocollo". Devo cambiare solo il titolo o anche lo slug? Nelle linee guida di traduzione MDN c'è scritto di fare rifetimento agli altri termini tradotti in quella lingua, ma, per il motivo di cui sopra, non trovo riferimenti validi.
>
>Per quanto riguarda i tag, invece?

**Comment by xplosionmind** [comment]
ho anche un altro problema: dopo aver tradotto i tag, una volta salvata la pagina, il tag che io ho tradotto digitando `Glossario` (senza accento) compare così:

![Screenshot 2020-04-16 at 11 45 36 AM](https://user-images.githubusercontent.com/42862428/79441835-09a9ae00-7fd8-11ea-8be2-baad82fbbc5a.jpg)

**Comment by xplosionmind** [comment]
> Devo cambiare solo il titolo o anche lo slug? Nelle linee guida di traduzione MDN c'è scritto di fare rifetimento agli altri termini tradotti in quella lingua, ma, per il motivo di cui sopra, non trovo riferimenti validi.

@kitsunenosaraT mi ha risposto su Telegram: è sempre meglio tradurre anche lo slug.

**Comment by Sav22999** [comment]
@xplosionmind prima di tradurre pagine MDN, per favore, avvisaci così facciamo una lista completa e possiamo fare revisione in maniera corretta (altrimenti rimangono pagine non revisionate) 😄 

Visto che traduci in italiano, penso sia bene tradurre i termini nello slug, anche perché servono per "trovare" la pagina correttamente... e una persona, se vuole una pagina in italiano, cercherà termini in italiano, no?

Per il "Glossário" non saprei 🤔

**Comment by Sav22999** [comment]
Ops. Non avevo ancora letto né il tuo ultimo commento, né la risposta di Sara.

**Comment by xplosionmind** [comment]
> @xplosionmind prima di tradurre pagine MDN, per favore, avvisaci così facciamo una lista completa e possiamo fare revisione in maniera corretta (altrimenti rimangono pagine non revisionate)

Ok, certo, perdonatemi!

**Comment by xplosionmind** [comment]
> Per il "Glossário" non saprei 🤔

Temo sia un bug della webapp di traduzione di Mozilla

**Comment by kitsunenosaraT** [comment]
@xplosionmind Scusa, ti chiedo una conferma. Hai barrato la casella "Pronto per la revisione" perchè hai finito? Se sì, procedo con la revisione. 😄

**Comment by xplosionmind** [comment]
articolo tradotto e pronto per la revisione

@kitsunenosaraT ho corretto da `HTML` a `HTTP` nel titolo dello issue, credo ti sia confusa

**Comment by kitsunenosaraT** [comment]
😱 Hai ragione, l'ho confuso con il titolo di un altro articolo in traduzione sull'HTML!
Grazie per averlo sistemato. Ti scriverò qui appena terminata la revisione.
Buona serata!

**Comment by Sav22999** [comment]
@kitsunenosaraT proviamo a usare i label come discusso su Telegram? 😄

**Comment by Sav22999** [comment]
@xplosionmind Revisione tecnica completata 😄 ecco le modifiche che ho apportato
- `protocol` anche se è un termine tecnico, viene ormai tradotto sempre con `protocollo`, quindi ho inserito la sua traduzione
- `semplice` -> `in chiaro`
- `su internet` -> `in Internet`

potete procedere con la Revisione linguistica

**Comment by Sav22999** [comment]
Anche le altre due voci sono pronte per la revisione linguistica

**Comment by kitsunenosaraT** [comment]
@Sav22999 ho aggiunto il tag.

@xplosionmind ho fatto dei piccoli ritocchi. Puoi vedere il diff dalla versione di Sav22999 nello [storico](https://wiki.developer.mozilla.org/it/docs/Glossary/HTTP$compare?locale=it&to=1618789&from=1618779)

In particolare, nell'ultimo paragrafo: 

>However, HTTP can also be used as a basis for REST web services from server to server or AJAX requests **within** web sites to make them more dynamic.

Tu hai messo "fra siti web", ma la fonte inglese sembra suggerire che le richieste avvengano **all'interno** del sito web. Ha senso, tecnicamente parlando?

**Comment by kitsunenosaraT** [comment]
Ecco le modifiche per il mini-articolo [Protocollo](https://wiki.developer.mozilla.org/it/docs/Glossary/Protocollo$compare?locale=it&to=1618796&from=1618526).

Anche qui:

> A protocol is a system of rules that define how data is exchanged **within** or between computers.

Quel "within" non l'hai tradotto, ma mi sembra che sia importante specificarlo. Chiedo, ovviamente, se ha senso.

**Comment by kitsunenosaraT** [comment]
Ecco anche le modifiche dell'articolo [Rest](https://wiki.developer.mozilla.org/it/docs/Glossary/REST$compare?locale=it&to=1618809&from=1618781).

Qui in realtà ho un paio di dubbi tecnici. "constraints" è stato tradotto con "parametri" o "canoni", ma dato l'argomento, non sarebbe più opportuno chiamarli "[vincoli](https://it.wikipedia.org/wiki/Representational_State_Transfer)"?

Inoltre, forse è una sottigliezza, ma qui:

> Beginners can assume a REST API means an HTTP service that can be *called* using standard web libraries and tools.

> I principianti possono concepire un REST API come un servizio HTTP che può essere *sfruttato* usando librerie e strumenti web.


Non sarebbe più esatto usare "può essere *chiamato*?
*Call* ("chiamata" in italiano secondo il [Language Portal di Microsoft](https://www.microsoft.com/en-us/language/Search?&searchTerm=call&langID=408&Source=true&productid=undefined), terza voce) è un termine abbastanza specifico.

Fatemi sapere entrambi cosa ne pensate 😀

**Comment by Sav22999** [comment]
@kitsunenosaraT ah, sì. Ammetto che non ho visto la parte inglese (o meglio, quando trovavo qualcosa di non chiaro andavo a verificare) ... per quello credevo fosse meglio fare prima la revisione stilistica, perché in quella revisione viene analizzato il testo inglese e la traduzione italiana. Mentre, la revisione tecnica punta più sul verificare se hanno senso tecnicamente le frasi, e se c'è qualche termine da sostituire... ha senso quello che dico, @kitsunenosaraT ?

**Comment by kitsunenosaraT** [comment]
Onestamente, no, non credo che sia un ragionamento molto sensato, scusa.

Se mai è il revisore tecnico che deve analizzare il testo inglese
accuratamente, altrimenti come fa ad assicurarsi che il traduttore abbia
effettivamente usato i termini giusti senza omettere nulla (proprio come è
successo in questo caso)?

Mi sembra assurdo pretendere di verificare il senso di una traduzione senza
confrontarla con l'originale.

Piuttosto è il revisore stilistico che in teoria dovrebbe concentrarsi
sull'italiano (sull'ortografia, la punteggiatura, la scorrevolezza) dando
per scontato che la conformità con l'originale sia già stata verificata da
qualcuno di più esperto.

Anche perché adesso sono cose semplici e ho potuto riconoscere anch'io le
imprecisioni, ma con tecnologie più complesse potrebbero sfuggirmi e ci
vorrebbe qualcuno che conosca la materia per scovarli.



Il ven 17 apr 2020, 20:08 Saverio Morelli <notifications@github.com> ha
scritto:

**Comment by Sav22999** [comment]
Giusto anche questo, non ci avevo pensato. Chiedo scusa, avevo capito male io. Dalla prossima volta, quindi, verificherò anche l'originale. Meglio averlo capito subito e non tardi direi :) e grazie per le delucidazioni
________________________________

**Comment by kitsunenosaraT** [comment]
> Meglio averlo capito subito e non tardi direi :) e grazie per le delucidazioni

Figurati! 😃 È un procedimento nuovo quello che stiamo affrontando, dobbiamo procedere un passo alla volta e correggere ciò che non funziona strada facendo.

A questo proposito, io proporrei anche di aprire *uno issue per articolo* invece di mettere più articoli nello stesso issue, anche se collegati. In questo modo, non solo risulta più ordinato, ma risulterà più facile tenere un indice degli articoli tradotti.

**Comment by xplosionmind** [comment]
perdonate il ritardo. Ho riletto l'articolo e direi che è perfetto. Grazie! A questo punto (spero sia giusto fare così) spunto anche `pronto per la pubblicazione`. Forse dovrei anche chiudere l'issue ma aspetto conferma di @kitsunenosaraT per questo.

**Comment by kitsunenosaraT** [comment]
Grazie mille @xplosionmind 
Ho rimosso il tag di richiesta revisione qui e sugli articoli di MDN. Adesso sono ufficiali.

Congratulazioni 🍾 😄 

Qui chiudiamo, e quando vuoi tradurre qualche issue nuovo, puoi scrivere nello issue #217
