### ISSUE TITLE
(IT) Capitolo 1 – Buone norme di traduzione

### ISSUE THREAD

**Issue by kitsunenosaraT** [MozillaItalia/Mozilla-Italia-l10n-guide#23]
**ENGLISH**
This is the *issue* (or topic) where new volunteers can discuss enhancements to the first draft of chapter  [1-Buone norme di traduzione.md](https://github.com/kitsunenosaraT/Mozilla-Italia-l10n-guide/blob/master/it/1-Buone_norme_di_traduzione.md)

This chapter deals with general translation best practices such as syntax, punctuation, false friends etc.
Please, read the chapter linked above and write down in this section all your comments, suggestions and impressions.
To quote the part you are referring to, copy-paste it in your comment and enter the character `>` in front of the first letter, just like this:
___
```
>This is the first chapter of the guide and deals with such matters as general translation best practices: syntax, punctuation, false friends etc.

It would be useful to add to the list a section about the most common mistakes.
```
will be displayed as:

>This is the first chapter of the guide and deals with such matters as general translation best practices: syntax, punctuation, false friends etc.

It would be useful to add to the list a section about the most common mistakes.
___
**ITALIANO**
Questo *issue* è lo spazio dove i nuovi volontari possono discutere i miglioramenti da apportare alla prima bozza del capitolo [1-Buone norme di traduzione.md](https://github.com/kitsunenosaraT/Mozilla-Italia-l10n-guide/blob/master/it/1-Buone_norme_di_traduzione.md)

Il capitolo raccoglie le buone norme universali per la traduzione tecnica, dunque sintassi, punteggiatura, *false friend* e simili.
Per partecipare leggi il capitolo nel paragrafo precedente e scrivi in questa sezione i tuoi commenti, suggerimenti e impressioni.
Per citare una parte specifica della guida, copia-incolla la parte rilevante nel campo dei commenti e inserisci davanti il carattere `>`, come nel seguente esempio:
___
```
>In ultimo bisogna evitare le trappole dei false friend (parole straniere che somigliano a termini esistenti italiani, ma hanno un significato diverso). Alcuni dei principali sono:

Vorrei suggerire alcuni *false friend* da aggiungere alla lista…
```
verrà visualizzato come:
>In ultimo bisogna evitare le trappole dei false friend (parole straniere che somigliano a termini esistenti italiani, ma hanno un significato diverso). Alcuni dei principali sono:

Vorrei suggerire alcuni *false friend* da aggiungere alla lista…

___
## Aggiornamenti per la seconda bozza
- [x] #Virgola, correggi “dopo le congiunzioni” con “prima delle congiunzioni” (eliogi)
- [x] #Virgolette, aggiungi riferimento ai diversi layout di tastiera (eliogi)
~- #Maiuscole e minuscole, aggiungi nota sui vari “internet” (con la minuscola)~ **In cap 2**
- [ ] Aggiungi appendice con le varie combinazioni e entity HTML per i caratteri più usati (gialloporpora) **In appendice**
- [x] Aggiungi istruzioni sulla conversione dei numeri (*billion*, decimali ecc.) (gialloporpora)
- [ ] #Falsi amici, aggiungi termine *narrative* (gialloporpora)
~-Aggiungi esempi sull’importanza del contesto, es. "post" sostantivo o verbo? (EugenioPetulla)~ **In cap 3**
~- Aggiungi click > clic, to click > fare clic e non "cliccare" (Mte90)~ **In cap 2**
- [x] Aggiungi regole sulla d eufonica (Mte90)
- [x] Sostituisci le combinazioni dei tasti per Windows in Alt + codice (le scorciatoie non funzionano in tutte le versioni di Windows) (Sav22999)
- [x] Aggiungi regole per la formattazione elenchi, vedi commento più sotto (Underpass)

**Comment by eliogi** [comment]
> In inglese la virgola viene utilizzata anche dopo le congiunzioni.

Forse volevi dire "prima" delle congiunzioni?

**Comment by eliogi** [comment]
Per evidenziare la punteggiatura sono stati usati degli asterischi, è voluto?

Es: **.**

**Comment by eliogi** [comment]
Sul discorso delle virgolette, metterei giusto una nota riguardo la tastiera utilizzata, dicendo di verificare il layout della propria tastiera.

**Comment by eliogi** [comment]
> Si sta diffondendo sempre di più l'uso di scrivere sempre indifferentemente in minuscolo le parole “internet” e “web”, Mozilla si attiene alla seguente norma vigente.

Qui - da nerd purista - ci sarebbe un'ulteriore distinzione: internet e Internet.
Riporto da una [fonte](http://www.bplab.bs.unicatt.it/linuxfacile/linuxfacile2-1-html/node16.html):
> Internet, con la lettera maiuscola, fa riferimento alla rete che iniziò con il progetto ARPAnet e continua oggigiorno come la confederazione di tutte le reti tcp/ip direttamente o indirettamente collegate al backbone(Il backbone è l'infrastruttura portante delle telecomunicazioni) degli Stati Uniti. La parola "internet" con tutte le lettere minuscole rappresenta tutte le reti, di piccole o grandi dimensioni, che utilizzano lo stesso protocollo di comunicazione. Ogni internet (lettere minuscole) non necessariamente dev'essere connessa a Internet (lettera maiuscola iniziale) e non necessariamente devono utilizzare tcp/ip come loro protocollo di base.

**Comment by eliogi** [comment]
> submit: non sottomettere (assoggettare qualcuno al proprio volere), ma sottoporre (ad esame).
A seconda dei casi, per esempio in presenza di un modulo per inoltrare file, si possono utilizzare anche inviare o caricare. es.

Permettimi una piccola libertà. Per questo ti voto alle prossime elezioni mondiali. Purtroppo in ambito tecnico questo false-friend sta diventando un'ossesione. Sento tante persone che "sottomettono" oggetti senza volontà.

**Comment by eliogi** [comment]
Finita revisione capitolo 1, mi sembra ben fatto. Non aggiungerei per ora niente altro, se mi vengono altre cose in mente aggiungo.

**Comment by gialloporpora** [comment]
Per la questione tastiera, io farei un appendice con i vari codici per alcuni caratteri speciali, tipo “” “” …, ecc., magari mettendo anche la relativa entity HTML.

Per me un false friend che sbagliano in molti, l'ho visto usare male anche sugli articoli del sito open chapter

**Comment by eliogi** [comment]
@gialloporpora già, la triste e lenta morte della lingua italiana. 
Ad ogni modo, mi piace l'idea dell'appendice apposita. 
"Codici Tastiera"

**Comment by gialloporpora** [comment]
Per quanto riguarda i caratteri: io sarei per inserire un'appendice con le varie combinazioni e entity HTML per i caratteri più usati “”, …, ecc.
Per un false friend che sbagliano in molti (io l'ho visto anche su articoli di testate online come Repubblica e il portale Treccani o sbagliato nei GR sui canali Rai) è il billion che diventa bilione.

È perché nessuno ci fa mai caso, ma, anche in TV, quando danno le cifre investite dagli USa molte volte sono inverosimili, perché il bilione in Italia esiste e però è molto più di un miliardo (nel glossario mi sembrava di aver aggiunto i vari traducenti perché è facile fare confusione).

[1]: https://it.wikipedia.org/wiki/Scala_lunga_e_scala_corta

**Comment by gialloporpora** [comment]
@eliogi,
è perché la gente non ha molta dimestichezza coi numeri grandi e non se 
ne rende conto, effettivamente può essere complicato anche perché c'è 
differenza tra inglese e inglese americano (che è quello con cui di 
solito abbiamo a che fare noi).
A me dà pure fastidio che, in TV, usino il punto per i decimali delle 
magnitudo, anche io ho il brutto vizio di usare il punto per i decimali, 
però se si fa divulgazione al grande pubblico bisognerebbe essere più 
corretti.
Tornando ai falsi amici, un altro termine complicato a volte da rendere 
è *narrative* che sbagliando si tende a tradurre con *narrativa* (il 
genere letterale).
[Qui](http://blog.terminologiaetc.it/2016/11/07/significato-differenza-narrazione-storytelling/) 
è spiegato bene la differenza.
È un ottimo blog che sto seguendo da un anno per cercare di tradurre 
meglio, tra le altre cose ha [questa 
pagina](http://blog.terminologiaetc.it/2012/08/16/falsi-amici-inglese-italiano/) 
dove vengono raccolti i vari *falsi amici* trattati.

**Comment by kitsunenosaraT** [comment]
Grazie per tutte le idee, ragazzi, ho messo un 👍 dove c'è qualcosa da incorporare nella guida al prossimo merge.

>Per evidenziare la punteggiatura sono stati usati degli asterischi, è voluto?
`Es: **.**`
Intendevo mettere la punteggiatura in grassetto. Sull'anteprima del markdown in Atom (l’editor che uso e che dovrebbe essere super-integrato con GitHub) funzionava, ma qui sembra che non funzioni solo con la punteggiatura.

Tra l'altro potrebbe essere un bel problema, visto che mi serve per sottolineare la parte rilevante dell'esempio. Qualcuno conosce un modo per risolvere? 😕

**Comment by kitsunenosaraT** [comment]
>La parola "internet" con tutte le lettere minuscole rappresenta tutte le reti, di piccole o grandi dimensioni, che utilizzano lo stesso protocollo di comunicazione. Ogni internet (lettere minuscole) non necessariamente dev'essere connessa a Internet (lettera maiuscola iniziale) e non necessariamente devono utilizzare tcp/ip come loro protocollo di base.

Scusa se faccio confusione, questo è un campo in cui non sono molto ferrata, queste reti di cui parli (che, se ho capito bene, sono le piccole reti casalinghe o aziendali), non si chiamano *intranet*, mentre internet è inteso come la grande rete che connette tutto?

**Comment by kitsunenosaraT** [comment]
> Per la questione tastiera, io farei un appendice con i vari codici per alcuni caratteri speciali, tipo “” “” …, ecc., magari mettendo anche la relativa entity HTML.
Assolutamente, ci conto! Anzi, visto che siamo utenti diversi con sistemi operativi diversi, direi di approfittarne per dare le istruzioni in Windows MacOs e Ubuntu. Se vedete un comando o una scorciatoia da tastiera nella guida, verificate che corrispondano al vostro sistema.

Importante anche l'idea di Elio di far presente le differenze di layout delle varie tastiere.

**Comment by kitsunenosaraT** [comment]
> http://blog.terminologiaetc.it/2012/08/16/falsi-amici-inglese-italiano/
Bellissimo sito, grazie per averlo condiviso con noi! 😀

**Comment by eliogi** [comment]
Ciao @kitsunenosaraT , riassumo qui le mie risposte.

> Tra l'altro potrebbe essere un bel problema, visto che mi serve per sottolineare la parte rilevante dell'esempio. Qualcuno conosce un modo per risolvere? 😕

Se ho capito bene succede solo quando inserisci quel codice nei commenti. 

Ho fatto una prova estemporanea, e sembra funzionare, forse bisogna guardare bene dove sono i commenti...

ESEMPIO:
Senza commento: **.**
> Commento: **.**

> Scusa se faccio confusione, questo è un campo in cui non sono molto ferrata, queste reti di cui parli (che, se ho capito bene, sono le piccole reti casalinghe o aziendali), non si chiamano intranet, mentre internet è inteso come la grande rete che connette tutto?

E' una questione puramente di "ideologia". Prima che nascesse Internet, così come lo conosciamo, i computer potevano creare delle reti con stesso "protocollo", la differenza è sottile, ma non necessariamente erano delle "intranet". Intranet presume che stia nella stessa sottorete, mentre internet (con i minuscola) si basa sullo stesso protocollo. Arpanet era "internet". Comunque, forse questo discorso lasciamolo cadere, è troppo etico e poco pratico. Ok per tutti? Lasciamo le cose come stanno...

PS: noticina in merito ai commento su github: quando fate una "citazione", ricordate di premere invio e lasciare uno spazio vuoto, altrimenti il vostro testo appare come "citazione" e non come risposta.

Grazie a tutti.

**Comment by kitsunenosaraT** [comment]
>Se ho capito bene succede solo quando inserisci quel codice nei commenti.
Ho fatto una prova estemporanea, e sembra funzionare, forse bisogna guardare bene dove sono i commenti...

Temo di  aver capito… Tu lasci uno spazio prima del `**.` Io non lo ho fatto, perché secondo le regole tipografiche non ci vanno spazi prima di un segno di interpunzione. Per esempio io scrivo:
`Errore 404: pagina non trovata**.**` invece di `Errore 404: pagina non trovata **.**`
Però senza uno spazio davanti il `**` non viene riconosciuto come tag di formattazione. :thinking: Non so se vale la pena commettere l’errore tipografico di lasciare uno spazio prima solo per evidenziare un carattere… Che ne pensi, @gialloporpora ?

>Intranet presume che stia nella stessa sottorete, mentre internet (con i minuscola) si basa sullo stesso protocollo. Arpanet era "internet". Comunque, forse questo discorso lasciamolo cadere, è troppo etico e poco pratico. Ok per tutti? Lasciamo le cose come stanno...

Grazie, ora mi sembra di aver capito meglio la differenza 😀 
E non sono d’accordo di lasciar perdere, l’appunto che hai fatto riguarda le storia del Web e dovrebbe interessare tutti gli addetti ai lavori. Se siete d’accordo, lo metterei in una noticina a margine, in modo da 
non confondere le idee.

>PS: noticina in merito ai commento su github: quando fate una "citazione", ricordate di premere invio e lasciare uno spazio vuoto, altrimenti il vostro testo appare come "citazione" e non come risposta.

Hai ragione… A volte me ne dimentico 😓 Non mi sono ancora abituata a tutti questi a capo del markdown

**Comment by eliogi** [comment]
> Però senza uno spazio davanti il ** non viene riconosciuto come tag di formattazione. 🤔 Non so se vale la pena commettere l’errore tipografico di lasciare uno spazio prima solo per evidenziare un carattere… Che ne pensi, @gialloporpora ?

Intanto vi dico la mia, secondo me in questo caso vale la pena. Quegli asterischi rischiano di confondere. Oppure troviamo una notazione per far capire che è un riportare il punto.

Per la questione Internet e internet, cerchiamo magari anche qualche fonte più attendibile dei miei ricordi di infanzia :)

**Comment by gialloporpora** [comment]
Scusate il ritardo,
io quando avevo letto il documento in locale questo problema non lo 
avevo notato, difatti anche rileggendolo ora la preview a me apare 
correttamente.
Questo a me sembra un problema del convertitore di markdown di GitHub.

Forse provando a cambiare:


> >Se Marco si lascerà scappare il nostro segreto**, e sono sicuro che 
> prima o poi lo farà,** finiremo tutti nei guai fino al collo.


con




> >Se Marco si lascerà scappare il nostro segreto, **e sono sicuro che 
> prima o poi lo farà**, finiremo tutti nei guai fino al collo.


potrebbe andare?


Più che la preview qui comunque,  credo che è importante vedere come lo 
strumento che da markdown va a generare la guida in formato HTML/PDF/epub.

**Comment by gialloporpora** [comment]
Sì, anche io rinuncerei a evidenziarlo.
Credo sia una particolarità del markdown di GitHub quella di non leggere 
gli asterischi (o altri codici) se “all'interno di parole”, per dire  
l'interprete Markdown che uso io funziona diversamente (e da quel che mi 
pare di capire anche quello della preview di Atom.js).

Purtroppo il markdown non ha  uno standard ben preciso e ci sono un 
sacco di libere interpretazioni su alcuni aspetti.

**Comment by kitsunenosaraT** [comment]
>Più che la preview qui comunque, credo che è importante vedere come lo strumento che da markdown va a generare la guida in formato HTML/PDF/epub.

Non sono ancora riuscita a inserire i capitoli su GitBook (a proposito, mi sa che dovrò ancora cambiare le cartelle… 😅 stavolta aspetto che @gialloporpora carichi il suo capitolo così non si creano conflitti), comunque il testo dovrebbe apparire esattamente come appare su GitHub, ovvero male.

Direi che possiamo fare una prova su GitBook e se viene reso con gli asterischi anche lì, piuttosto li omettiamo.

**Comment by gialloporpora** [comment]
Se vuoi carica pure e cambia l'albero delle cartelle, ho capito come 
aggiornare tutto senza problemi.
Se ho capito bene, questo influenza anche i link  agli altri capitoli 
nel file, quindi se vuoi cambiarla puoi farlo già subito così controllo 
di non sbagliare i link.

**Comment by kitsunenosaraT** [comment]
Hai ragione, siccome bisogna riaggiornare tutti i link, è meglio che lo faccia ora che ci sono pochi collegamenti…
Allora procedo, grazie!

**Comment by kitsunenosaraT** [comment]
Mentre risistemavo i link ai capitoli, ho pensato di raccogliere nel primo post una check-list dei suggerimenti da incorporare nella seconda bozza. Così per chi aggiorna il capitolo è più facile evitare di perdere pezzi per strada, inoltre si vede meglio chi ha contribuito con cosa.

**Comment by gialloporpora** [comment]
Ottima idea.
Ora aggiorno anche io la mia copia locale.

**Comment by Mte90** [comment]
Mi sembra ottima, io continuo a ricordare la d eufonica che mettevo ovunque nei testi italiani ed il concetto di fare clic e non cliccare ma questa pagina non li cita.

**Comment by kitsunenosaraT** [comment]
Giustissimo, metto subito nelle cose da aggiornare!

**Comment by gialloporpora** [comment]
Allora, a proposito di *false friend*, visto che l'ho letto ieri l'altro, c'è il **blue** che non è il blu ma l'azzurro, il blu sarebbe il **dark blue** e la *blue whale* che va di moda da noi è balenottera azzurra (non balena blu).
Un altro, visto i meme su Star Wars, è *classified* che anche in TFA hanno tradotto con classificato e secondo me in italiano rende proprio male perché, anche se qualcuno lo usa sui giornali, noi usiamo classificato con altre accezioni, è più un secretato.
Se avete visto TFA, il passaggio in cui BB-8 dice che è classificato e Rey gli risponde “classificato, anche io…” per me in italiano ha poco senso.

**Comment by kitsunenosaraT** [comment]
Sono d'accordissimo su *classified*, che è decisamente *riservato*, *segreto* ecc. In italiano *classificato* significa che è stato inserito in una classe o categoria, tutta un'altra cosa.

Per *blue* invece farei una puntualizzazione. In inglese (come in tantissime altre lingue) non esiste una parola specifica per *azzurro* (almeno, c'è *azure*, ma è una vocabolo molto ricercato). [Blue](https://en.wikipedia.org/wiki/Blue) indica tutta la gamma che va dal blu oltremare al celeste (o sky blue). Semplicemente, al contrario di noi, non sentono il bisogno di puntualizzare tra blu e azzurro in genere. Se proprio devono descriverlo usano light blue, dark blue, cobalt blue ecc. Ma in generale, mentre noi diremmo "il cielo è azzurro, il mare è blu", per loro è "the sky is blue, the sea is blue".

**Comment by gialloporpora** [comment]
Grazie per la spiegazione  sulle sfumature del blu.
Io ricordo il pulsantino di Firefox in Classic Theme Restorer che era definito blue e in italiano era più azzurro che blu.
Ti metto anche il link all'articolo a cui facevo riferimento:
http://blog.terminologiaetc.it/2015/03/02/falsi-amici-colori-blue-blu/

**Comment by kitsunenosaraT** [comment]
Ho letto l'articolo, molto interessante! Però, basandomi anche sulla mia personale esperieza, non sono molto d'accordo con questo passaggio:

> in inglese di solito blue non indica un colore piuttosto scuro, come blu in italiano, ma invece tonalità chiare che noi chiamiamo in tutt’altro modo.

Forse semplicemente non ci ho mai fatto caso io, ma stando alle mie letture, mi sembra che *blue* venga usato interscambiabilmente per il chiaro e per lo scuro,  e che la tonalità (*dark/light*) venga specificata solo se rilevante.

Per esempio, nei pulsanti delle interfacce secondo me la questione è irrilevante. Lo fanno apposta a mettere colori ben distinti tra loro per non confondere l'utente. In questi contesti non troveremo mai un pulsante blu cobalto e un altro blu savoia, ma piuttosto uno di una tonalità qualsiasi di blu, l'altro di una tonalità qualsiasi di rosso.

Per cui nelle istruzioni non viene riportato "Click the light blue button" or "Click the coral red button", ma verranno chiamati semplicemente "the blue button" e "the red button".

Invece se si dovessero descrivere i colori di una stoffa o di un quadro, la tonalità diventa rilevante, e qui abbiamo i vari *pale blue*, *sky blue*, *navy blue* etc.

P.s. Spero che l'articolo abbia torto riguardo alla sparizione della parola *azzurro* in italiano, perché è una parola che mi piace 😓

**Comment by kitsunenosaraT** [comment]
Underpass sul forum ha segnalato il seguente intervento di Lisman per quanto riguarda la formattazione degli elenchi:

>Il Nuovo Manuale di Stile del Lesina che, per quanto riguarda il trattamento delle liste, si limita a presentare due metodi alternativi che chiama rispettivamente stile testo e stile elenco:

>Citazione

>    La scelta fra i due può essere influenzata dal tono generale dell'esposizione; ed eventualmente – ma seguendo criteri di coerenza – entrambi gli stili potrebbero essere usati all'interno dello stesso testo.

>      Stile testo
> Si seguono le regole del testo corrente, in particolare:
> * si usa l'iniziale minuscola se la voce prosegue il periodo della frase introduttiva;
> * ogni voce termina con il segno di punteggiatura che gli spetterebbe nel contesto della frase;
> * l'ultima voce si chiude con il punto.

> Come si può osservare, le precedenti indicazioni sono espresse mediante una lista in "stile testo"



> Stile elenco

> Il testo delle voci di una lista viene trattato come una serie di elementi di informazione distinti dal testo corrente. In questo caso si adottano le seguenti convenzioni:

           

> * Le voci hanno comunque iniziale maiuscola, poiché viste come elementi informativi autonomi.
> * Il testo di ogni voce è chiuso dal punto se costituisce una frase compiuta; non è seguito da punteggiatura in caso contrario (per esempio, se è una semplice denominazione...). In questo secondo caso neppure l'ultima voce della lista è chiusa da un punto.

> Come si può osservare, le precedenti indicazioni sono espresse mediante una lista "stile elenco"...

**Comment by kitsunenosaraT** [comment]
La [seconda versione](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/1-Buone_norme_di_traduzione.md) del capitolo è pronta 🎉 
Nuovi suggerimenti nello issue #91
