### ISSUE TITLE
Translating MDN – [CSS - Building blocks]

### ISSUE THREAD

**Issue by kitsunenosaraT** [MozillaItalia/Mozilla-Italia-l10n-guide#230]
Questo issue è dedicato alla traduzione e revisione di un articolo di [MDN](https://developer.mozilla.org/).

## Informazioni sul progetto
**URL**: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks

**URL traduzione**: https://developer.mozilla.org/it/docs/Learn/CSS/Building_blocks

**Formato di file**: markup wiki (testo con tag)

**Strumenti**: a scelta tra [interfaccia di traduzione MDN](https://developer.mozilla.org/) (online) / editor di testo semplice (offline) / [OmegaT](http://omegat.org/) (offline)

### Prima di iniziare
- Crea un account GitHub (se non lo hai già): ti servirà sia per scrivere in questo issue, sia per accedere a MDN
  - (Facoltativo) Installa il componente aggiuntivo [MozIta L10n Addons](https://addons.mozilla.org/it/firefox/addon/mozita-l10n-addons/) per accedere più facilmente ai caratteri speciali come `’ “ ” È` ecc.
- Leggi "[Come tradurre le pagine di MDN](https://developer.mozilla.org/it/docs/MDN/Contribute/Localize/Translating_pages)"

- Leggi i capitoli della guida. Se lo desideri, lascia un feedback nel relativo issue:
  - Capitolo 1 – [Buone norme di traduzione tecnica](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/1-Buone_norme_di_traduzione.md) Feedback: issue #225 
  - Capitolo 2 – [Linee guida di Mozilla Italia](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/2-Linee_guida_di_Mozilla_Italia.md) Feedback: issue #138
  - Capitolo 3 – [Flusso di lavoro](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/3-Flusso_di_lavoro.md) Feedback: issue #24 
  - Capitolo 4 – [Tipi di file](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/4-Tipi_di_file.md) Feedback: issue #31 
  - Capitolo 5  – [Risorse esterne](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/5-Risorse_esterne.md) Feedback: issue #36 

#### Prendere in carico il progetto
* Scrivi nello issue #217 l'URL dell'articolo che vuoi tradurre. Verrà aperto uno issue dedicato.
* Accedi a [MDN](https://developer.mozilla.org/) con il tuo account GitHub
* Attieniti alle [istruzioni per MDN del capitolo 3](https://github.com/kitsunenosaraT/Mozilla-Italia-l10n-guide/blob/master/it/3-Flusso_di_lavoro.md#mdn) e ai suggerimenti del resto della guida, in particolare [i consigli pratici del capitolo 2](https://github.com/kitsunenosaraT/Mozilla-Italia-l10n-guide/blob/master/it/2-Linee_guida_di_Mozilla_Italia.md#consigli-pratici)
* Quando hai terminato, aggiungi a questo issue il [label](https://help.github.com/en/github/managing-your-work-on-github/about-labels) `richiesta revisione tecnica` e **avvisa con un messaggio nella sezione commenti**.
  * Se sei il revisore tecnico, quando hai terminato, elimina il *label* `richiesta revisione tecnica` e applica quello `richiesta revisione stilistica`.
  * Se sei il revisore stilistico, quando hai terminato, elimina il label `richiesta revisione stilistica`.
* Per qualsiasi problema o domanda scrivi pure in questo issue
* …e buona traduzione! 🎊 

## Link Utili
* Motori di ricerca per la terminologia
  - [Pontoon: tutti i progetti](https://pontoon.mozilla.org/it/all-projects/all-resources/?utm_source=pontoon-addon&string=66616) -- Per gli elementi UI, le funzioni e altra terminologia dei prodotti Mozilla.
  - [Transvision](https://transvision.mozfr.org/) -- Motore di ricerca esterno per i software e i siti  Mozilla, complementare a Pontoon.
  - [Microsoft Language Portal](https://www.microsoft.com/en-us/language/Search?langID=408&Source=true&productid=0) -- Per gli elementi UI, le funzioni e altra terminologia dei prodotti Microsoft.

❗️ **N.B.** Per segnalare la traduzione di un nuovo articolo utilizzare lo issue indice #217.

**Comment by xplosionmind** [comment]
Ciao, ho due dubbi di traduzione:

## Come si traduce "cascade"?

Secondo me è giusto lasciarlo invariato, ma devo o non devo mettere le virgolette?

#### esempio

originale:
> This module looks at the cascade and inheritance, all the selector types we have available, units, sizing, styling backgrounds and borders, debugging, and lots more.

mia traduzione:
> In questo modulo verranno trattati: “cascade” e ereditarietà, tutti i tipi di selettori disponibili, unità di misura, dimensioni, stilizzazione di sfondi e contorni, debugging e molto altro

---

## “L’HTML” o ”HTML”, “CSS” o “Il CSS”?

Un dettaglio che non ho trovato nelle Linee Guida, ma che forse sarebbe molto utile inserire, è se, quando e come usare gli articoli per definire i linguaggi di programmazione.

#### esempi

originale:
> 3. Basic familiarity with HTML, as discussed in the Introduction to HTML module.
> 4. An understanding of the basics of CSS, as discussed in the CSS first steps module.

mia traduzione:
> 3. Una minima familiarità con l’HTML, come trattato nel modulo Introdzione all’HTML.
> 4. Comprenzione delle basi del CSS come trattato nel modulo Primi passi con CSS.

- dovrei tradurre con “familiarità con HTML”, “introduzione a HTML”?
- “Introduzione all’HTML”, “Introduzione a HTML” o “Introduzione su HTML”?
- meglio “Comprensione delle basi del CSS”, “Comprensione delle basi di CSS” o “Comprensione delle basi CSS”?

---

Tutte le quotes e gli esempi sono tratti dall'[articolo dello issue](https://wiki.developer.mozilla.org/it/docs/Learn/CSS/Building_blocks)

**Comment by Sav22999** [comment]
@xplosionmind per "cascade" io l'ho sempre trovato (in italiano) come "a cascata".

Per "HTML" e "CSS":
3. Anche io tradurrei in questo modo
4. Il secondo "CSS" credo vada meglio con "[...] passi con il CSS."

L'articolo sottintende "linguaggio" -> Il (linguaggio) HTML -> Il HTML suona male, quindi si predilige "Lo HTML"->"l'HTML". Stessa cosa per CSS -> il (linguaggio) CSS -> il CSS.

- Assolutamente no: Introduzione su HTML (la domanda è "Introduzione a che cosa?") -> (io sceglierei) "Introduzione all'HTML"
- Comprensione della basi del CSS -> Primi passi con il CSS (puoi usare anche "col" se ti piace la prep.artic.)

**Comment by xplosionmind** [comment]
Grazie Saverio! Ho seguito i tuoi consigli: l'articolo è pronto per la revisione tecnica.

**Comment by kitsunenosaraT** [comment]
@Mte90 Se hai tempo, vorresti occuparti anche di questa revisione tecnica?

**Comment by Mte90** [comment]
`la costruzione del CSS` del titolo della pagina dovrebbe avere la prima lettera in maiuscolo.
`Inquesta lezione accenneremo` manca uno spazio tra le due parole.
Per il resto a livello tecnico i termini sono stati gestiti correttamente per me.

**Comment by kitsunenosaraT** [comment]
Grazie @Mte90 Allora si può procedere con la revisione stilistica.

**Comment by Sav22999** [comment]
Scusate, segnalo alcuni typo:
- ![immagine](https://user-images.githubusercontent.com/32335378/80351979-7b54e800-8873-11ea-80b6-0b4a05a95cf7.png)
- ![immagine](https://user-images.githubusercontent.com/32335378/80351907-60827380-8873-11ea-9d56-293491445734.png)
- [...] dopo aver acquisito l<s>'essenziale</s><b>a minima</b> esperienza di [...]
- [...] e<b>d</b> ereditarietà [...]
- ![immagine](https://user-images.githubusercontent.com/32335378/80352318-ffa76b00-8873-11ea-9eb5-9dd1a489b7a6.png) ("ComprenZione"->"Comprensione"), anche se personalmente non mi piace molto come termine. Proporrei qualcosa tipo "Capacità"/"Dimestichezza"/...

**Comment by xplosionmind** [comment]
grazie mille @Sav22999 e @Mte90.

Ho provveduto a correggere gli errori da voi segnalati. Alcune domande per @Sav22999:

- per quanto riguarda “comprensione”, io terrei questo termine, perché è ancora uno step sotto rispetto a “capacità”/“dimestichezza” che tu hai proposto. È il più preciso a mio parare.
- non capisco la correzione del punto `3.`, non capisco cosa dovrei correggere... forse “...nel modulo **di** introduzione all’HTML”?

**Comment by Sav22999** [comment]
@xplosionmind 
- se preferisci "comprensione" va bene, il mio era un suggerimento niente di più 😄
- c'è un typo "Introdzione", manca una "u"

**Comment by xplosionmind** [comment]
>     * c'è un typo "Introdzione", manca una "u"

cavolo, sono cieco. Grazie! Articolo pronto per revisione stilistica!

**Comment by kitsunenosaraT** [comment]
Ricevuto! 😎

**Comment by kitsunenosaraT** [comment]
Eccomi qui. 
Bravi tutti, complimenti 😁 
Qui c'è il [diff che evidenzia le modifiche](https://wiki.developer.mozilla.org/it/docs/Learn/CSS/Building_blocks$compare?locale=it&to=1621267&from=1621197).


Alcune note:

- meglio sostituire i trattini degli incisi con la punteggiatura nostrana (come anche raccomandato nella [guida](https://mozillaitalia.gitbooks.io/l10n-guide/it/1-Buone_norme_di_traduzione.html#trattini) )
> Primi passi con il CSS</a> — dopo
> Primi passi con il CSS</a>: dopo

- apostrofo dritto/curvo: noi di solito usiamo quello curvo, ma dubito che gli altri collaboratori di MDN facciano lo stesso (dato che è più scomodo da digitare). Comunque l'importante è scegliere un tipo e usare quello coerentemente all'interno dello stesso articolo (io ho uniformato usando quello dritto).

- ho puntato tutto gli URL agli articoli in italiano, dove presenti. So che è un lavoro noioso, ma andrebbe fatto (altrimenti, che senso ha tradurre tutto MDN in italiano, se poi il lettore viene rimandato alla versione inglese?)

- Mi sa che hai saltato tutto il paragrafo "Assesments".

- Rimane in sospeso la questione sollevata da @danielebarell sull'utilizzo dell'articolo singolare o plurale per il CSS.

Quando hai tempo, dimmi se fila liscio, se noti qualcosa che non va o che vorresti cambiare.

**Comment by danielebarell** [comment]
>Rimane in sospeso la questione sollevata da @danielebarell sull'utilizzo dell'articolo singolare o plurale per il CSS.
Ciao
Questione rientrata. Come stabilito da Saverio:
- _il CSS_ singolare come linguaggio di programmazione* 
- _i CSS_ plurale se riferito a più di un file 

* ho controllato anche se sia corretto definirlo "linguaggio di programmazione" ed in effetti lo è.
**CSS is a Declarative, Domain-Specific Programming Language**

**Comment by Sav22999** [comment]
@danielebarell il CSS (come l'HTML) non è un linguaggio di programmazione ... definirlo come tale è parecchio azzardato (e lo so, non lo hai definito tu come "programming language") ... per definizione (brevemente): un linguaggio di programmazione è un linguaggio con sintassi definita in grado di realizzare e applicare algoritmi, il CSS non permette di fare ciò 😄 

in ogni caso, è pur sempre un linguaggio, così come lo è l'HTML, anche se non di programmazione 😆

Per "i CSS" non sono molto d'accordo. Se ci si riferisce a file (sia uno sia tanti), credo sia molto meglio specificare: "I fogli di stile CSS" o "Il/Un foglio di stile CSS" 🤔 cosa ne pensate?

**Comment by danielebarell** [comment]
@Sav22999 
>Per "i CSS" non sono molto d'accordo. Se ci si riferisce a file (sia uno sia tanti), credo sia molto meglio specificare: "I fogli di stile CSS" o "Il/Un foglio di stile CSS" (o per brevità anche "i file CSS"/"il file CSS") 🤔 cosa ne pensate?

Voto "fogli di stile" se ci riferiamo a file `.css` *
anche senza necessità di specificare sempre _CSS_ se nella documentazione dobbiamo ripeterci più volte .
Prima volta "I/l fogli/o di stile CSS"
le volte successive basta "I/l fogli/o di stile"

* Esistono altre estensioni collegate al mondo CSS (i preprocessori): `.sass` `.scss` etc.

**Comment by xplosionmind** [comment]
Ottimo, allora siamo d’accordo. La conclusione è questa:

- “Il CSS”, al singolare, solamente quando si tratta di linguaggio; si può omettere la parola “linguaggio”, che è sottintesa.
- quando si tratta di file, specifichiamo sempre “foglio/i di stile”, ma per comodità possiamo omettere, nelle ripetizioni del termine successive alla prima, “CSS”; altrimenti possiamo scrivere “file CSS”, sia per il plurale che per il singolare.

@Sav22999 puoi segnarti questa conclusione per poterla inserire nelle linee guida per la traduzione MDN di cui hai parlato su Telegram. Grazie @danielebarell per il confronto.

**Comment by xplosionmind** [comment]
>     * Comunque l'importante è scegliere un tipo e usare quello coerentemente all'interno dello stesso articolo (io ho uniformato usando quello dritto).

Bene, direi proprio che da ora in poi userò sempre l'accento dritto, così sono sicuro di non sbagliare.



>     * ho puntato tutto gli URL agli articoli in italiano, dove presenti. So che è un lavoro noioso, ma andrebbe fatto (altrimenti, che senso ha tradurre tutto MDN in italiano, se poi il lettore viene rimandato alla versione inglese?)

Perdonami, io sono sempre in dubbio quando si parla di link e ho tanta paura di combinare pasticci perciò non li ho ancora toccati. Precisamente, come si fa a trasformare un link perché rimandi alla pagina in italiano? Basta aggiungere `[...]/it/[...]` oppure bisogna indicare il titolo dell'articolo in italiano? @Sav22999 questa è una di quelle informazioni che sarebbe **estremamente** utile fornire nelle linee guida di traduzione MDN. In ogni caso, appena capisco bene come fare, convertirò sempre anche i link, perdonatemi.



>     * Mi sa che hai saltato tutto il paragrafo "Assesments".

Sono troppo sbadato, devo rileggere più con calma! Grazie.



>     * Rimane in sospeso la questione sollevata da @danielebarell sull'utilizzo dell'articolo singolare o plurale per il CSS.

Risolta nel commento precedente.

A questo punto, direi che la traduzione è completa e possiamo chiudere lo issue! Grazie mille a tutti.

*La versione definitiva dell'articolo tradotto è [qui](https://developer.mozilla.org/it/docs/Learn/CSS/Building_blocks).*

**Comment by kitsunenosaraT** [comment]
@xplosionmind Grazie!

Per quanto riguarda i link, dovremmo proprio decidere delle linee guida comuni, ma per adesso ti dico come mi regolo io.

Per ogni link:
1. Clicco sul collegamento e vado alla pagina inglese.
2. Dal pulsante Lingue controllo se nel menu a tendina compare "Italiano"
3. Se compare Italiano, lo seleziono e vado alla pagina italiana.
4. Copio l'URL della pagina italiana e lo sostituisco al link inglese nella mia traduzione
   - N.B. In questo caso non basta sempre sostituire `/en/` con `/it/` perché lo slug (cioè la parte finale dell'URL) potrebbe cambiare in italiano.
5. Copio il titolo esatto dell'articolo e lo incollo come testo del link e lo incollo nella mia traduzione (il testo del link deve corrispondere esattamente al titolo della pagina in italiano,non traduco con parole mie).

Es.
No:
`<a href="https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/Installing_basic_software">installazione di software base</a>`

Sì:
`<a href="https://developer.mozilla.org/it/docs/Learn/Getting_started_with_the_web/Installing_basic_software">Installazione di software fondamentali</a>`

Spero che possa esserti d'aiuto.

Grazie ancora per il tuo lavoro 🙇‍♂️
