### ISSUE TITLE
Translating MDN – Using the viewport meta tag to control layout on mobile browsers

### ISSUE THREAD

**Issue by Sav22999** [MozillaItalia/Mozilla-Italia-l10n-guide#234]
Questo issue è dedicato alla traduzione e revisione di un articolo di [MDN](https://developer.mozilla.org/).

## Informazioni sul progetto
**URL**: https://developer.mozilla.org/en-US/docs/Mozilla/Mobile/Viewport_meta_tag

**URL traduzione**:

**Formato di file**: markup wiki (testo con tag)

**Strumenti**: a scelta tra [interfaccia di traduzione MDN](https://developer.mozilla.org/) (online) / editor di testo semplice (offline) / [OmegaT](http://omegat.org/) (offline)

### Prima di iniziare
- Crea un account GitHub (se non lo hai già): ti servirà sia per scrivere in questo issue, sia per accedere a MDN
  - (Facoltativo) Installa il componente aggiuntivo [MozIta L10n Addons](https://addons.mozilla.org/it/firefox/addon/mozita-l10n-addons/) per accedere più facilmente ai caratteri speciali come `’ “ ” È` ecc.
- Leggi "[Come tradurre le pagine di MDN](https://developer.mozilla.org/it/docs/MDN/Contribute/Localize/Translating_pages)"

- Leggi i capitoli della guida. Se lo desideri, lascia un feedback nel relativo issue:
  - Capitolo 1 – [Buone norme di traduzione tecnica](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/1-Buone_norme_di_traduzione.md) Feedback: issue #225 
  - Capitolo 2 – [Linee guida di Mozilla Italia](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/2-Linee_guida_di_Mozilla_Italia.md) Feedback: issue #138
  - Capitolo 3 – [Flusso di lavoro](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/3-Flusso_di_lavoro.md) Feedback: issue #24 
  - Capitolo 4 – [Tipi di file](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/4-Tipi_di_file.md) Feedback: issue #31 
  - Capitolo 5  – [Risorse esterne](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/5-Risorse_esterne.md) Feedback: issue #36 

#### Prendere in carico il progetto
* Scrivi nello issue #217 l'URL dell'articolo che vuoi tradurre. Verrà aperto uno issue dedicato.
* Accedi a [MDN](https://developer.mozilla.org/) con il tuo account GitHub
* Attieniti alle [istruzioni per MDN del capitolo 3](https://github.com/kitsunenosaraT/Mozilla-Italia-l10n-guide/blob/master/it/3-Flusso_di_lavoro.md#mdn) e ai suggerimenti del resto della guida, in particolare [i consigli pratici del capitolo 2](https://github.com/kitsunenosaraT/Mozilla-Italia-l10n-guide/blob/master/it/2-Linee_guida_di_Mozilla_Italia.md#consigli-pratici)
* Quando hai terminato, aggiungi a questo issue il [label](https://help.github.com/en/github/managing-your-work-on-github/about-labels) `richiesta revisione tecnica` e **avvisa con un messaggio nella sezione commenti**.
  * Se sei il revisore tecnico, quando hai terminato, elimina il *label* `richiesta revisione tecnica` e applica quello `richiesta revisione stilistica`.
  * Se sei il revisore stilistico, quando hai terminato, elimina il label `richiesta revisione stilistica`.
* Per qualsiasi problema o domanda scrivi pure in questo issue
* …e buona traduzione! 🎊 

## Link Utili
* Motori di ricerca per la terminologia
  - [Pontoon: tutti i progetti](https://pontoon.mozilla.org/it/all-projects/all-resources/?utm_source=pontoon-addon&string=66616) -- Per gli elementi UI, le funzioni e altra terminologia dei prodotti Mozilla.
  - [Transvision](https://transvision.mozfr.org/) -- Motore di ricerca esterno per i software e i siti  Mozilla, complementare a Pontoon.
  - [Microsoft Language Portal](https://www.microsoft.com/en-us/language/Search?langID=408&Source=true&productid=0) -- Per gli elementi UI, le funzioni e altra terminologia dei prodotti Microsoft.

❗️ **N.B.** Per segnalare la traduzione di un nuovo articolo utilizzare lo issue indice #217.

**Comment by xplosionmind** [comment]
ciao, grazie per aver creato l’issue. Mi sono fermato alla traduzione del primo paragrafo perché nella sezione dei tag ho visto che compare `NeedsUpdate`. Per questo, credo sia il caso di chiudere lo issue e riaprirlo una volta che la pagina originale sia stata aggiornata.

![Screenshot 2020-05-07 at 12 01 05 PM](https://user-images.githubusercontent.com/42862428/81282229-2aa37300-905b-11ea-8359-531a92c54807.jpg)

**Comment by kitsunenosaraT** [comment]
@xplosionmind come preferisci! Chiudiamo fino a prossimo aggiornamento.
