### ISSUE TITLE
Translating MDN – [Normal Flow]

### ISSUE THREAD

**Issue by kitsunenosaraT** [MozillaItalia/Mozilla-Italia-l10n-guide#255]
Questo issue è dedicato alla traduzione e revisione di un articolo di [MDN](https://developer.mozilla.org/).

## Informazioni sul progetto
**URL**: https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Normal_Flow

**URL traduzione**: https://wiki.developer.mozilla.org/it/docs/Learn/CSS/CSS_layout/Normal_Flow

**Formato di file**: markup wiki (testo con tag)

**Strumenti**: a scelta tra [interfaccia di traduzione MDN](https://developer.mozilla.org/) (online) / editor di testo semplice (offline) / [OmegaT](http://omegat.org/) (offline)

### Prima di iniziare
- Crea un account GitHub (se non lo hai già): ti servirà sia per scrivere in questo issue, sia per accedere a MDN
  - (Facoltativo) Installa il componente aggiuntivo [MozIta L10n Addons](https://addons.mozilla.org/it/firefox/addon/mozita-l10n-addons/) per accedere più facilmente ai caratteri speciali come `’ “ ” È` ecc.
- Leggi "[Come tradurre le pagine di MDN](https://developer.mozilla.org/it/docs/MDN/Contribute/Localize/Translating_pages)"

- Leggi i capitoli della guida. Se lo desideri, lascia un feedback nel relativo issue:
  - Capitolo 1 – [Buone norme di traduzione tecnica](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/1-Buone_norme_di_traduzione.md) Feedback: issue #225 
  - Capitolo 2 – [Linee guida di Mozilla Italia](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/2-Linee_guida_di_Mozilla_Italia.md) Feedback: issue #138
  - Capitolo 3 – [Flusso di lavoro](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/3-Flusso_di_lavoro.md) Feedback: issue #24 
  - Capitolo 4 – [Tipi di file](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/4-Tipi_di_file.md) Feedback: issue #31 
  - Capitolo 5  – [Risorse esterne](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/5-Risorse_esterne.md) Feedback: issue #36 

#### Prendere in carico il progetto
* Scrivi nello issue #217 l'URL dell'articolo che vuoi tradurre. Verrà aperto uno issue dedicato.
* Accedi a [MDN](https://developer.mozilla.org/) con il tuo account GitHub
* Attieniti alle [istruzioni per MDN del capitolo 3](https://github.com/kitsunenosaraT/Mozilla-Italia-l10n-guide/blob/master/it/3-Flusso_di_lavoro.md#mdn) e ai suggerimenti del resto della guida, in particolare [i consigli pratici del capitolo 2](https://github.com/kitsunenosaraT/Mozilla-Italia-l10n-guide/blob/master/it/2-Linee_guida_di_Mozilla_Italia.md#consigli-pratici)
* Quando hai terminato, aggiungi a questo issue il [label](https://help.github.com/en/github/managing-your-work-on-github/about-labels) `richiesta revisione tecnica` e **avvisa con un messaggio nella sezione commenti**.
  * Se sei il revisore tecnico, quando hai terminato, elimina il *label* `richiesta revisione tecnica` e applica quello `richiesta revisione stilistica`.
  * Se sei il revisore stilistico, quando hai terminato, elimina il label `richiesta revisione stilistica`.
* Per qualsiasi problema o domanda scrivi pure in questo issue
* …e buona traduzione! 🎊 

## Link Utili
* Motori di ricerca per la terminologia
  - [Pontoon: tutti i progetti](https://pontoon.mozilla.org/it/all-projects/all-resources/?utm_source=pontoon-addon&string=66616) -- Per gli elementi UI, le funzioni e altra terminologia dei prodotti Mozilla.
  - [Transvision](https://transvision.mozfr.org/) -- Motore di ricerca esterno per i software e i siti  Mozilla, complementare a Pontoon.
  - [Microsoft Language Portal](https://www.microsoft.com/en-us/language/Search?langID=408&Source=true&productid=0) -- Per gli elementi UI, le funzioni e altra terminologia dei prodotti Microsoft.

❗️ **N.B.** Per segnalare la traduzione di un nuovo articolo utilizzare lo issue indice #217.

**Comment by danielebarell** [comment]
Iniziata la traduzione in ritardo rispetto alle mie previsioni.
Mi viene promesso il seppellimento professionale tramite un numero massiccio di progetti, ma poi forse non se ne farà nulla;
devo svuotare l'appartamento di mia suocere e ridipingerne le pareti;
e il computer di mia figlia maturanda si rompe precisamente 3 giorni prima che inizino le lezioni da remoto.
Mah.

A margine, il primo paragrafo di questo articolo, nettamente più breve rispetto al precedente, presenta un espressione su cui ho dei dubbi:
_".... it is worth revisiting some of the things **you will have studied** in previous modules ..."_  

"you will have studied" che razza di tempo e di modo è??

**Comment by danielebarell** [comment]
Son cotto alle 4 di pomeriggio (che fisico!)

Ci siam quasi: 
giovedì riguardo e copio la localizzazione e chiamo le revisioni.

**Comment by danielebarell** [comment]
Ciao,
ho rivisto la traduzione e chiamo  le revisioni.
A livello tecnico non mi pare ci siano problemi, a livello stilistico ho tenuto conto delle osservazioni fatte nel precedente articolo.
Ogni volta che rileggo trovo sempre qualche mancanza o qualcosa che potrebbe essere migliorato. 
Amen.

@Sav22999 
@kitsunenosaraT

**Comment by kitsunenosaraT** [comment]
@danielebarell grazie e mille! 🎉 
Non so quanto ci metterò, comunque come al solito intendo fare la revisione offline sul documento, quindi **se d'ora in avanti cambi qualsiasi cosa nella traduzione, avvisami, così aggiorno la mia copia offline**.

Non so se per la revisione tecnica sia meglio aspettare @Sav22999 o @Mte90 o se invece convenga che inizi io.

**Comment by Mte90** [comment]
Rivisto e mi sembra tutto a posto anche perchè c'è poco testo rispetto agli altri.

**Comment by kitsunenosaraT** [comment]
Grazie @Mte90 che rapidità! 😁 
A questo punto tolgo il tag "Revisione tecnica" e inizio io!

**Comment by danielebarell** [comment]
OT

> Edit: Forse questo diff esterno è più leggibile.

**Diffchecker**
Ciao sto provando il Diffchecker, in se mi sembra una buona app, però mi chiede un pagamento per l'acquisto dopo un periodo di prova di 30 gg. @kitsunenosaraT Tu, Sara, come ti stai regolando? La usi professionalmente? Contiamo di usarla con costanza per le nostre localizzazioni? Giusto per capire prima di prendere in considerazione l'acquisto.

**Comment by danielebarell** [comment]
Ciao Sara,
@kitsunenosaraT 

> Complimenti, il tuo stile si sta evolvendo! 😀

Grazie molte! 
In effetti sto solo cercando di seguire le indicazioni di chi ne sa indubbiamente più di me 💯 

---
Divido il controllo sulla revisione in due parti; a quella odierna sulla prima parte seguirà la seconda entro la fine della settimana prossima.

Iniziamo:

> Questo articolo illustra cos'è il flusso normale

Questo articolo illustra il flusso normale | **OK** |

> leggi Introduz**ii**one a HTML

leggi Introduzione a HTML | typo, **OK** |

> Spiegare come i browser predispongo il layout delle pagine web prima dell'intervento da parte dello sviluppatore.

Comprendere come i browser predispongono il layout delle pagine web prima di intervenire su di esso. | **Contesto** |

Credo occorra specificare che l'intervento sia mediante CSS. Infatti anche l'utente potrebbe intervenire sul layout ridimensionando la finestra del browser e il layout, se responsivo, muterebbe il suo aspetto. Quindi forse andrebbe esplicitato che l'intervento è sulla scrittura del CSS.
Propongo 2 alternative:

[a]
**Comprendere come i browser dispongono implicitamente il layout delle pagine web prima che vengano applicate le regole di stile CSS.**
o forse meglio:
[b]
**Comprendere come i browser dispongono implicitamente il layout delle pagine web _senza_ che vengano applicate le regole di stile CSS.**

> è possibile cambiare il comportamento degli elementi adattando la loro posizione oppure rimuovendoli del tutto.

è possibile cambiare il comportamento degli elementi adattando la loro posizione all'interno del flusso oppure estrapolandoli del tutto da esso. | **OK, ma...** |

Forse c'è una ridondanza alla fine, quindi propongo:

**è possibile cambiare il comportamento degli elementi adattando la loro posizione all'interno del flusso oppure estrapolandoli da esso.**

> La maniera migliore per iniziare a strutturare una pagina web è impostare in maniera chiara e robusta il documento che verrà visualizzato secondo il flusso normale.

La maniera migliore per costruire una pagina web è iniziare impostando una struttura chiara e solida, adatta a essere visualizzata nel flusso normale. | **OK** |

> Inoltre, poiché il flusso normale è stato progettato per rendere leggibile il documento, cominciando a impostare la pagina nel modo che abbiamo detto possiamo effettuare le modifiche in maniera armonica senza forzature.

Inoltre, poiché il flusso normale è stato progettato per rendere leggibile il documento, **se** la pagina possiede già questa struttura possiamo effettuare le modifiche in maniera armonica, senza forzature. | **Contesto** |

Il fatto che la pagina web segua il flusso normale non è un ipotesi, come farebbe forse pensare quel _se_, bensì una certezza.
Propongo:
**Inoltre, poiché il flusso normale è stato progettato per rendere leggibile il documento, possiamo cominciare da questa impostazione per efettuare le modifiche in maniera armonica, senza forzature.**

>[...] vale la pena ripassare alcune nozioni che dovreste aver appreso nei moduli precedenti con un occhio di riguardo al flusso normale del documento.

[...] ripassiamo alcune nozioni apprese nei moduli precedenti sul flusso normale del documento. | Molto più succinta, **OK** |

> il riquadro di un determinato elemento viene disposto

il riquadro di un determinato elemento varia |  **OK** | 

> Invece sia la larghezza che l'altezza degli elementi in linea [<a href="/en-US/docs/Web/HTML/Inline_elements">Inline elements</a>] si basa sulle dimensioni del contenuto di questo elemento.

Invece, nel caso degli elementi in linea [<a href="/en-US/docs/Web/HTML/Inline_elements">Inline elements</a>], sia la larghezza che l'altezza dipendono dal contenuto. | **OK** |

> Non è possibile prestabilire la larghezza o l'altezza degli elementi in linea, perché tali elementi si posizionano come contenuti fluidi all'interno di un elemento blocco.

Non è possibile imporre una larghezza o un'altezza degli elementi in linea, perché essi si posizionano come contenuti fluidi all'interno di un elemento blocco. | **OK** |

> Se vogliamo poter stabilire la larghezza e l’altezza occorre usare <code>display:block</code> (oppure <code>display: inline-block</code>, che presenta caratteristiche di entrambi).

Se vogliamo stabilire le sue dimensioni, occorre usare <code>display:block</code> per fare in modo che assuma le proprietà di un elemento blocco (oppure <code>display: inline-block</code>, che presenta caratteristiche di entrambi i _metodi_). | **OK**, ma... |

ho un dubbio sulla correttazza del termine "_metodi_", e cioè se sia oppurtuno definire tali i valori della regola "<code>display</code>". 
In ambito strettamente codice-tecnico un _metodo_ è una funzione di un oggetto ovvero ciò che un oggetto è in grado di compiere. 
Vado un po' OT per spiegarm. che magari è cosa gradita:

---

<code>
class Localizer{
</code>
<br>
<code>
	name = undefined;
</code>
<br>
<code>
	constructor(nmParam){
</code>
<br>
<code>
		this.name = nmParam;
</code>
<br>
<code>
		}
</code>
<br>
<code>
translate(document){
</code>
<br>
<code>
		[... bla bla bla ...]
</code>
<br>
<code>
		console.log(`${this.name} traduce '${document}'` );
</code>
<br>
<code>
	}
</code>
<br>
<code>
}
</code>
<br>
<br>
<code>
const kit = new Localizer('Sara');
</code>
<br>
<code>
kit.translate('Usare i Tag in MDN'); //risulta: "Sara traduce 'Usare i Tag in MDN'";
</code>
<br>
<br>
_Il membro "translate()" della classe Localizer istanziata nell'oggeto kit è definito **metodo**_

---

Perciò a "metodo" preferirei un altro termine, ad esempio, "modo". 
Quindi verrebbe:
**Se vogliamo stabilire le sue dimensioni, occorre usare <code>display:block</code> per fare in modo che assuma le proprietà di un elemento blocco (oppure <code>display: inline-block</code>, che presenta caratteristiche di entrambi i _modi_).**

Alla prossima settimana,
ciao
dan

**Comment by kitsunenosaraT** [comment]
@danielebarell 



>    Spiegare come i browser predispongo il layout delle pagine web prima dell'intervento da parte dello sviluppatore.

> Comprendere come i browser predispongono il layout delle pagine web prima di intervenire su di esso. | Contesto |

> Credo occorra specificare che l'intervento sia mediante CSS. Infatti anche l'utente potrebbe intervenire sul layout ridimensionando la finestra del browser e il layout, se responsivo, muterebbe il suo aspetto. Quindi forse andrebbe esplicitato che l'intervento è sulla scrittura del CSS.
> Propongo 2 alternative:

> [a]
> Comprendere come i browser dispongono implicitamente il layout delle pagine web prima che vengano applicate le regole di stile CSS.
>o forse meglio:
>[b]
> Comprendere come i browser dispongono implicitamente il layout delle pagine web senza che vengano applicate le regole di stile CSS.



---

> è possibile cambiare il comportamento degli elementi adattando la loro posizione oppure rimuovendoli del tutto.

> è possibile cambiare il comportamento degli elementi adattando la loro posizione all'interno del flusso oppure estrapolandoli del tutto da esso. | OK, ma... |

> Forse c'è una ridondanza alla fine, quindi propongo:

> è possibile cambiare il comportamento degli elementi adattando la loro posizione all'interno del flusso oppure estrapolandoli da esso.

Riguardo diffchecker: secondo me è un'ottima app già nella versione online gratuita.
Personalmente la uso solo in rari casi come questo, perché per lavoro uso altri strumenti

**Comment by kitsunenosaraT** [comment]
@danielebarell 

>    Spiegare come i browser predispongo il layout delle pagine web prima dell'intervento da parte dello sviluppatore.

> Comprendere come i browser predispongono il layout delle pagine web prima di intervenire su di esso. | Contesto |

> Credo occorra specificare che l'intervento sia mediante CSS. Infatti anche l'utente potrebbe intervenire sul layout ridimensionando la finestra del browser e il layout, se responsivo, muterebbe il suo aspetto. Quindi forse andrebbe esplicitato che l'intervento è sulla scrittura del CSS.
> Propongo 2 alternative:

> [a]
> Comprendere come i browser dispongono implicitamente il layout delle pagine web prima che vengano applicate le regole di stile CSS.
>o forse meglio:
>[b]
> Comprendere come i browser dispongono implicitamente il layout delle pagine web senza che vengano applicate le regole di stile CSS.


Hai ragione, utile specificare l'uso del CSS. Però la frase è molto più diretta in inglese di come la metti in italiano:

Lo scopo dell'articolo è che (tu, utente) impari come le cose funziona il flusso normale **prima** di metterti a modificarlo con il CSS.  Il volgere la frase come se le modifiche le facesse qualcun altro mi sembra che confonda solo le idee.

Quindi, controproposta:

>  Comprendere come i browser predispongono il layout delle pagine web prima di intervenire su di esso applicando le regole di stile CSS. 

---

> è possibile cambiare il comportamento degli elementi adattando la loro posizione oppure rimuovendoli del tutto.

> è possibile cambiare il comportamento degli elementi adattando la loro posizione all'interno del flusso oppure estrapolandoli del tutto da esso. | OK, ma... |

> Forse c'è una ridondanza alla fine, quindi propongo:

> è possibile cambiare il comportamento degli elementi adattando la loro posizione all'interno del flusso oppure estrapolandoli da esso.

Hai ragione, approvo.

---

>    Se vogliamo poter stabilire la larghezza e l’altezza occorre usare display:block (oppure display: inline-block, che presenta caratteristiche di entrambi).

> Se vogliamo stabilire le sue dimensioni, occorre usare display:block per fare in modo che assuma le proprietà di un elemento blocco (oppure display: inline-block, che presenta caratteristiche di entrambi i metodi). | OK, ma... |

> ho un dubbio sulla correttazza del termine "metodi", e cioè se sia oppurtuno definire tali i valori della regola "display".
In ambito strettamente codice-tecnico un metodo è una funzione di un oggetto ovvero ciò che un oggetto è in grado di compiere.

[…]

> Se vogliamo stabilire le sue dimensioni, occorre usare display:block per fare in modo che assuma le proprietà di un elemento blocco (oppure display: inline-block, che presenta caratteristiche di entrambi i modi).

Grazie, ora capisco che "metodo" si riferisce a un concetto più specifico. In realtà questi concetti sono il mio punto debole, quindi sono contenta di avere qualcuno che tiene d'occhio i miei sinonimi per evitare errori.
Tuttavi, "modi" mi suona davvero troppo generico. C'è un modo per definire `display:block` e `display:inline-block` ? Magari "stili"?

---

Riguardo diffchecker: secondo me è un'ottima app già nella versione online gratuita.
Personalmente la uso solo in rari casi come questo, perché per lavoro utilizzo strumenti specializzati del mio settore.
Per il poco che lo usiamo noi volontari, la versione online gratuita è più che sufficiente.

Se a te serve per motivi tuoi e preferisci la versione desktop (magari per questioni di privacy) è un conto, ma non sentirti assolutamente obbligato a sborsare un centesimo per il volontariato a Mozilla. Metti già a disposizione il tuo tempo gratuitamente, ci manca che ti chiediamo di comprare software!

**Comment by danielebarell** [comment]
Ciao Sara, @kitsunenosaraT 
Riprendo le tue osservazioni sulla prima parte diffchecker:

> Lo scopo dell'articolo è che (tu, utente) impari come le cose funziona il flusso normale prima di metterti a modificarlo con il CSS. Il volgere la frase come se le modifiche le facesse qualcun altro mi sembra che confonda solo le idee.

Nel precedente intervento consideravo che vi sono due tipi di persone, chamiamoli 'attori', che possono modificare il layout di una pagina:
 -1- "lo sviluppare", ovvero la persona scrive il codice CSS.
 -2- "l'utente", quello che visualizza la pagina e intergisce con essa.
Ambedue sono potenzialmente in grado di modificare il layout; il primo sovrascrivendo con regole CSS esplicite il flusso normale della pagina, il secondo ridimensionando la larghezza della pagina tramite browser (se non è su mobile) oppure intervenendo nelle impostazioni base del browser, ad esempio aumentando la dimensione di default del carattere.
Tuttavia l'articolo è rivolto solamente a chi scrive codice cioè al primo dei due attori (che tu chiami "utente", nel senso di utente dell'articolo, e  che io invece chiamo "sviluppatore"), quindi alla fine, come dici tu, dirimere la questione fa confusione oltre a perdere aderenza con la frase originale.  
Perciò la tua controproposta:
**Comprendere come i browser predispongono il layout delle pagine web prima di intervenire su di esso applicando le regole di stile CSS.**
per me è approvata 👍 

**è possibile cambiare il comportamento degli elementi adattando la loro posizione all'interno del flusso oppure estrapolandoli da esso.**
Confermata.

> Grazie, ora capisco che "metodo" si riferisce a un concetto più specifico. In realtà questi concetti sono il mio punto debole, quindi sono contenta di avere qualcuno che tiene d'occhio i miei sinonimi per evitare errori.

Ci mancherebbe. D'altra parte a me fa piacere provare a spiegarli. 👍 

Tornando alla traduzione, con "stili" verebbe:
**Se vogliamo stabilire le sue dimensioni, occorre usare <code>display:block</code> per fare in modo che assuma le proprietà di un elemento blocco (oppure <code>display: inline-block</code>, che presenta caratteristiche di entrambi _gli stili_).**
E a me va benissimo. :)

> Riguardo diffchecker: secondo me è un'ottima app già nella versione online gratuita.
Personalmente la uso solo in rari casi come questo, perché per lavoro utilizzo strumenti specializzati del mio settore.
Per il poco che lo usiamo noi volontari, la versione online gratuita è più che sufficiente.

Allora vada per la versione gratuita, avevo capito che gratis durava comunque al massimo 30 gg 🥇

**Comment by danielebarell** [comment]
**seconda parte dell'accettezione** 
@kitsunenosaraT 

> Il layout che segue il flusso normale, lo abbiamo detto nell'introduzione al layout CSS, consiste nel sistema secondo cui gli elementi vengono posizionati all'interno dell'area di visualizzazione del browser.

Il layout del flusso normale, lo abbiamo detto nell'introduzione al layout CSS, è il sistema impiegato dai browser per disporre gli elementi all'interno dell'area di visualizzazione. | **OK, fila meglio** |


** Come da impostazione predefinita, gli elementi di tipo blocco si dispongono secondo la <em>direzione blocco</em>, determinata dalla proprietà <a href="/en-US/docs/Web/CSS/writing-mode">writing-mode</a> dell'elemento padre (che assume valore <em>iniziale</em> horizontal-tb). ** | **OK, devo stare attento alla formattazione** |

Qua riprendo la tua domanda:
> Scusa se ti chiedo una cosa ovvia, ma da totale ignorante mi chiedo se "initial: horizontal-tb" non sia un nome di proprietà da lasciare in inglese, stile "display:block".
**"intial", tra l'altro è marcato con un tag < em >. Non potrebbe essere un errore, ovvero il tag avrebbe dovuto essere < code >?

Non è ovvio.
Però dovrebbe essere giusto così com'è in originale sebbene l'espressione _initial: horizontal-tb_ induca a pensare l'incontrario, proprio come tu rilevi.
_horizonatal-tb_ è uno dei valori della proprietà _writing-mode_ e non di _initial_ che di per se, come proprietà, non esiste.
link: https://developer.mozilla.org/en-US/docs/Web/CSS/writing-mode
Dunque perchè l'autrice ha messo _initial_? 
Perchè nei CSS _initial_  segnala esplicitamente alla regola di assumere ciò che noi chiameremmo _valore, o stato, di default_. 
-- OT --
Talvolta a livello di codice è importante esplicitare _initial_ perchè altrimenti per il meccanismo della cascata (la C ovvero il _cascading_ dello _style sheet_) l'elemento potrebbe ereditare il valore assegnato ai suoi contenitori.   
Scrivere
<code>
writing-mode: horizontal-tb
</code>
è lo stesso che scrivere
<code>
writing-mode: initial
</code>
-- fine OT --

> Ciascuno di questi elementi occupa un intero spazio orizzontale, una linea via l'altra; inoltre possono essere separati da un margine posto tra di essi.

Ciascun elemento occupa un'intera linea; inoltre è possibile inserire margini per separare i vari elementi. | Più concisa, **OK** |

> Seguendo l'impostazione di lingue come l'inglese, cioè la lettura da sinistra verso destra e dall’alto in basso, gli elementi blocco vengono disposti verticalmente dall'alto in basso secondo l’ordine di scrittura preimpostato.

Nel caso di lingue come l'inglese, con la direzione di scrittura preimpostata da sinistra verso destra e dall’alto verso il basso, gli elementi blocco vengono disposti verticalmente dall'alto in basso.  | **Più filante, OK** |

> bensì si susseguono lungo la medesima linea uno dopo l'altro oppure di seguito a un contenuto testuale adiacente

bensì si susseguono lungo la medesima linea e si allineano ai contenuti testuali adiacenti | **OK** |

> il nome di annullamento del margine ("margin collapsing").

prende il nome di "margin collapsing" (compressione dei margini). | **OK** |

> Il banale esempio [..]

Il basilare esempio [...] | **OK** |

> Di base sono un elemento blocco.

Sono un tipico elemento blocco. | **OK** |

> mentre l'altezza è determinata dal contenuto al nostro interno.

(_al **nostro** interno_ si intende nel nostro stomaco subito dopo la pausa pranzo    📟 👎 )

mentre l'altezza di ciascuno è determinata dal suo contenuto. | **OK** |

> La nostra larghezza e altezza è uguale al nostro contenuto + margine interno + il bordo della larghezza e dell'altezza.

Le nostre larghezza e altezza totali sono uguali a contenuto + margine interno + altezza/larghezza del bordo. | **OK**, ma... |
richiedo chiarimento della lingua italiana: dire "La nostra larghezza e altezza", aggettivo singolare applicato a una pluralità di nomi al singolare, in italiano, è sbagliato?


> Siamo separati  dei margini. A causa del "margin collapse", Veniamo separati dalla larghezza di uno solo dei nostri margini, il maggiore, mentre il minore di annulla.

Siamo separati dai margini. A causa del "margin collapse", tra uno e l'altro di noi rimane un solo margine, il maggiore, mentre il minore si comprime. | **OK** |


> Inoltre ti era sfuggita una frase sorgente, quindi l'ho tradotta e ho cancellato dello strano codice di formattazione che riguardava un cambio di font 🤔

È questo a cui ti riferisci, Sara? 
_&lt;p&gt;Gli elementi in linea come &lt;span&gt;questo&lt;/span&gt; e &lt;span&gt;quest'altro&lt;/span&gt; si collocano entrambi sulla stessa linea e, spazio permettendo, sulla stessa linea dei nodi di testo adiacenti._

Il paragrafo originale è:

> &lt;p&gt;inline elements &lt;span&gt;like this one&lt;/span&gt; and &lt;span&gt;this one&lt;/span&gt; sit on the same line as one another, and adjacent text nodes, if there is space on the same line.

Se per _strana formattazione_ ti riferisci agli &lt;span&gt; è vero, son strani perchè non mi pare aggiungano nulla.
Direi di eliminarli. Per cui verrebbe:


**Gli elementi in linea come questo e quest'altro si collocano entrambi sulla stessa linea e, spazio permettendo, sulla stessa linea dei nodi di testo adiacenti.**

Mi ho un dubbio: **A cosa precisamente si riferisce l'autrice con _questo e quest'altro_?**

> &lt;p&gt;Gli elementi in linea che eccedono la larghezza dell'elemento padre vengono &lt;span&gt;se possibile incorporati in una nuova linea, proprio come questo testo&lt;/span&gt;, oppure scalano a una linea successiva

&lt;p&gt;Gli elementi in linea che eccedono la larghezza dell'elemento padre, &lt;span&gt;se possibile vanno a capo, continuando su una nuova linea, proprio come questo testo&lt;/span&gt;, altrimenti si spostano direttamente sulla linea successiva, |  **OK**, ma… |
Anche qui c'é un rimasuglio di formattazione inutile, per cui direi:

**Gli elementi in linea che eccedono la larghezza dell'elemento padre, se possibile vanno a capo, continuando su una nuova linea, proprio come questo testo, altrimenti si spostano direttamente sulla linea successiva,**[...]

> Ora che abbiamo compreso il flusso normale, cioè il meccanismo predefinito che un browser usa per disporre gli elementi nella pagina, possiamo a studiare [...]

Ora che abbiamo compreso il flusso normale, cioè il meccanismo predefinito con cui un browser dispone gli elementi nella pagina, passiamo a studiare [...] | **OK** |

Attendo che tu mi chiarisca quel paio di dubbi che ancora ho.
Poi trasferisco la revisione stilistaca concordata e chiudo l'articolo.

A presto,
dan

**Comment by kitsunenosaraT** [comment]
@danielebarell 

Scusa se ti ho fatto aspettare tanto per la seconda parte. 🙇 

> Allora vada per la versione gratuita, avevo capito che gratis durava comunque al massimo 30 gg 🥇

Capisco la confusione.
Il servizio online è gratis e lo puoi usare tutte le volte che ti pare.
Solo che quando condividi un diff con qualcuno, rimarrà online per massimo 30 giorni, poi giustamente lo rimuovono, visto che te lo ospitano nel loro spazio di archiviazione. (Se hai ancora gli originali, puoi comunque ricreare il diff in qualsiasi momento, quando serve).
L'avviso dei 30 gg. che hai visto si riferiva alla scadenza di questo particolare diff, non alla tua possibilità di usare il servizio in generale.

> Però dovrebbe essere giusto così com'è in originale sebbene l'espressione initial: horizontal-tb induca a pensare l'incontrario, proprio come tu rilevi. […]

Perfetto, allora nessun cambiamento necessario! Grazie per avere fugato i miei dubbi :D

> Le nostre larghezza e altezza totali sono uguali a contenuto + margine interno + altezza/larghezza del bordo. | OK, ma... |
> richiedo chiarimento della lingua italiana: dire "La nostra larghezza e altezza", aggettivo singolare applicato a una pluralità di nomi al singolare, in italiano, è sbagliato?
	
Non è sbagliato, varie fonti autorevoli ammettono entrambe le versioni, concordanza singolare o plurale. Solo che io ho poi aggiunto l'aggettivo "totali" per chiarire il fatto che si intende altezza dell'elemento + i bordi, e ho ritenuto meglio portare tutto al plurale, in quanto "larghezza e altezza totale" sembrava una somma delle due dimensioni, mentre vengono intese separatamente. Però, pensandoci, funziona anche, per ricalcare il tuo modello:
	
> La nostra larghezza e altezza totale è uguale a contenuto + margine interno + altezza/larghezza del bordo.

In qualità di autore della traduzione, scegli la versione che preferisci tu.

> Se per strana formattazione ti riferisci agli <span>
	
No, la strana formattazione a cui mi riferivo è in una parte precedente dell'articolo, in "Prerequisiti". Si tratta di questa:
	
`<span style="font-family:&quot;Calibri&quot;,sans-serif; font-size:11.0pt; line-height:107%">) </span>e nozioni sul funzionamento del CSS<span style="font-family:&quot;Calibri&quot;,sans-serif; font-size:11.0pt; line-height:107%"> </span>`
	
	
> è vero, son strani perchè non mi pare aggiungano nulla.
> Direi di eliminarli. 
> Mi ho un dubbio: A cosa precisamente si riferisce l'autrice con questo e quest'altro?
	
No, quei tag servono! Racchiudono le parole "questo" e "quest'altro" in un box. L'autrice usa le porzioni di testo "questo" / "quest'altro"  come esempio degli elementi in linea nel flusso di testo. La porzione di testo successiva, "se possibile vanno a capo, continuando su una nuova linea, proprio come questo testo", dimostra l'esempio del flusso con l'a capo.
	
Se guardi la pagina dell'articolo, nel box col rendering del codice, è sicuramente più chiaro della mia spiegazione.

**Comment by danielebarell** [comment]
> Scusa se ti ho fatto aspettare tanto per la seconda parte. 🙇

Figurati, ho percepito che sei molto impegnata. :)

Il presente post solo per avvertire che conto di riprendere e terminare la discussione domani, 22/10, e spero di confezionare l'articolo all'inizio di settimana prossima 🔢 
Mi sfugge ancora la collocazione degli < span > e vedrò di controllare meglio.
A presto.

PS: Vorrei anche capire che metodo usare per trorvare emoticon più significativi  (;P

**Comment by danielebarell** [comment]
Ciao Sara @kitsunenosaraT 

> Le nostre larghezza e altezza totali sono uguali a contenuto + margine interno + altezza/larghezza del bordo. 
[...]Non è sbagliato, varie fonti autorevoli ammettono entrambe le versioni, concordanza singolare o plurale. Solo che io ho poi aggiunto l'aggettivo "totali" per chiarire[...]

Bene bene, confermo l'uso dell'aggettivo al plurale, grazie per il chiarimento!
Viene;
**Le nostre larghezza e altezza totali sono uguali a contenuto + margine interno + altezza/larghezza del bordo.**

> `< span style="font-family:&quot;Calibri&quot;,sans-serif; font-size:11.0pt; line-height:107%">) </span>e nozioni sul funzionamento del CSS<span style="font-family:&quot;Calibri&quot;,sans-serif; font-size:11.0pt; line-height:107%" > < /span >`

Ho visto in Prerequisiti. 
Quei tag non formattano alcun contenuto; temo siano ereditati da un copia-incolla dell'editor che uso in locale.  Comunque via, van rimossi.

>No, quei tag servono![...] 

/:0 Verissimo! Ho perso il contesto della traduzione, cioè che eravamo in fase di coding :(
Faccio ammenda.

Ok. Sto sfarfallando un po' perchè non riesco a dormire, però direi che ci siamo.
 
Assemblo i correttivi.

**Comment by danielebarell** [comment]
|-- **Check out codice** --|

Tutti gli snippet che si appoggiano a codepen e Jsfiddle sono stati localizzati e sono visibili | **Checked** |

Metti il link corretti agli articoli localizzati quando il modulo è concluso. | **TODO** |

----

|-- **Note per l10n a venire** --|

**To Explain** in Prerequisites | Objective

**Comprendere** (non “spiegare”)

**... in English ...**
Quando l'autrice si riferisce alla lingua inglese (per intendere modalità di lettura occidentale da sinistra a destra) traduci:
"**Nel caso di lingue come l'inglese, con la direzione di scrittura preimpostata da sinistra verso destra e dall’alto verso il basso …**".

**margin collapsing**
È un comportamento tipico, ma non molto conosciuto, dei margini che traduciamo:
 **compressione dei margini** (non annullamento) **o meglio** "margin colpsing/collapse" **non tradotto**.

---
_Vale sempre:_

Tradurre innanzitutto il titolo nel campo Traduzione per corretta creazione dello slug.
**Il nome della pagina dello slug però rimane quello originale** 

**Usa la punteggiatura.**

**Struttura il periodo con principali e subordinate** anziché appiattirlo con coordinate. Tendenza:L’inglese è paratattico, l’italiano è ipotattico.

**Coerenza terminologica** prima, gradevolezza e stile eventualmente dopo.

Traduci **default** come **predefinito** || **predefinita** e non altro (es. preimpostato || preimpostata ).

Traduci **parent** come **padre** || **madre** e non altro.

Traduci **child** (items, elements ecc.) come [componenti] **figlio** e non figli. Sta per componenti [di tipo] figlio.

Taduci "... esempio **di seguito**" e non altro. (es. di sotto)

---

Chiudo l'issue #255.

I prossimi due articoli (Flexbox e Grid) **sono i più importanti dell'intero modulo** CSS Layout perchè sono le metodologie utilizzate in questi e nei prossimi anni, perciò occorrerà particolare attenzione.

Mi prendo una settimana e _spero_ di iniziare col prossimo articolo entro **i primi di Novembre**.

Daniele @Mte90
Sara @kitsunenosaraT

vi ringrazio,
a presto ;)
dan

**Comment by kitsunenosaraT** [comment]
@danielebarell Grazie come al solito per il lavoro minuziosissimo! 🙏 
Ho guardato l'articolo terminato su MDN e mi sembra perfetto. Solo una cosa: possiamo rimuovere la spunta a "traduzione in corso"?

**Comment by kitsunenosaraT** [comment]
@danielebarell Ho visto che hai tolto la spunta "traduzione in corso" su MDN, quindi a questo punto possiamo davvero chiudere lo issue. Grazie per il tuo lavoro!
