### ISSUE TITLE
Translating MDN – How the Web works

### ISSUE THREAD

**Issue by Sav22999** [MozillaItalia/Mozilla-Italia-l10n-guide#261]
Questo issue è dedicato alla traduzione e revisione di un articolo di [MDN](https://developer.mozilla.org/).

## Informazioni sul progetto
**URL**: https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/How_the_Web_works

**URL traduzione**: --non disponibile--

**Formato di file**: markup wiki (testo con tag)

**Strumenti**: a scelta tra [interfaccia di traduzione MDN](https://developer.mozilla.org/) (online) / editor di testo semplice (offline) / [OmegaT](http://omegat.org/) (offline)

### Prima di iniziare
- Crea un account GitHub (se non lo hai già): ti servirà sia per scrivere in questo issue, sia per accedere a MDN
  - (Facoltativo) Installa il componente aggiuntivo [MozIta L10n Addons](https://addons.mozilla.org/it/firefox/addon/mozita-l10n-addons/) per accedere più facilmente ai caratteri speciali come `’ “ ” È` ecc.
- Leggi "[Come tradurre le pagine di MDN](https://developer.mozilla.org/it/docs/MDN/Contribute/Localize/Translating_pages)"

- Leggi i capitoli della guida. Se lo desideri, lascia un feedback nel relativo issue:
  - Capitolo 1 – [Buone norme di traduzione tecnica](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/1-Buone_norme_di_traduzione.md) Feedback: issue #225 
  - Capitolo 2 – [Linee guida di Mozilla Italia](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/2-Linee_guida_di_Mozilla_Italia.md) Feedback: issue #138
  - Capitolo 3 – [Flusso di lavoro](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/3-Flusso_di_lavoro.md) Feedback: issue #24 
  - Capitolo 4 – [Tipi di file](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/4-Tipi_di_file.md) Feedback: issue #31 
  - Capitolo 5  – [Risorse esterne](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/5-Risorse_esterne.md) Feedback: issue #36 

#### Prendere in carico il progetto
* Scrivi nello issue #217 l'URL dell'articolo che vuoi tradurre. Verrà aperto uno issue dedicato.
* Accedi a [MDN](https://developer.mozilla.org/) con il tuo account GitHub
* Attieniti alle [istruzioni per MDN del capitolo 3](https://github.com/kitsunenosaraT/Mozilla-Italia-l10n-guide/blob/master/it/3-Flusso_di_lavoro.md#mdn) e ai suggerimenti del resto della guida, in particolare [i consigli pratici del capitolo 2](https://github.com/kitsunenosaraT/Mozilla-Italia-l10n-guide/blob/master/it/2-Linee_guida_di_Mozilla_Italia.md#consigli-pratici)
* Quando hai terminato, aggiungi a questo issue il [label](https://help.github.com/en/github/managing-your-work-on-github/about-labels) `richiesta revisione tecnica` e **avvisa con un messaggio nella sezione commenti**.
  * Se sei il revisore tecnico, quando hai terminato, elimina il *label* `richiesta revisione tecnica` e applica quello `richiesta revisione stilistica`.
  * Se sei il revisore stilistico, quando hai terminato, elimina il label `richiesta revisione stilistica`.
* Per qualsiasi problema o domanda scrivi pure in questo issue
* …e buona traduzione! 🎊 

## Link Utili
* Motori di ricerca per la terminologia
  - [Pontoon: tutti i progetti](https://pontoon.mozilla.org/it/all-projects/all-resources/?utm_source=pontoon-addon&string=66616) -- Per gli elementi UI, le funzioni e altra terminologia dei prodotti Mozilla.
  - [Transvision](https://transvision.mozfr.org/) -- Motore di ricerca esterno per i software e i siti  Mozilla, complementare a Pontoon.
  - [Microsoft Language Portal](https://www.microsoft.com/en-us/language/Search?langID=408&Source=true&productid=0) -- Per gli elementi UI, le funzioni e altra terminologia dei prodotti Microsoft.

❗️ **N.B.** Per segnalare la traduzione di un nuovo articolo utilizzare lo issue indice #217.

**Comment by JennyDC2020** [comment]
Grazie mille @Sav22999 

Finisco di guardare l'ultima parte della guida e poi comincio il lavoro  :blush:

**Comment by JennyDC2020** [comment]
Buon pomeriggio!

Sto ultimando la traduzione; a dire il vero ci ho messo molto meno tempo di quello che sembra: ma ho avuto dei giorni complicati e il tempo era scarsissimo. 

Ho due dubbi che avrei bisogno di chiarire 😊! Carico la schermata che ho su OmegaT per maggiore chiarezza.

![Tag](https://user-images.githubusercontent.com/72305254/97783234-a90a4900-1b96-11eb-9851-dde573391ad1.png)

**1) _Traduzione valori degli attributi id_**

I valori degli attributi "id" vanno tradotti? Ho spulciato altre pagine su MDN nelle altre lingue e sembra di sì...ma prima di combinare qualche guaio preferisco chiedere! Se così fosse, ad esempio, l'attributo:

`<h2 id="In_this_module">`

diventerebbe:

`<h2 id="In_questo_modulo">` 

e così via.

**2) _Modifica dei collegamenti con quelli che rimandano alla versione italiana_**

I collegamenti descritti nell'articolo che sto traducendo puntano alla versione inglese; credo che sia meglio cambiarli. Modificherei l'indirizzo del collegamento (quello contenuto dentro `href`) e tradurrei il testo, seguendo come esempio i titoli degli articoli di volta in volta citati; ad esempio l'elemento puntato:

`<li id="Installing_basic_software"><a href="/en-US/Learn/Getting_started_with_the_web/Installing_basic_software">Installing basic software</a></li>`

diventerebbe:

`<li id="Installazione_di_software_fondamentali"><a href="https://developer.mozilla.org/it/docs/Learn/Getting_started_with_the_web/Installing_basic_software">Installazione di software fondamentali</a></li>`

Mentre attendo le risposte di @Sav22999 oppure di @kitsunenosaraT o ancora di @michrogit (o di chiunque altro voglia aiutarmi!), rileggo il testo tradotto - che non ho ancora copiato su MDN - per vedere come "suona".  :kissing:

**Comment by kitsunenosaraT** [comment]
Ciao @JennyDC2020 ! Grazie per aver tradotto l'articolo. Usi OmegaT, vedo! Bene!

> 1) Traduzione valori degli attributi id

Bella domanda. In realtà si auto-aggiornano con le parole dell'header tradotto quando salvi l'articolo su MDN.
Meglio lasciare che si aggiornino automaticamente, almeno siamo sicuri che il software di MDN li riconoscerà.

> 2) Modifica dei collegamenti con quelli che rimandano alla versione italiana

Di solito cambiamo i link in modo che puntino all'articolo italiano (se esiste). 
Tuttavia, [recenti sviluppi](https://t.me/mozItaL10n/6758) dal team che gestisce MDN suggeriscono che in un non lontano futuro tutti gli articoli tradotti dall'inglese verranno spostati e archiviati in modalità di sola lettura. Non sappiamo ancora i dettagli, ma temo che alla fine del trasferimento i link agli articoli italiani saranno inutilizzabili. Per questo ti consiglierei di non stare a perderci tempo e lasciare i link che rimandano all'inglese.

**Comment by JennyDC2020** [comment]
Eccomi 😊 

> Ciao @JennyDC2020 ! Grazie per aver tradotto l'articolo. Usi OmegaT, vedo! Bene!

Si si, sto usando OmegaT e mi sto trovando molto molto bene! Sono contenta perché non conoscevo assolutamente questo fantastico strumento! ❤️  

> Bella domanda. In realtà si auto-aggiornano con le parole dell'header tradotto quando salvi l'articolo su MDN.
> Meglio lasciare che si aggiornino automaticamente, almeno siamo sicuri che il software di MDN li riconoscerà.

Ok 👍 
 
> Di solito cambiamo i link in modo che puntino all'articolo italiano (se esiste).
> Tuttavia, [recenti sviluppi](https://t.me/mozItaL10n/6758) dal team che gestisce MDN suggeriscono che in un non lontano futuro tutti gli articoli tradotti dall'inglese verranno spostati e archiviati in modalità di sola lettura. Non sappiamo ancora i dettagli, ma temo che alla fine del trasferimento i link agli articoli italiani saranno inutilizzabili. Per questo ti consiglierei di non stare a perderci tempo e lasciare i link che rimandano all'inglese.

Ok anche qui, lascio tutto così com'è!

Ho finalmente trovato il tempo per rileggere tutto, modificare alcune cosine, correggere errori di battitura. Copio il sorgente creato da OmegaT e incollo su MDN. (Lo faccio dopo pranzo, ormai!)

**Comment by JennyDC2020** [comment]
Ecco [la traduzione](https://wiki.developer.mozilla.org/it/docs/Learn/Getting_started_with_the_web/Come_funziona_il_Web) di "How the web works"; ho cercato di renderlo il più fluido possibile cercando però di rimanere fedele all'originale. Sicuramente qualche erroretto c'è, vi chiedo di avere pazienza! ❤️

**Comment by massic80** [comment]
Mi chiedo se in generale abbia senso tradurre acronimi strettamente tecnici che - nei pochi casi in cui si fa - vengono espressi sempre in inglese.
Il TCP/IP per esempio viene chiamato sempre tisipì, non si "sbobina" mai... non so se abbia una definizione formale in italiano, del tipo
_TCP/IP: Il Protocollo di Controllo di Trasmissione e il Protocollo Internet_.
Io al massimo metterei qualcosa come _TCP/IP: Ii Transmission Control Protocol (Protocollo di Controllo di Trasmissione) e l'Internet Protocol (Protocollo Internet in italiano)_.
Diversamente dovremmo dire Interrete al posto di Internet e Committa al posto di Commit come il menu contestuale di TortoiseGit :)
Che ne dite?

**Comment by kitsunenosaraT** [comment]
@JennyDC2020 Grazie, non vedo l'ora di leggerlo 😃 Purtroppo non ho molto tempo a disposizione in queste settimane, quindi chiedo a te di avere pazienza se la revisione si farà un po' aspettare...

@massic80 Non mi risulta che ci sia una regola fissa per tradurre gli acronimi o meno, in genere ci si basa sull'uso comune (quale versione è più riconoscibile dal lettore). Nel caso di TCP/IP (che appare sempre così) concordo pienamente con la tua strategia di lasciare l'acronimo invariato e inserire la versione estesa + traduzione tra parentesi.
Una volta letto l'articolo vedrò meglio…

**Comment by JennyDC2020** [comment]
@kitsunenosaraT 
Non preoccuparti, non ho fretta 😊

**Comment by kitsunenosaraT** [comment]
@JennyDC2020 
Come scritto nello issue #217 d'ora in avanti su MDN non sarà più possibile modificare gli articoli in italiano o tradurne di nuovi. Il tuo articolo è stato pubblicato e adesso è consultabile in modalità di sola lettura. Questo significa che non posso modificarlo per farti il QA, mi dispiace molto 🙇 
Ad ogni modo ho letto comunque l'articolo e lo trovo nel complesso chiaro e scorrevole. Sono contenta che tu abbia fatto in tempo a terminarlo prima che chiudessero la localizzazione, così è rimasto un tuo contributo a MDN 😄 
Grazie davvero, e mi dispiace che il progetto si sia concluso proprio mentre stavi iniziando, ma vedrai che in futuro arriveranno nuove occasioni!

**Comment by JennyDC2020** [comment]
Ciao Sara, scusami per il ritardo (avevo letto ma poi mi ero dimenticata di rispondere :frowning:!) 

Il mio tempismo è da manuale :satisfied: ma vuol dire che doveva andare così; è stato breve ma intenso: altri progetti e altre occasioni arriveranno!

Grazie ancora per il tuo supporto  :green_heart:
