### ISSUE TITLE
Translating MDN – [Flexbox]

### ISSUE THREAD

**Issue by kitsunenosaraT** [MozillaItalia/Mozilla-Italia-l10n-guide#264]
Questo issue è dedicato alla traduzione e revisione di un articolo di [MDN](https://developer.mozilla.org/).

## Informazioni sul progetto
**URL**: https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Flexbox

**URL traduzione**:

**Formato di file**: markup wiki (testo con tag)

**Strumenti**: a scelta tra [interfaccia di traduzione MDN](https://developer.mozilla.org/) (online) / editor di testo semplice (offline) / [OmegaT](http://omegat.org/) (offline)

### Prima di iniziare
- Crea un account GitHub (se non lo hai già): ti servirà sia per scrivere in questo issue, sia per accedere a MDN
  - (Facoltativo) Installa il componente aggiuntivo [MozIta L10n Addons](https://addons.mozilla.org/it/firefox/addon/mozita-l10n-addons/) per accedere più facilmente ai caratteri speciali come `’ “ ” È` ecc.
- Leggi "[Come tradurre le pagine di MDN](https://developer.mozilla.org/it/docs/MDN/Contribute/Localize/Translating_pages)"

- Leggi i capitoli della guida. Se lo desideri, lascia un feedback nel relativo issue:
  - Capitolo 1 – [Buone norme di traduzione tecnica](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/1-Buone_norme_di_traduzione.md) Feedback: issue #225 
  - Capitolo 2 – [Linee guida di Mozilla Italia](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/2-Linee_guida_di_Mozilla_Italia.md) Feedback: issue #138
  - Capitolo 3 – [Flusso di lavoro](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/3-Flusso_di_lavoro.md) Feedback: issue #24 
  - Capitolo 4 – [Tipi di file](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/4-Tipi_di_file.md) Feedback: issue #31 
  - Capitolo 5  – [Risorse esterne](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/5-Risorse_esterne.md) Feedback: issue #36 

#### Prendere in carico il progetto
* Scrivi nello issue #217 l'URL dell'articolo che vuoi tradurre. Verrà aperto uno issue dedicato.
* Accedi a [MDN](https://developer.mozilla.org/) con il tuo account GitHub
* Attieniti alle [istruzioni per MDN del capitolo 3](https://github.com/kitsunenosaraT/Mozilla-Italia-l10n-guide/blob/master/it/3-Flusso_di_lavoro.md#mdn) e ai suggerimenti del resto della guida, in particolare [i consigli pratici del capitolo 2](https://github.com/kitsunenosaraT/Mozilla-Italia-l10n-guide/blob/master/it/2-Linee_guida_di_Mozilla_Italia.md#consigli-pratici)
* Quando hai terminato, aggiungi a questo issue il [label](https://help.github.com/en/github/managing-your-work-on-github/about-labels) `richiesta revisione tecnica` e **avvisa con un messaggio nella sezione commenti**.
  * Se sei il revisore tecnico, quando hai terminato, elimina il *label* `richiesta revisione tecnica` e applica quello `richiesta revisione stilistica`.
  * Se sei il revisore stilistico, quando hai terminato, elimina il label `richiesta revisione stilistica`.
* Per qualsiasi problema o domanda scrivi pure in questo issue
* …e buona traduzione! 🎊 

## Link Utili
* Motori di ricerca per la terminologia
  - [Pontoon: tutti i progetti](https://pontoon.mozilla.org/it/all-projects/all-resources/?utm_source=pontoon-addon&string=66616) -- Per gli elementi UI, le funzioni e altra terminologia dei prodotti Mozilla.
  - [Transvision](https://transvision.mozfr.org/) -- Motore di ricerca esterno per i software e i siti  Mozilla, complementare a Pontoon.
  - [Microsoft Language Portal](https://www.microsoft.com/en-us/language/Search?langID=408&Source=true&productid=0) -- Per gli elementi UI, le funzioni e altra terminologia dei prodotti Microsoft.

❗️ **N.B.** Per segnalare la traduzione di un nuovo articolo utilizzare lo issue indice #217.

**Comment by danielebarell** [comment]
Ciao,
Tutto bene? Siete in verde, gialla o rossa?
Ad ogni modo abituiamoci a state in campana perchè continuieremo a fluttuare tra sti colori...

@kitsunenosaraT , @Mte90 
Sono circa a metà dell'articolo e spero di portarlo a termine entro la fine della settimana prossima o l'inizio della successiva, dipenderà dall'intensità degli altri impegni lavorativi.

Rispetto agli articoli precedenti c'è una parte tecnica più approfondita con file di esempio che l'utente dovrebbe scaricare per eseguire alcune piccole variazioni di codice come da esempi.
Queste pagine di esercitazione hanno testo in inglese. E' solo testo riempitivo tipo "Ipse lorum...", **mi domando se occorra farne una versione non-inglese, sostituendo il testo attuale con, appunto, il noto "Ipse lorum..."**.
Se la rispota fose positiva occorre fare anche degli screenshot .png da sostituire agli attuali. 

Per il resto l'impatto tecnico rimane relativamente leggero e chiaro. 
C'è **un'esercitazione parzialmente fuorviante**, a mio parere, che riguarda il comportamento dei componenti in overflow (superamento dei margini del loro contenitore): raggiunta una certa dimensione della finestra del browser l'overflow NON si verifica quindi **chi esegue l'esercizio potrebbe non riscontrare il problema di partenza**

Questo è tutto per ora.

Buon fine settimana :)

**Comment by Mte90** [comment]
vediamo che dice anche @xplosionmind visto che ha fatto il talk su mdn e non è proprio sviluppatore.

**Comment by xplosionmind** [comment]
ciao! Mitico @danielebarell, stai facendo un lavoro pazzesco!

@Mte90 non capisco bene perché mi hai taggato; se riguarda gli screenshot, secondo me non sono da tradurre, forse sarebbe eccessivo, se riguarda l'overflow non funzionante, chiederei a Daniele di indicarmi quale articolo: si tratta di quello su flexbox di questo issue oppure dei precedenti a cui hai fatto riferimento?

**Comment by danielebarell** [comment]
> ciao! Mitico @danielebarell, stai facendo un lavoro pazzesco!

Ti ringrazio ;) ma non sono neppure al giro di boa... vedremo alla fine.

Il problema specifio che segnalavo:

"_One issue that arises when you have a fixed amount of width or height in your layout is that eventually your flexbox children will overflow their container, breaking the layout._"
Dice che potrebbe verificarsi un overflow (cioè una sbordatura degli elementi figli all'interno del contenitore che causa la comparsa scrollbar orizzontale) che secca il layout. 
In effetti specifica "eventually" ovvero che può capitare oppure no.

Nel link che mette e che vi invito a guardare [live view](https://mdn.github.io/learning-area/css/css-layout/flexbox/flexbox-wrap0.html) l'overflow si verifica solo se la finestra del browser è larga meno di 1600 pixel, a dimensione più alta il problema non si riscontra.
Qunindi chi visualizza in HD a 1920 sto problema da cui scaturisce tutta la successiva trattazione, non lo percepisce.

@Mte90 , @xplosionmind 
Vi chiedo di verificare se ad una larghezza superiore a 1600 sta pagina perde lo scroll orizzontale
e poi vi chiedo un parere: secondo voi vale la pena sollevare il problema con MDN?

**Comment by Mte90** [comment]
Io ho 1800 di larghezza e c'è solo la barra laterale per lo scroll verticale.

Per il testo riempitivo direi che si può lasciare in inglese dopotutto è solo di esempio, di solito si usa il lorem ipsum.

**Comment by xplosionmind** [comment]
Eccomi. Scusa per il ritardo, @danielebarell. A me l'overflow funziona. Ho un Mac retina, quindi direi che la mia risoluzione è più che HD. Allego screenshot di come vedo l'estremità destra della pagina (dopo avere scrollato).

![Screenshot 2020-11-13 at 11 18 36 PM](https://user-images.githubusercontent.com/42862428/99126593-c8798b00-2606-11eb-9e0a-d5501a0c72e5.jpg)

**Comment by danielebarell** [comment]
@kitsunenosaraT @Mte90  @xplosionmind 

Ciao,
spero tutti bene !

In questo momento ho pubblicato l'articolo.
:)

Si annunciava piuttosto complesso ed in effetti lo é stato, più dei precedenti direi.
Devo ammettere che star dietro alle spiegazioni dell'autrice stavolta mi ha provato non poco, ma tra uno sfarfallio e l'altro spero sia uscito un buon lavoro di base.
@kitsunenosaraT 
A livello stilistico ho cercato di migliorare ulteriormente l'espressività in Italiano tenendo conto delle discussioni che abbiamo avuto nelle occasioni precedenti. Occorre però dire che l'impostazione è diversa, molto più simile a un tutorial pratico che a un articolo tecnico espositivo. 
@Mte90 , @Mte90 
A livello tecnico non mi pare ci sia nulla da controllare al momento, perchè ho lasciato invariate le sorgenti di riferimento.
Tuttavia se decidessimo di localizzarle ci sarebbe un lavoro da fare un po' lungo, 
A mio parere però **sarebbe opportuno fare una localizzazione.**

Nel prossimo post elenco ciò che andrebbe andrebbe localizzato.

**Comment by Mte90** [comment]
![Screenshot_2020-11-17 Flexbox](https://user-images.githubusercontent.com/403283/99414563-39ff5500-28f7-11eb-909e-44eb81236a27.png)
Vedo questo in cima è un errore forse?

**Comment by danielebarell** [comment]
I file da localizzare sarebbero:  
https://github.com/mdn/learning-area/blob/master/css/css-layout/flexbox/flexbox0.html
https://mdn.github.io/learning-area/css/css-layout/flexbox/flexbox0.html
https://github.com/mdn/learning-area/blob/master/css/css-layout/flexbox/flexbox-wrap0.html
http://mdn.github.io/learning-area/css/css-layout/flexbox/flexbox-wrap0.html
https://github.com/mdn/learning-area/blob/master/css/css-layout/flexbox/flexbox1.html
http://mdn.github.io/learning-area/css/css-layout/flexbox/flexbox1.html
https://github.com/mdn/learning-area/blob/master/css/css-layout/flexbox/complex-flexbox.html
https://wiki.developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Cross_browser_testing

https://github.com/mdn/learning-area/blob/master/css/css-layout/flexbox/flex-align0.html
http://mdn.github.io/learning-area/css/css-layout/flexbox/flex-align0.html
che contiene una pulsantiera.
La proposta di traduzione delle label si trova qui:
https://codepen.io/danielebarell/pen/rNLqYqQ?editors=0100 
(@kitsunenosaraT  scusa, Sara, so che non si deve piazzare pagine personali, ma gli snippet di codice non so dove altrimenti provarli)

--

e occorrerebbero anche le rispettive immagini .png, mi pare siano sette:

https://i.imgur.com/Bih741v.png
https://media.prod.mdn.mozit.cloud/attachments/2016/06/21/13408/716e67fb3ceb12d91c318cb673ddcfce/flexbox-example2.png
https://media.prod.mdn.mozit.cloud/attachments/2016/06/21/13410/32ebb3a8615fc65e21b55178f0dae139/flexbox-example3.png
https://media.prod.mdn.mozit.cloud/attachments/2016/06/21/13412/314e52407cb6bd74f795da2aa0a061f6/flexbox-example4.png
https://media.prod.mdn.mozit.cloud/attachments/2016/06/21/13406/c1f996af7f5da5cb14752e311f7bdd0d/flexbox-example1.png
https://media.prod.mdn.mozit.cloud/attachments/2020/04/29/17210/96d86573b60cc21a1c56739d759c997b/flexbox_center_space-around.png
https://media.prod.mdn.mozit.cloud/attachments/2020/04/29/17211/62e2715b9685153e61d9b924f2bbcc97/flexbox_first-child_flex-end.png
https://media.prod.mdn.mozit.cloud/attachments/2016/06/21/13418/4ca8450e3da203b923a08c8b088be4d6/flexbox-example7.png

**Comment by danielebarell** [comment]
A mo di nota dichiaro subito il prossimo articolo da tradurre:
https://wiki.developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Flexbox_skills
che é il test associato alla comprensione dell'articolo, una piccola deviazione rispetto al percorso che sto cercando di seguire.

**Comment by danielebarell** [comment]
> 
> 
> ![Screenshot_2020-11-17 Flexbox](https://user-images.githubusercontent.com/403283/99414563-39ff5500-28f7-11eb-909e-44eb81236a27.png)
> Vedo questo in cima è un errore forse?

@Mte90 
Confermo.
Io vedo un alertbox che dice:
> "Questa pagina contiene un errore di script. Nell’attesa che venga corretto dagli editori del sito, è possibile visualizzare qui di seguito una versione provvisoria dei contenuti. "

e se apri il box hai:


> Tutti gli utenti registrati di MDN possono modificare un documento per correggere eventuali errori. Per iniziare fai riferimento alla guida alla risoluzione dei problemi in KumaScript.

   ```
 Tipo di errore:
        MacroInvocationError 
    Testo completo dell’errore:

        Syntax error at line 112, column 88 of document:
          110 | <h2 id="La_forma_contratta_flex-flow">La forma contratta flex-flow</h2>
          111 | 
          112 | <p>Occorre notare a questo punto che esiste una forma contratta, {{cssxref("flex-flow")}, per le proprietà {{cssxref("flex-direction")}} e {{cssxref("flex-wrap")}} — }. É possibile per esempio sostituire</p>
        -----------------------------------------------------------------------------------------------^
          113 | 
          114 | <pre class="brush: css  notranslate">flex-direction: row;
        Expected "}}" or [ \t\n\r;] but "}" found.


Al momento non riesco a spiegare cosa non vada. :(

```

**Comment by kitsunenosaraT** [comment]
@danielebarell Grazie come al solito per il tuo scrupoloso lavoro! Metto questa revisione in coda tra le cose da fare.

**Comment by kitsunenosaraT** [comment]
@danielebarell come scritto nello issue #217 purtroppo non ho fatto in tempo a fare il QA stilistico prima che disattivassero la funzione di localizzazione di MDN.
Mi consolo perché il tuo articolo, che era già completo e revisionato dal punto di vista tecnico (grazie anche a @Mte90 e @xplosionmind ), è ancora accessibile sul sito (anche se in modalità di sola lettura).

So che ormai è tardi, ma ho letto comunque l'articolo e ci ho trovato la tua solita scrupolosità e attenzione. Visto che era un articolo lungo e complesso, che immagino ti sia costato molta fatica, sono davvero desolata di non avergli reso onore con un bel QA.
Anche se questo progetto si ferma, tutti gli articoli che hai tradotto rimangono e hanno un valore. Inoltre in futuro ci saranno senz'altro altre iniziative interessanti in cui usare le tue conoscenze, quindi spero che rimarrai con noi.

Con questo, chiudo lo issue.
