### ISSUE TITLE
(IT) Capitolo 2 – Linee guida di Mozilla Italia

### ISSUE THREAD

**Issue by kitsunenosaraT** [MozillaItalia/Mozilla-Italia-l10n-guide#27]
**ENGLISH**
This is the *issue* (or topic) where new volunteers can discuss enhancements to the first draft of chapter  [2-Linee guida di Mozilla Italia.md](https://github.com/kitsunenosaraT/Mozilla-Italia-l10n-guide/blob/master/it/2-Linee_guida_di_Mozilla_Italia.md)

This chapter deals with Mozilla’s approach to themes such as developing a coherent internal terminology, projecting a strong identity, dealing with the new and evolving panorama of web terminology etc.
Please, read the chapter linked above and write down in this section all your comments, suggestions and impressions.
To quote the part you are referring to, copy-paste it in your comment and enter the character `>` in front of the first letter, just like this:
___
```
>This is the first chapter of the guide and deals with such matters as general translation best practices: syntax, punctuation, false friends etc.

It would be useful to add to the list a section about the most common mistakes.
```
will be displayed as:

>This is the first chapter of the guide and deals with such matters as general translation best practices: syntax, punctuation, false friends etc.

It would be useful to add to the list a section about the most common mistakes.
___
**ITALIANO**
Questo *issue* è lo spazio dove i nuovi volontari possono discutere i miglioramenti da apportare alla prima bozza del capitolo [2-Linee guida di Mozilla Italia.md](https://github.com/kitsunenosaraT/Mozilla-Italia-l10n-guide/blob/master/it/2-Linee_guida_di_Mozilla_Italia.md)

Il capitolo descrive l’approccio di Mozilla a tematiche come lo sviluppo di una terminologia interna coerente, la creazione di un'identità comunitaria chiara e riconoscibile, la gestione dei nuovi termini che dal mondo del Web si riversano nella lingua italiana, ecc.
Per partecipare leggi il capitolo nel paragrafo precedente e scrivi in questa sezione i tuoi commenti, suggerimenti e impressioni.
Per citare una parte specifica della guida, copia-incolla la parte rilevante nel campo dei commenti e inserisci davanti il carattere `>`, come nel seguente esempio:
___
```
>In ultimo bisogna evitare le trappole dei false friend (parole straniere che somigliano a termini esistenti italiani, ma hanno un significato diverso). Alcuni dei principali sono:

Vorrei suggerire alcuni *false friend* da aggiungere alla lista…
```
verrà visualizzato come:
>In ultimo bisogna evitare le trappole dei false friend (parole straniere che somigliano a termini esistenti italiani, ma hanno un significato diverso). Alcuni dei principali sono:

Vorrei suggerire alcuni *false friend* da aggiungere alla lista…
–––
## Aggiornamenti per la seconda bozza
- [x] Aggiungi neologismi / risemantizzazione di termini esistenti (gialloporpora)
- [x] #Terminologia: se e quando tradurre: aggiungi esempio di cookie agli esempi di termini che se tradotti creano confusione (gialloporpora)
- [x] #Tradurre: i pro e i contro: aggiungi esempio di mouse (dispositivo di puntamento ottico) tra i traducenti italiani caduti in disuso (gialloporpora)
- [x] #Un caso particolare: la documentazione tecnica: correggere il link nel TOC (eliogi)
- [x] #Non tradurre: i pro e i contro: evita termini troppo accademici come “acriticamnte” (Mte90)
- [x] #Non tradurre: i pro e i contro: aggiungi l'allontanamento dell'utente tra gli svantaggi di qst. metodo (Mte90)
- [x] #Tradurre: i pro e i contro: esempio di traduzione fuorviante in trash > spazzatura (Mte90)
- [x] #Un caso delicato: la documentazione tecnica: approfondire l'argomento con Mte90
- [x] #Identità e missione di Mozilla: Sottolineare come la creazione collaborativa di un glossario sia un momento importante di aggregazione per la comunità e spunto di interessanti discussioni (Mte90)
- [x] Evitare i possessivi quando ovvi (es. **Publish your Project**>**Pubblica il progetto**), metterli solo quando rendono la traduzione migliore (es. **Your Project is Online** > **Il tuo progetto è stato pubblicato**) (eliogi)
- [x] aggiungi nota sui vari “internet” (con la minuscola) (eliogi)
- [x] Aggiungi click > clic, to click > fare clic e non "cliccare" (Mte90)
- [x] Aggiungi crittografia ecc. tra i termini del glossario (flodolo)

**Comment by kitsunenosaraT** [comment]
See https://github.com/kitsunenosaraT/Mozilla-Italia-l10n-guide/pull/26#issuecomment-296996677 for gialloporpora's suggestionst.

**Comment by eliogi** [comment]
Read Chapter 2 completely. For me it's ok.
I've checked also summary, please update the item "Un caso particolare: la documentazione tecnica" with the correct link.

**Comment by Mte90** [comment]
My feedback:

- traducenti: mai sentito, ho imparato una parola nuova ma forse mettere la sua spiegazione tra parentesi? cosi semplifichiamo la curva di apprendimento
- acriticamente: mai sentito, pensavo ad un errore di battitura
- l'esempio di testo mezzo inglese e italiano è bellissimo e spaventoso
- la spiegazione dopo il testo mi sembra buona, metterei anche che allontana le persone fare un testo del genere, dopotutto stai parlando in italiano perché usare termini che non sono tuoi? non tutti li conoscono
- ho visto tradurre trash come spazzatura nel mondo wordpress quindi nei pro e contro direi che serve menzionare il glossario
- per la documentazione tecnica io sottolinerei che un esperto può riconoscere in un testo completamente in inglese quali sono termini tecnici e quali non lo sono ad esempio `download` rispetto a `design pattern`. Inoltre spesso per la parte tecnica non è necessario tradurre il amteriale perché gli esperti conoscono l'inglese quindi si può focalizzare il lavoro su materiale con altre priorità (esempio della comunità wordpress).
- nel riquadro identità e missione si parla di definire nuovi termini ptoermmo dire di fare l'accademia della crusca per il web, per rendere il testo più amichevole e far passare il messaggio

Sull'ultima sezione posso darvi il mio talk riguardo come gestire i termini: mte90.github.io/Talk-WhyGlossary/
In poche parole per me bisogna definire a quale pubblico è pensato il testo e questo termine in modo tale da vautare se serve la sua traduzione e se già esiste.

**Comment by kitsunenosaraT** [comment]
Grazie @Mte90! Hai fornito degli spunti molto utili.
In particolare:
- Traducenti: infatti è un termine molto tecnico, sebbene utile in una guida di localizzazione. Intendiamo al prossimo giro aggiungere questo e alcuni altri termini tecnici al [glossario dell'introduzione](https://github.com/kitsunenosaraT/Mozilla-Italia-l10n-guide/blob/master/it/README.md#glossario)
- acriticamente e parole simili: ricevuto, è importante usare un linguaggio più comune. Nella prossima sessione lo sostituisco, e se trovi altre parole simili non esitare a segnalarmele 👍 
- un linguaggio pseudo-inglese allontana l’utente, giusto, va sottolineato!
- teniamoci buono l'esempio d trash >spazzatura :rofl: 
- Accademia della Crusca del Web, sì, rende l'idea.
>per la documentazione tecnica io sottolinerei che un esperto può riconoscere in un testo completamente in inglese quali sono termini tecnici e quali non lo sono ad esempio download rispetto a design pattern. Inoltre spesso per la parte tecnica non è necessario tradurre il amteriale perché gli esperti conoscono l'inglese quindi si può focalizzare il lavoro su materiale con altre priorità (esempio della comunità wordpress).

Qui in linea di massima sono d'accordo, però sul punto che tanto un esperto non ha bisogno di traduzioni ci sarebbe un po' da discutere.

Infine grazie per le slide sulla terminologia che hai messo nel link. Ho trovato molto importante la parte in cui parli di come il processo di compilare insieme un glossario sia un elemento aggregante per la comunità e faccia sorgere dibattiti interessanti. Vorrei incorporare questa parte nel capitolo perché ci sta a pennello 😀

**Comment by Mte90** [comment]
Per la parte traduzione io vedo che imn ambito tech non è importante se è tradotta in Italiano e lo stesso dicono altri programmatori, quindi dipende di nuovo dal pubblico e organizzare il materiale con queste priorità aiuta ad avere degli obiettivi che in un team di traduzione servono per vedere il progresso ed organizzarsi.
Integra quello che ti serve, questo progetto è menzionato nelle slide e lo citerò al Wordcamp Europe del prossimo mese

**Comment by EugenioPetulla** [comment]
Molto ben fatto, complimenti vivissimi.

Detto questo, mi accodo per aggiungere un piccolo tema che mi capita spesso di affrontare con le traduzioni tecniche, ovvero il contesto. A volte nella traduzione tecnica e' necessario assicurarsi del contesto in cui si usano vari termini per disambiguarne il significato.

Ad esempio il termine 'Post' in inglese ha svariati significati e può essere sia un verbo che un sostantivo, il tutto dipendente dal contesto che gioca quindi un ruolo fondamentale nelle traduzioni.

Detto questo, ancora complimenti per l'ottimo lavoro svolto! :)

**Comment by kitsunenosaraT** [comment]
Grazie @EugenioPetulla hai fatto un esempio molto calzante. L'importanza del contesto andrebbe effettivamente trattato nel [Capitolo 1](https://github.com/kitsunenosaraT/Mozilla-Italia-l10n-guide/blob/master/it/1-Buone_norme_di_traduzione.md#verbi-e-sostantivi). Vado ad aggiungere il tuo intervento nella lista dei miglioramenti per la seconda bozza dello issue #23  :+1:
E intanto aggiungo, come ha detto @Mte90 , "traducente" allo issue #33  dell'introduzione.

**Comment by kitsunenosaraT** [comment]
Aggiunta nota per inserire

>to encode/decode: codificare/decodificare
to encipher/decipher: cifrare/decifrare
cipher: algoritmo di cifratura (?)
to encrypt/decrypt: crittare/decrittare
encryption: crittografia

suggerita da @flodolo

**Comment by kitsunenosaraT** [comment]
I nuovi suggerimenti sono stati implementati nella pull request #133 
Chi ha inserito dei suggerimenti è invitato a leggere la proposta di capitolo per verificare se sono stati inseriti in maniera soddisfacente. La pull request rimarrà aperta fino a fine mese, dopo di che, se non ci saranno feedback, verrà pubblicata come secondo capitolo.

**Comment by kitsunenosaraT** [comment]
Tutti i suggerimenti sono stati incorporati nella versione 2 del capitolo.
Per nuove segnalazioni da incorporare nella versione 3 si può usare lo issue #138.

Grazie a tutti per i vostri feedback! 🦊
