### ISSUE TITLE
Weekly Translation of Pontoon Projects (Week #38/2021)

### ISSUE THREAD

**Issue by flodolo** [MozillaItalia/Mozilla-Italia-l10n-guide#310]
# Stringhe della settimana

| Nome progetto (e identificativo stringhe) | Numero stringhe | Traduttore `@username` | QA richiesto |  In revisione | Approvato |
| :-- | :-: | :-- | :-: | :-: | :-: |
| [AMO](https://pontoon.mozilla.org/it/amo/all-resources/?status=fuzzy%2Cmissing&utm_source=pontoon-addon&author=leanintocuriosity%40gmx.com&string=232137) | 3 | @JennyDC2020  |  ✅ | ✅ | ✅ |
| [Firefox for Android](https://pontoon.mozilla.org/it/firefox-for-android/all-resources/?status=missing%2Cfuzzy&string=232142) | 3 | @JennyDC2020  | ✅  | ✅ | ✅ |
| Mozilla.org | 102 |  |  |  |  |
|  | [29](https://pontoon.mozilla.org/it/mozillaorg/en/firefox/browsers/mobile/android.ftl/?status=missing&string=232006) | @michrogit | ✅ | ✅ | ✅ |
|  | [46](https://pontoon.mozilla.org/it/mozillaorg/en/firefox/browsers/mobile/compare.ftl/?status=missing&string=231934) | @JennyDC2020  | ✅ | ✅ | ✅ |
|  | [27](https://pontoon.mozilla.org/it/mozillaorg/en/firefox/browsers/mobile/ios.ftl/?status=missing&string=231994) | @michrogit | ✅ | ✅ | ✅ |
| [Common Voice](https://pontoon.mozilla.org/it/common-voice/all-resources/?status=missing&string=232146) | 2 | @michrogit | ✅ | ✅ | ✅ |

❗️  La lista delle stringhe da tradurre viene aggiornata più volte nell'arco della settimana

❕ I seguenti progetti non sono gestiti dal team L10n. **NON** includerli nella lista delle stringhe:
- Seamonkey (responsabile: Iacopo Benesperi)
- SUMO (responsabile: Team SuMo)
- Firefox (sola lettura)

## Informazioni sul progetto
Questo issue serve a gestire le traduzioni dei siti Mozilla sulla piattaforma [Pontoon](https://pontoon.mozilla.org/it/).

Ogni settimana uscirà un nuovo issue con una lista dei progetti che contengono stringhe mancanti. Puoi sempre trovare lo issue della settimana corrente sulla [bacheca del progetto](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/projects/5).
Chi vuole farsi avanti, a seconda della propria disponibilità, si "prenoterà" per le stringhe.
Questo per organizzare meglio l'attività di traduzione ed evitare che più persone lavorino sulle stesse stringhe.

#### Prima di iniziare:
* [Registrati](https://accounts.firefox.com/oauth/signin?response_type=code&scope=profile%3Auid%20profile%3Aemail%20profile%3Adisplay_name%20profile%3Auid%20profile%3Adisplay_name%20profile%3Aemail&state=yrvTUh3o4F4c&redirect_uri=https%3A%2F%2Fpontoon.mozilla.org%2Faccounts%2Ffxa%2Flogin%2Fcallback%2F&client_id=76ab66239b5585ad) sulla piattaforma di traduzione Pontoon
  - (Facoltativo) Installa i componenti aggiuntivi [Pontoon Add-on](https://addons.mozilla.org/it/firefox/addon/pontoon-tools/) per ricevere le notifiche sulle stringhe mancanti in tempo reale (più altre chicche) e [MozIta L10n Add-on](https://addons.mozilla.org/it/firefox/addon/mozita-l10n/) per accedere più facilmente ai caratteri speciali come `’ “ ” È` ecc.
* **Leggi i capitoli della guida**, se lo desideri, lascia un feedback nel relativo issue:
  - Capitolo 1 – [Buone norme di traduzione tecnica](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/1-Buone_norme_di_traduzione.md) Feedback: issue #225 
  - Capitolo 2 – [Linee guida di Mozilla Italia](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/2-Linee_guida_di_Mozilla_Italia.md) Feedback: issue #138
  - Capitolo 3 – [Flusso di lavoro](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/3-Flusso_di_lavoro.md) Feedback: issue #24 
  - Capitolo 4 – [Tipi di file](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/4-Tipi_di_file.md) Feedback: issue #31 
  - Capitolo 5  – [Risorse esterne](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/5-Risorse_esterne.md) Feedback: issue #36

#### Prendere in carico il progetto:
* Lascia un messaggio nella sezione Commenti, scrivendo di quale progetto vuoi occuparti (importante per avvisare gli altri che ci stai lavorando tu). Scrivi anche il tuo nome utente accanto al nome del progetto sulla lista qui in alto (usa l'icona `…` nell'angolo in alto a destra per modificare il testo.)
  - Se non sei ancora tra i [Collaborators](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/settings/collaboration) non hai i permessi per modificare la lista. Scrivi solo nei commenti, qualcuno con i permessi aggiungerà il tuo nome alla lista.
* Attieniti alle istruzioni del [capitolo 3](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/3-Flusso_di_lavoro.md) e del [capitolo 4](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/4-Tipi_di_file.md).
* Per qualsiasi problema o domanda scrivi pure in questo issue.
* Quando la tua traduzione è pronta, lascia un commento nello issue per dare l'OK al QA.
* Rimani a disposizione per il QA, ti verrà chiesto se vuoi confermare le modifiche del revisore o proporre un'alternativa.
* e buona traduzione! 🎊 

##### Alcune norme comportamentali da seguire
1. Non usare lo issue per discussioni fuori tema, conversazioni personali, battute umoristiche ecc. (per cui sono disponibili appositi gruppi Telegram e sezioni del forum).
2. Non usare la `@menzione` quando non strettamente necessario, in particolare non menzionare uno o tutti i revisori ogni volta che chiedi il QA (a meno che non desideri il parere di quel revisore specifico).
3. Puoi prenotarti per i progetti a seconda della tua disponibilità, ma ricorda di lasciare anche agli altri volontari occasione di partecipare.
4. Puoi (anzi sei incoraggiato a) aggiornare la lista di stringhe presenti nello issue se noti che sono apparse nuove stringhe su Pontoon e desidera tradurle.
5. Puoi prendere anche solo una parte delle stringhe di un progetto, secondo la tua disponibilità. Basta che inserisci una casella di spunta con rientro `<spazio><spazio>- [ ]` nella riga sotto il progetto in questione, scrivendo accanto il tuo nome e il numero di stringhe che prendi.

## Link Utili
* Server di test -- Per vedere dove andranno a finire le tue traduzioni
  - per le singole pagine di [mozilla.org](https://l10n.mozilla-community.org/langchecker/?action=listpages) 
  - per [AMO](https://addons-dev.allizom.org/it/)
  - per [MDN](https://developer.allizom.org/it/)
  - per [Common Voice](https://voice.allizom.org/it)
  - per [Thunderbird.net](https://www.thunderbird.net/it/) *sito produzione
  - per [Firefox Monitor](https://fx-breach-alerts.herokuapp.com/) + [Modelli email](https://fx-breach-alerts.herokuapp.com/email-l10n)
  - per [Mozilla Donate website](https://donate-wagtail.mofostaging.net/it/) + [Istruzioni test pagamenti](https://groups.google.com/forum/#!topic/mozilla.dev.l10n.web/aEWu_hSnYMU)
* Motori di ricerca per le stringhe
  - [Pontoon: tutti i progetti](https://pontoon.mozilla.org/it/all-projects/all-resources/?utm_source=pontoon-addon&string=66616) -- Cerca simultaneamente tra tutti i progetti di Pontoon in italiano.
  - [Transvision](https://transvision.mozfr.org/) -- Motore di ricerca esterno per le stringhe Mozilla, complementare a Pontoon.
  - [Microsoft Language Portal](https://www.microsoft.com/en-us/language/Search?langID=408&Source=true&productid=0) -- Glossario Microsoft.
* [Transvision Access Key](https://transvision.mozfr.org/accesskeys/) -- Rileva eventuali errori nelle access key (da controllare ogni volta che si traduce una stringa contenente access key)
* [Sezione Localization in Discourse](https://discourse.mozilla.org/c/l10n/547) -- Sezione dedicata alla localizzazione dei prodotti Mozilla.
* [#l10n-community in Matrix](https://chat.mozilla.org/#/room/#l10n-community:mozilla.org) -- Sezione dedicata alla comunità di localizzatori Mozilla su Matrix.

**Comment by flodolo** [comment]
@michrogit 
C'è una nuova stringa in ios.ftl, se vuoi prenderla.

Aggiunte 3 stringhe per AMO.

**Comment by michrogit** [comment]
> @michrogit
> C'è una nuova stringa in ios.ftl, se vuoi prenderla.

Presa e tradotta. È praticamente identica alla [stringa immediatamente successiva](https://pontoon.mozilla.org/it/mozillaorg/en/firefox/browsers/mobile/ios.ftl/?status=missing&string=231941) dove avevano invece utilizzato un `{ -brand-name-sync } your devices ecc.` che avevo dovuto aggirare perché in italiano `{ -brand-name-sync } i tuoi dispositivi ecc.` non lo potevo utilizzare. In questa nuova stringa hanno utilizzato `Sync` al posto di `{ -brand-name-sync }`. Non capisco se una delle due verrà eliminata visto che sono identiche…

**Comment by JennyDC2020** [comment]
Mi prenoto per le 46 stringhe di _Mozilla.org_ : parto da domani mattina, ormai 😉

**Comment by JennyDC2020** [comment]
Le [3 stringhe](https://pontoon.mozilla.org/it/firefox-for-android/all-resources/?status=missing%2Cfuzzy&string=232142) di _Firefox for Android_ sono pronte per il QA. 🌔

**Comment by flodolo** [comment]
> [3](https://pontoon.mozilla.org/it/amo/all-resources/?extra=missing-without-unreviewed&string=232137) di _AMO_

1 da rivedere qui.

**Comment by JennyDC2020** [comment]
Era quella che non mi tornava 😅
Approvo ovviamente 😉

**Comment by michrogit** [comment]
Le 2 stringhe [Common Voice](https://pontoon.mozilla.org/it/common-voice/all-resources/?status=missing&string=232146) sono pronte per il QA. Per quanto riguarda la seconda stringa, ero incerto su come tradurre quel "[Common Voice](https://pontoon.mozilla.org/it/common-voice/all-resources/?status=missing&string=232146)" e mi sono consultato con @Sav22999 prima di tradurla :wink:

**Comment by JennyDC2020** [comment]
Ho due dubbi che riguardano le stringhe di _Mozilla.org_ che sto traducendo e preferisco chiedere direttamente qui prima di arrivare al QA. 😃 

**Primo dubbio**

[Questa stringa](https://pontoon.mozilla.org/it/mozillaorg/en/firefox/browsers/mobile/compare.ftl/?string=232140) l'avevo tradotta così:
 
`Come minimo, il tuo browser mobile dovrebbe fornire una modalità “Navigazione anonima”, che elimina in modo automatico la cronologia e la cronologia di ricerca. Tutti e cinque i browser confrontati ottengono punti in quest’area.`

Per non ripetere _cronologia_ due volte, sarebbe sbagliato mettere: 

`[…] che elimina in modo automatico sia la cronologia dei siti visitati sia quella di ricerca. […]` 

**Secondo dubbio**

Considerando il contesto, [questa stringa](https://pontoon.mozilla.org/it/mozillaorg/en/firefox/browsers/mobile/compare.ftl/?string=232021) è meglio tradurla con:

1. `<strong>Caratteristiche</strong>`
2. `<strong>Funzioni</strong>`
3. `<strong>Opzioni</strong>`

Grazie 🙇

**Comment by flodolo** [comment]
> Per quanto riguarda la seconda stringa, ero incerto su come tradurre quel "[Common Voice](https://pontoon.mozilla.org/it/common-voice/all-resources/?status=missing&string=232146)" e mi sono consultato con @Sav22999 prima di tradurla 😉

Non ho capito 'sta frase. Detto questo, cosa significa in practica "take out" qui?

**Comment by flodolo** [comment]
@JennyDC2020 
Evitare la ripetizione va bene, puoi anche usare "cronologia di navigazione e di ricerca".

Direi "Caratteristiche" nella seconda.

**Comment by JennyDC2020** [comment]
> Evitare la ripetizione va bene, puoi anche usare "cronologia di navigazione e di ricerca".
> 
> Direi "Caratteristiche" nella seconda.

Grazie per la risposta, flodolo 😸 

Le [46 stringhe](https://pontoon.mozilla.org/it/mozillaorg/en/firefox/browsers/mobile/compare.ftl/?status=missing&string=231934) di _Mozilla.org_ sono pronte per il QA. 🌑

**Comment by michrogit** [comment]
> > Per quanto riguarda la seconda stringa, ero incerto su come tradurre quel "[Common Voice](https://pontoon.mozilla.org/it/common-voice/all-resources/?status=missing&string=232146)" e mi sono consultato con @Sav22999 prima di tradurla 😉
> 
> Non ho capito 'sta frase. Detto questo, cosa significa in practica "take out" qui?

Questo è quanto mi scriveva @Sav22999 nell'interscambio che abbiamo avuto su Telegram
`Forse permettono di cancellare le registrazioni inserite entro massimo X giorni`

**Comment by flodolo** [comment]
La prossima volta sarebbe più sicuro chiedere al responsabile del progetto via Pontoon, o controllare il codice ;-)

Visto l'ID e [questa discussione](https://github.com/common-voice/common-voice/pull/3133), credo sia semplicemente "download". Nel dubbio, provate a chiedere (come detto, vorrei occuparmi il meno possibile di certi progetti).

@michrogit 
QA pronto per i tuoi progetti, visto che erano in coda da un po'. Prima di sera, o comunque prima di lunedì, controllo anche il resto delle traduzioni per mozilla.org ;-)

**Comment by michrogit** [comment]
@flodolo, grazie per il QA delle stringhe Mozilla.org. Approvati tutti i tuoi più che corretti suggerimenti :wink:
Per la stringa Common Voice, anche secondo me è "download" stando a quanto da te indicato (ID e discussione). 
Pensi che possa approvarlo o preferisci che chiediamo delucidazioni?

**Comment by flodolo** [comment]
>  Pensi che possa approvarlo o preferisci che chiediamo delucidazioni?

Approviamo. Se vuoi usare il link "report or request context" per chiedere, tanto meglio (così vediamo se stanno effettivamente seguendo le traduzioni…)

**Comment by flodolo** [comment]
@JennyDC2020 
QA pronto, solo alcuni suggerimenti da rivedere in cui mi sono preso un po' di libertà, visto che si tratta di pagine marchettare.

**Comment by JennyDC2020** [comment]
> @JennyDC2020 
> QA pronto, solo alcuni suggerimenti da rivedere in cui mi sono preso un po' di libertà, visto che si tratta di pagine marchettare.

Ho letto e approvo tutti i tuoi suggerimenti 😉

**Comment by michrogit** [comment]
Ho approvato la stringa [Common Voice](https://pontoon.mozilla.org/it/common-voice/all-resources/?time=202109250514-202109250614&string=232145) in sospeso e chiesto chiarimenti tramite link "report or request context". Vediamo se e che cosa rispondono…

**Comment by michrogit** [comment]
> > @JennyDC2020
> > QA pronto, solo alcuni suggerimenti da rivedere in cui mi sono preso un po' di libertà, visto che si tratta di pagine marchettare.
> 
> Ho letto e approvo tutti i tuoi suggerimenti 😉

Approvato :wink: e chiuso il progetto Mozilla.org

**Comment by flodolo** [comment]
Miracolosamente niente arretrati a questo giro. Sperando si diano una calmata, nuova issue
https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/issues/311
