### ISSUE TITLE
Navigazione anonima

### ISSUE THREAD

**Issue by unbranched** [MozillaItalia/Mozilla-Italia-l10n-guide#322]
Salve, da tempo combatto per fare capire alla gente cosa faccia e soprattutto cosa NON faccia la "Navigazione anonima" di un browser, visto che l'utente medio fatica a comprendere. Dopo tanti anni da quando questa funzionalità è stata introdotta, purtroppo c'è ancora tanta confusione.

Noto che la traduzione italiana di Firefox la chiama appunto "Navigazione anonima"/"Finestra anonima"/eccetera , mentre in inglese è "Private window". Non ho trovato una discussione a riguardo sulla scelta del termine "anonima" ma penso che sia pericolosamente fuorviante per l'utente medio, visto che di anonimo non ha niente.

Nonostante "Navigazione privata" non risolverà del tutto le incomprensioni, penso che sia sicuramente migliore e meno allusiva ad un anonimato.

Cosa ne pensate?

**Comment by flodolo** [comment]
La scelta di utilizzare "Navigazione anonima" è stata fatta anni fa, prima che Google creasse Chrome e "Navigazione in incognito" (che soffre degli stessi problemi), preferendola a "Navigazione privata" o "Navigazione riservata".

Non si può sostituire il nome di una parte fondamentale dell'interfaccia dopo 15 anni, specialmente se l'alternativa ha gli stessi problemi della soluzione attuale. Anche se "Navigazione anonima" non è perfetta, a questo punto non ha senso cambiarla, perché creerebbe solo ulteriore confusione per gli utenti.

Nel caso di questa funzione, nessun nome riuscirà mai a spiegare cosa è davvero anonimo/privato.

**Comment by unbranched** [comment]
Capisco e ti ringrazio per la spiegazione, credo solo che sia un peccato che fosse stata scelta la parola peggiore tra le possibili.
"Privata" e "riservata" mi sembrano almeno decenti, "Incognito" di Chrome invece è proprio sbagliata allo stesso modo di Anonima.
