### ISSUE TITLE
(IT) Introduzione

### ISSUE THREAD

**Issue by kitsunenosaraT** [MozillaItalia/Mozilla-Italia-l10n-guide#33]
**ENGLISH**
This is the *issue* (or topic) where new volunteers can discuss enhancements to the first draft of the Italian [Introduction](https://github.com/kitsunenosaraT/Mozilla-Italia-l10n-guide/blob/master/it/README.md)

The introduction briefly presents Mozilla and its core values, the Italian l10 team and explains the role of volunteer translators in our organization.
Please, read the chapter linked above and write down in this section all your comments, suggestions and impressions.
To quote the part you are referring to, copy-paste it in your comment and enter the character `>` in front of the first letter, just like this:
___
```
>This is the first chapter of the guide and deals with such matters as general translation best practices: syntax, punctuation, false friends etc.

It would be useful to add to the list a section about the most common mistakes.
```
will be displayed as:

>This is the first chapter of the guide and deals with such matters as general translation best practices: syntax, punctuation, false friends etc.

It would be useful to add to the list a section about the most common mistakes.
___
**ITALIANO**
Questo *issue* è lo spazio dove i nuovi volontari possono discutere i miglioramenti da apportare alla prima bozza dell’[Introduzione](https://github.com/kitsunenosaraT/Mozilla-Italia-l10n-guide/blob/master/it/README.md).
L’introduzione presenta brevemente Mozilla e i suoi principi fondanti, oltre che il team di localizzazione di Mozilla Italia. Inoltre spiega il ruolo dei traduttori volontari all’interno della nostra organizzazione.
Per partecipare leggi il capitolo nel paragrafo precedente e scrivi in questa sezione i tuoi commenti, suggerimenti e impressioni.
Per citare una parte specifica della guida, copia-incolla la parte rilevante nel campo dei commenti e inserisci davanti il carattere `>`, come nel seguente esempio:
___
```
>In ultimo bisogna evitare le trappole dei false friend (parole straniere che somigliano a termini esistenti italiani, ma hanno un significato diverso). Alcuni dei principali sono:

Vorrei suggerire alcuni *false friend* da aggiungere alla lista…
```
verrà visualizzato come:
>In ultimo bisogna evitare le trappole dei false friend (parole straniere che somigliano a termini esistenti italiani, ma hanno un significato diverso). Alcuni dei principali sono:

Vorrei suggerire alcuni *false friend* da aggiungere alla lista…

___
## Aggiornamenti per la seconda bozza
- [x] Espandere il glossario con termini linguistici ricorrenti nella guida, es, “calchi lessicali”. (gialloporpora)
- [x] Aggiungere "traducente" al glossario (Mte90)

**Comment by gialloporpora** [comment]
Io non sono esperto di questioni grammaticali e linguistiche in genere, però nell'Introduzione potremo ampliare il Glossario terminologico usato nel resto del libro inserendo anche qualche termine più legato alla terminologia puramente linguistica e non informatica, tipo:
http://blog.terminologiaetc.it/2009/02/27/prestiti-e-calchi-in-italiano/

da che mi sembra di capire che , anche in relazione al capitolo 2, quando non traduciamo, a voler usare il termine preciso, stiamo prendendo in prestito il vocabolo inglese, senza adattamenti, almeno nell'informatica a me non me ne vengono (a parte forse performante che non so se sia buon italiano o meno) e twittare che viene adattato da tweetare.

**Comment by kitsunenosaraT** [comment]
Hai ragione, come glossario è molto scarso. Devo fare una bella cernita dei termini linguistici che utilizziamo nella guida e arricchirlo. Il tuo link sarà molto utile per le definizioni.

**Comment by kitsunenosaraT** [comment]
I suggerimenti sono stati implementati nella pull request #77 
Nuovo issue per commentare la seconda versione dell'introduzione > #85
