### ISSUE TITLE
Weekly Translation of Pontoon Projects (Week 40–43/2024)

### ISSUE THREAD

**Issue by flodolo** [MozillaItalia/Mozilla-Italia-l10n-guide#381]
# Stringhe della settimana

| Nome progetto (e identificativo stringhe) | Numero stringhe | Traduttore `@username` | QA richiesto |  In revisione | Approvato |
| :-- | :-: | :-- | :-: | :-: | :-: |
| Common Voice | [22](https://pontoon.mozilla.org/it/common-voice/all-resources/?status=missing,pretranslated&string=310697) | @ni-kozen | ✅ | ✅ | ✅ |
| Thunderbird | [33](https://pontoon.mozilla.org/it/thunderbirdnet/all-resources/?status=missing,pretranslated&string=311176) | @JennyDC2020 |  ✅ | ✅  | ✅  |

❗️  La lista delle stringhe da tradurre viene aggiornata più volte nell'arco della settimana

❕ I seguenti progetti non sono gestiti dal team L10n. **NON** includerli nella lista delle stringhe:
- Seamonkey (responsabile: Iacopo Benesperi)
- SUMO (responsabile: Team SuMo)
- Firefox (sola lettura)

## Informazioni sul progetto
Questo issue serve a gestire le traduzioni dei siti Mozilla sulla piattaforma [Pontoon](https://pontoon.mozilla.org/it/).

Ogni settimana uscirà un nuovo issue con una lista dei progetti che contengono stringhe mancanti. Puoi sempre trovare lo issue della settimana corrente sulla [bacheca del progetto](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/projects/5).
Chi vuole farsi avanti, a seconda della propria disponibilità, si "prenoterà" per le stringhe.
Questo per organizzare meglio l'attività di traduzione ed evitare che più persone lavorino sulle stesse stringhe.

#### Prima di iniziare:
* [Registrati](https://accounts.firefox.com/oauth/signin?response_type=code&scope=profile%3Auid%20profile%3Aemail%20profile%3Adisplay_name%20profile%3Auid%20profile%3Adisplay_name%20profile%3Aemail&state=yrvTUh3o4F4c&redirect_uri=https%3A%2F%2Fpontoon.mozilla.org%2Faccounts%2Ffxa%2Flogin%2Fcallback%2F&client_id=76ab66239b5585ad) sulla piattaforma di traduzione Pontoon
  - (Facoltativo) Installa i componenti aggiuntivi [Pontoon Add-on](https://addons.mozilla.org/it/firefox/addon/pontoon-tools/) per ricevere le notifiche sulle stringhe mancanti in tempo reale (più altre chicche) e [MozIta L10n Add-on](https://addons.mozilla.org/it/firefox/addon/mozita-l10n/) per accedere più facilmente ai caratteri speciali come `’ “ ” È` ecc.
* **Leggi i capitoli della guida**, se lo desideri, lascia un feedback nel relativo issue:
  - Capitolo 1 – [Buone norme di traduzione tecnica](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/1-Buone_norme_di_traduzione.md) Feedback: issue #225 
  - Capitolo 2 – [Linee guida di Mozilla Italia](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/2-Linee_guida_di_Mozilla_Italia.md) Feedback: issue #138
  - Capitolo 3 – [Flusso di lavoro](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/3-Flusso_di_lavoro.md) Feedback: issue #24 
  - Capitolo 4 – [Tipi di file](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/4-Tipi_di_file.md) Feedback: issue #31 
  - Capitolo 5  – [Risorse esterne](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/5-Risorse_esterne.md) Feedback: issue #36

#### Prendere in carico il progetto:
* Lascia un messaggio nella sezione Commenti, scrivendo di quale progetto vuoi occuparti (importante per avvisare gli altri che ci stai lavorando tu). Scrivi anche il tuo nome utente accanto al nome del progetto sulla lista qui in alto (usa l'icona `…` nell'angolo in alto a destra per modificare il testo.)
  - Se non sei ancora tra i [Collaborators](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/settings/collaboration) non hai i permessi per modificare la lista. Scrivi solo nei commenti, qualcuno con i permessi aggiungerà il tuo nome alla lista.
* Attieniti alle istruzioni del [capitolo 3](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/3-Flusso_di_lavoro.md) e del [capitolo 4](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/4-Tipi_di_file.md).
* Per qualsiasi problema o domanda scrivi pure in questo issue.
* Quando la tua traduzione è pronta, lascia un commento nello issue per dare l'OK al QA.
* Rimani a disposizione per il QA, ti verrà chiesto se vuoi confermare le modifiche del revisore o proporre un'alternativa.
* e buona traduzione! 🎊 

##### Alcune norme comportamentali da seguire
1. Non usare lo issue per discussioni fuori tema, conversazioni personali, battute umoristiche ecc. (per cui sono disponibili appositi gruppi Telegram e sezioni del forum).
2. Non usare la `@menzione` quando non strettamente necessario, in particolare non menzionare uno o tutti i revisori ogni volta che chiedi il QA (a meno che non desideri il parere di quel revisore specifico).
3. Puoi prenotarti per i progetti a seconda della tua disponibilità, ma ricorda di lasciare anche agli altri volontari occasione di partecipare.
4. Puoi (anzi sei incoraggiato a) aggiornare la lista di stringhe presenti nello issue se noti che sono apparse nuove stringhe su Pontoon e desidera tradurle.
5. Puoi prendere anche solo una parte delle stringhe di un progetto, secondo la tua disponibilità. Basta che inserisci una casella di spunta con rientro `<spazio><spazio>- [ ]` nella riga sotto il progetto in questione, scrivendo accanto il tuo nome e il numero di stringhe che prendi.

## Link Utili
* Server di test -- Per vedere dove andranno a finire le tue traduzioni
  - per le singole pagine di [mozilla.org](https://l10n.mozilla-community.org/langchecker/?action=listpages) 
  - per [AMO](https://addons-dev.allizom.org/it/)
  - per [MDN](https://developer.allizom.org/it/)
  - per [Common Voice](https://voice.allizom.org/it)
  - per [Thunderbird.net](https://www.thunderbird.net/it/) *sito produzione
  - per [Firefox Monitor](https://fx-breach-alerts.herokuapp.com/) + [Modelli email](https://fx-breach-alerts.herokuapp.com/email-l10n)
  - per [Mozilla Donate website](https://donate-wagtail.mofostaging.net/it/) + [Istruzioni test pagamenti](https://groups.google.com/forum/#!topic/mozilla.dev.l10n.web/aEWu_hSnYMU)
* Motori di ricerca per le stringhe
  - [Pontoon: tutti i progetti](https://pontoon.mozilla.org/it/all-projects/all-resources/?utm_source=pontoon-addon&string=66616) -- Cerca simultaneamente tra tutti i progetti di Pontoon in italiano.
  - [Transvision](https://transvision.mozfr.org/) -- Motore di ricerca esterno per le stringhe Mozilla, complementare a Pontoon.
  - [Microsoft Language Portal](https://www.microsoft.com/en-us/language/Search?langID=408&Source=true&productid=0) -- Glossario Microsoft.
* [Transvision Access Key](https://transvision.mozfr.org/accesskeys/) -- Rileva eventuali errori nelle access key (da controllare ogni volta che si traduce una stringa contenente access key)
* [Sezione Localization in Discourse](https://discourse.mozilla.org/c/l10n/547) -- Sezione dedicata alla localizzazione dei prodotti Mozilla.
* [#l10n-community in Matrix](https://chat.mozilla.org/#/room/#l10n-community:mozilla.org) -- Sezione dedicata alla comunità di localizzatori Mozilla su Matrix.

**Comment by ni-kozen** [comment]
Mi prenoto per CV 😊

**Comment by ni-kozen** [comment]
Credo che le stringhe siano state eliminate

**Comment by flodolo** [comment]
> Credo che le stringhe siano state eliminate

Confermo 🤦🏼 

Vediamo se riappaiono settimana prossima.

**Comment by michrogit** [comment]
Sembra che sia sopravvissuta [una stringa](https://pontoon.mozilla.org/it/common-voice/all-resources/?status=missing,pretranslated&string=310697)…

**Comment by michrogit** [comment]
@flodolo, sono arrivate 16 stringhe "pretranslated" per Sumo. Ho lasciato [9 stringhe](https://pontoon.mozilla.org/it/sumo/all-resources/?status=missing,pretranslated&string=310813) in sospeso con suggerimenti di traduzione e commenti per dubbi vari… Quando hai qualche minuto libero, riusciresti a dargli un'occhiata e approvare (le eventuali stringhe approvabili) o proporre delle eventuali correzioni/alternative?

**Comment by flodolo** [comment]
@ni-kozen sembrano che le stringhe di CV siano resuscitate

**Comment by ni-kozen** [comment]
Traduzione finita, però ho dei dubbi su queste espressioni:

- `Small batch` / `Bulk batch`: "Blocco" (di frasi)? Altrimenti "gruppo", "set", "serie"... E poi "di piccole / grandi dimensioni", oppure qualcosa di più corto?
- `{ $uploadedSentences } of 1 sentence collected`: ho messo "{ ... } frase raccolta su 1", però effettivamente il singolare funziona solo con 1 ("1 frase") e non con 0 ("0 frasi").

**Comment by flodolo** [comment]
> * `Small batch` / `Bulk batch`: "Blocco" (di frasi)? Altrimenti "gruppo", "set", "serie"... E poi "di piccole / grandi dimensioni", oppure qualcosa di più corto?

Lotto? Non che mi suonino particolarmente bene.

> * `{ $uploadedSentences } of 1 sentence collected`: ho messo "{ ... } frase raccolta su 1", però effettivamente il singolare funziona solo con 1 ("1 frase") e non con 0 ("0 frasi").

In Italiano, "one" è usato solo per "1", "other" è usato per 0 e >1.

Approvato il resto, 4 da rivedere.

**Comment by ni-kozen** [comment]
> Lotto? Non che mi suonino particolarmente bene.

OK, ci sta. "Lotto in blocco" suona un po' strano, ma si dovrebbe capire 🙂

> In Italiano, "one" è usato solo per "1", "other" è usato per 0 e >1.

Ah sì, giusto. Grazie!

**Comment by flodolo** [comment]
> OK, ci sta. "Lotto in blocco" suona un po' strano, ma si dovrebbe capire 🙂

Stesso dubbio, ma sembra che ci siano risultati per "lotti in blocchi" (mi chiedo se siano traduzioni automatiche).

**Comment by ni-kozen** [comment]
Ripensandoci, forse la traduzione suggerita in italiano comunque non funziona per quel tipo di stringhe: [[1]](https://pontoon.mozilla.org/it/common-voice/all-resources/?string=310833) e [[2]](https://pontoon.mozilla.org/it/common-voice/all-resources/?string=310828).

O almeno non funziona nel caso di "1 frase raccolta su X" (X>1) perchè ho spostato "sentence" rispetto alla posizione in inglese, che si riferiva alle frasi totali.
Però, anche ripristinando l'ordine originale dall'inglese "1 su X frasi" ci sarebbe comunque il problema che "raccolta/e" in italiano cambia a seconda del numero.

> In Italiano, "one" è usato solo per "1", "other" è usato per 0 e >1.

Però "one" e "other in queste stringhe si riferiscono a `{ $totalSentences }`, giusto?
Se sì, "0 frase/i raccolte/e su 1" farebbe comunque parte della prima opzione.

Spero di essere stata abbastanza chiara 😅

**Comment by flodolo** [comment]
```
small-batch-response-message =
    { $totalSentences ->
        [one] { $uploadedSentences } frase raccolta su 1. Fai clic <downloadLink>qui</downloadLink> per scaricare le frasi rifiutate.
       *[other] { $uploadedSentences } frasi raccolte su { $totalSentences }. Fai clic <downloadLink>qui</downloadLink> per scaricare le frasi rifiutate.
    }
```

Al momento, quello che determina la forma del plurale è `$totalSentences`, per cui la traduzione non funziona 🤔 
Peraltro, come fanno a esserci frasi rifiutate se ne è stata raccolta 1 su 1?

Non è un granché in italiano, ma l'unica che funziona è

```
small-batch-response-message =
    { $totalSentences ->
        [one] { $uploadedSentences } frase raccolta. Fai clic <downloadLink>qui</downloadLink> per scaricare le frasi rifiutate.
       *[other] { $uploadedSentences } di { $totalSentences } frasi raccolte. Fai clic <downloadLink>qui</downloadLink> per scaricare le frasi rifiutate.
    }
```

**Comment by ni-kozen** [comment]
Scusa per l'attesa 😢

> Al momento, quello che determina la forma del plurale è `$totalSentences`, per cui la traduzione non funziona 🤔 Peraltro, come fanno a esserci frasi rifiutate se ne è stata raccolta 1 su 1?

Solo nel caso di "0 frasi raccolte su 1".

> Non è un granché in italiano, ma l'unica che funziona è
> 
> ```
> small-batch-response-message =
>     { $totalSentences ->
>         [one] { $uploadedSentences } frase raccolta. Fai clic <downloadLink>qui</downloadLink> per scaricare le frasi rifiutate.
>        *[other] { $uploadedSentences } di { $totalSentences } frasi raccolte. Fai clic <downloadLink>qui</downloadLink> per scaricare le frasi rifiutate.
>     }
> ```


Il problema è che ci possono essere "1 frase (raccolta)" oppure "0 / 2+ frasi (raccolte)" sia nel caso di `[one]` che di `[other]` `{ $totalSentences }`.
- `[one]`: 0 frasi raccolte su 1, 1 frase raccolta su 1
- `[other]`: 0 / 2+ frasi raccolte su n, 1 frase raccolta su n

**Comment by ni-kozen** [comment]
Si potrebbe magari spostare "frasi raccolte" all'inizio e lasciarlo in plurale?
- `[one]`: Frasi raccolte: `{ $uploadedSentences }` / `{ $totalSentences }` (0/1, 1/1)
- `[other]`: Frasi raccolte: `{ $uploadedSentences }` / `{ $totalSentences }` (0/n, 1/n, 2+/n)

**Comment by flodolo** [comment]
Possiamo rimuovere il plurale e usare sempre `{ $uploadedSentences } di { $totalSentences } frasi raccolte` (0 di 1, 1 di 1, 0 di 2, 1 di 2, ecc.).

**Comment by ni-kozen** [comment]
> Possiamo rimuovere il plurale e usare sempre `{ $uploadedSentences } di { $totalSentences } frasi raccolte` (0 di 1, 1 di 1, 0 di 2, 1 di 2, ecc.).

Scusa, non ho capito perché dici "rimuovere il plurale".

**Comment by flodolo** [comment]
Passare da 

```
small-batch-response-message =
    { $totalSentences ->
        [one] { $uploadedSentences } frase raccolta. Fai clic <downloadLink>qui</downloadLink> per scaricare le frasi rifiutate.
       *[other] { $uploadedSentences } di { $totalSentences } frasi raccolte. Fai clic <downloadLink>qui</downloadLink> per scaricare le frasi rifiutate.
    }
```

a

```
small-batch-response-message = { $uploadedSentences } di { $totalSentences } frasi raccolte. Fai clic <downloadLink>qui</downloadLink> per scaricare le frasi rifiutate.
```

**Comment by ni-kozen** [comment]
Ah OK. Sì, tanto la distinzione che c'è nell'originale in italiano non aiuta.
Risulta comunque in alcuni casi "1 frasi raccolte", ma se pensi sia accettabile va bene!

**Comment by flodolo** [comment]
Con 1 risulterebbe "1 di 1 frasi raccolte", che non è ideale ma è corretto in italiano.

**Comment by flodolo** [comment]
Aggiunte 33 stringhe per thunderbird.net

**Comment by JennyDC2020** [comment]
Le [33 stringhe](https://pontoon.mozilla.org/it/thunderbirdnet/all-resources/?status=missing,pretranslated&string=311176) di Thunderbird sono pronte per il QA!
😸

**Comment by JennyDC2020** [comment]
> QA pronto, 

Accetto tutti i tuoi suggerimenti 🤝😃 

> più complicate di quello che pensavo.

Assolutamente!!!

**Comment by flodolo** [comment]
Aperta nuova issue #382 , a quanto pare ci sono 105 stringhe per thunderbird.net 🙄
