### ISSUE TITLE
Translating MDN – HTML attribute: `<strong>`

### ISSUE THREAD

**Issue by kitsunenosaraT** [MozillaItalia/Mozilla-Italia-l10n-guide#51]
Per i volontari interessati a cimentarsi nella traduzione di un articolo di Mozilla Developer Nework, ecco un breve articolo che spiega la funzione dell’attributo HTML `<strong>`

## Informazioni sul progetto
**URL** https://developer.mozilla.org/it/docs/Web/HTML/Element/strong
**URL traduzione: **
**Formato di file** markup wiki (testo con tag)
**Strumenti** a scelta tra [interfaccia di traduzione MDN](https://developer.mozilla.org/) (online) / editor di testo semplice / [OmegaT](http://omegat.org/) (offline)

**Progresso:**
  -  [ ] Pronto per la revisione
  -  [ ] Pronto per la pubblicazione

### Prima di iniziare
- Crea un account GitHub (se non lo hai già): ti servirà sia per scrivere in questo issue, sia per accedere a MDN
  - (Facoltativo) Installa il componente aggiuntivo [MozIta L10n Addons] (https://addons.mozilla.org/it/firefox/addon/mozita-l10n-addons/) per accedere più facilmente ai caratteri speciali come `’ “ ” È` ecc.
- Leggi "[Come tradurre le pagine di MDN](https://developer.mozilla.org/it/docs/MDN/Contribute/Localize/Translating_pages)"

- Leggi i capitoli della guida. Se lo desideri, lascia un feedback nel relativo issue:
  - Capitolo 1 – [Buone norme di traduzione tecnica](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/1-Buone_norme_di_traduzione.md) Feedback: issue #91 
  - Capitolo 2 – [Linee guida di Mozilla Italia](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/2-Linee_guida_di_Mozilla_Italia.md) Feedback: issue #138
  - Capitolo 3 – [Flusso di lavoro](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/3-Flusso_di_lavoro.md) Feedback: issue #24 
  - Capitolo 4 – [Tipi di file](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/4-Tipi_di_file.md) Feedback: issue #31 
  - Capitolo 5  – [Risorse esterne](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/5-Risorse_esterne.md) Feedback: issue #36 

#### Prendere in carico il progetto
* Se non lo hai già fatto, [registra un account gratuito su GitHub](https://github.com/join?source=header-home)
* Scrivi nell’area commenti qui di seguito che vuoi occuparti di questo progetto
* Accedi a [MDN](https://developer.mozilla.org/) con il tuo account GitHub
* Attieniti alle [istruzioni per MDN del capitolo 3](https://github.com/kitsunenosaraT/Mozilla-Italia-l10n-guide/blob/master/it/3-Flusso_di_lavoro.md#mdn) e ai suggerimenti del resto della guida, in particolare [i consigli pratici del capitolo 2](https://github.com/kitsunenosaraT/Mozilla-Italia-l10n-guide/blob/master/it/2-Linee_guida_di_Mozilla_Italia.md#consigli-pratici)
* per qualsiasi problema o domanda scrivi pure in questo issue
* e buona traduzione! 🎊 

## Link Utili
* Motori di ricerca per la terminologia
  - [Pontoon: tutti i progetti](https://pontoon.mozilla.org/it/all-projects/all-resources/?utm_source=pontoon-addon&string=66616) -- Per gli elementi UI, le funzioni e altra terminologia dei prodotti Mozilla.
  - [Transvision](https://transvision.mozfr.org/) -- Motore di ricerca esterno per i software e i siti  Mozilla, complementare a Pontoon.
  - [Microsoft Language Portal](https://www.microsoft.com/en-us/language/Search?langID=408&Source=true&productid=0) -- Per gli elementi UI, le funzioni e altra terminologia dei prodotti Microsoft.

❗️ **N.B.** Per segnalare la traduzione di un nuovo articolo utilizzare lo issue indice #217.

**Comment by VaiTon** [comment]
Posso occuparmi io di questa pagina?

**Comment by kitsunenosaraT** [comment]
È un progetto vecchio pensato per l'Hacktoberfest, ma se ti interessa, volentieri 👍 
Aspetta che lo ricatalogo sotto il nuovo progetto della traduzione di MDN…

**Comment by kitsunenosaraT** [comment]
*Et voilà*, ti ho inserito nell'indice degli articoli di MDN in traduzione nello issue #217.

Adesso aggiungo nel primo messaggio di questo issue alcuni link che potrebbero esserti utili.
Inizia quando vuoi e tienici aggiornati. Buon divertimento! 😁

**Comment by kitsunenosaraT** [comment]
**Avviso**: a causa di varie esigenze di mantenimento della piattaforma MDN, è stata presa la decisione di interrompere il supporto per la localizzazione della maggior parte delle lingue, compreso l'italiano.
Gli articoli già tradotti rimarranno visualizzabili sulla piattaforma in modalità di sola lettura, ma non sarà più possibile tradurre nuovi articoli. [Ulteriori informazioni](https://hacks.mozilla.org/2020/10/mdn-web-docs-evolves-lowdown-on-the-upcoming-new-platform/).
Più informazioni nello issue #217
