### ISSUE TITLE
Translating articles for mozillaitalia.org blog

### ISSUE THREAD

**Issue by kitsunenosaraT** [MozillaItalia/Mozilla-Italia-l10n-guide#59]
Benvenuti!
Questo issue è dedicato alla traduzione in italiano di articoli provenienti dai blog Mozilla, ed è aperto a tutti i volontari che vorranno contribuire.
Gli articoli tradotti verranno pubblicati sul blog di [Mozilla Italia](https://www.mozillaitalia.org/home/).

## Articoli da tradurre (in aggiornamento)
- [x] [Firefox Memory Usage in the Quantum Era](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/articoli/firefox-quantum-utilizzo-memoria.md) (Assegnato a @Sav22999)
- [ ] [Start Your Engines – Firefox Quantum Lands in Beta, Developer Edition](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/articoli/la-rivoluzione-quantum.md)
- [x] [10 Fascinating Things We Learned When We Asked The World How Connected Are You?](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/articoli/10-Fascinating-Things-We-Learned-When-We-Asked-The-World.md) (assigned to @Sav22999)

### Prima di iniziare:
* (Facoltatitvo) Presentati nello Issue #20 Introduction (Presentazioni)
* (Facoltativo) Rispondi a un breve sondaggio nello Issue #7 Survey on volunteers preferences and expectations
* **Leggi i capitoli della guida** e, se lo desideri, lascia un feedback nel relativo issue:
  - Capitolo 1 – [Buone norme di traduzione tecnica](https://github.com/kitsunenosaraT/Mozilla-Italia-l10n-guide/blob/master/it/1-Buone_norme_di_traduzione.md) Feedback: issue #23 
  - Capitolo 2 – [Linee guida di Mozilla Italia](https://github.com/kitsunenosaraT/Mozilla-Italia-l10n-guide/blob/master/it/2-Linee_guida_di_Mozilla_Italia.md) Feedback: issue #27 
  - Capitolo 3 – [Flusso di lavoro](https://github.com/kitsunenosaraT/Mozilla-Italia-l10n-guide/blob/master/it/3-Flusso_di_lavoro.md) Feedback: issue #24 
  - Capitolo 4 – [Tipi di file](https://github.com/kitsunenosaraT/Mozilla-Italia-l10n-guide/blob/master/it/4-Tipi_di_file.md) Feedback: issue #31 
 - Capitolo 5 -- [Risorse esterne](https://github.com/kitsunenosaraT/Mozilla-Italia-l10n-guide/blob/master/it/5-Risorse_esterne.md) Feedback issue #36 

### Prendere in carico il progetto
* Scrivi nei commenti di questo issue quale articolo hai scelto
* Crea un fork del repository (pulsante in alto a destra). Adesso hai una copia di questo repo su cui puoi lavorare su https://github.com/tuo nome utente 🎉 
(se vuoi approfondire, leggi questa semplice guida su [come contribuire a GitHub](https://guides.github.com/activities/forking/))
### Tradurre l'articolo
* Vai all'articolo nella tua copia del repository e premi l'icona della matita in alto a destra per modificarlo
* Sovrascrivi al testo la tua traduzione. Cerca di tradurre attenendoti il più possibile alla guida di localizzazione:
  - Cura grammatica, ortografia e punteggiatura.
  - Ricerca i termini e i nomi di prodotti e tecnologie che non conosci. 
  - Per quanto riguarda i termini dell'interfaccia dei prodotti o delle iniziative Mozilla, controlla come sono stati resi ufficialmente in italiano utilizzando la [Barra di ricerca Machinery](https://screenshots.firefox.com/FsPaDkVI9aWXJwl1/pontoon.mozilla.org) in [Pontoon](https://pontoon.mozilla.org/it/amo/LC_MESSAGES/djangojs.po/?string=66616) o il plugin di ricerca [Mozilla Transvision](https://transvision.mozfr.org/)
    - 💡  Preferisci lavorare offline? Copia il contenuto dell'articolo nel tuo editor di testo preferito, traducilo con calma. Quando hai finito, copia-incolla la traduzione nel file su GitHub
* **Piccola guida al linguaggio di GitHub**:
   - Ogni volta che premi il pulsante *Commit* equivale a *Salva* sul computer. Se traduci l'articolo a più riprese, ricordati di salvare il tuo lavoro per non perderlo. A ogni commit GitHub ti dà la possibilità di includere un messaggio sulla versione che stai salvando (es. "prima stesura", "correzioni" ecc.)
  - i commit salvano il file solo sulla tua copia locale, il repository originali non ne viene influenzato. Quando sei pronto a sottoporre il tuo articolo alla revisione, cerca il pulsante *Compare & pull request* per inviare una proposta delle tue modifiche al repository centrale. Devi dare un "titolo" alla tua pull request: usa "Traduzione *titolo articolo*" o simili, così sarà più facile individuare il tuo contributo.
* attendi che la tua traduzione venga sottoposta revisione (QA) ed eventualmente correggi le parti che ti sono state segnalate con un nuovo commit.
* **per qualsiasi problema o domanda riguardo al funzionamento di GitHub o alla traduzione in sé, scrivi pure in questo issue, non ti abbandoneremo!**
* e buona traduzione! 🎊

---
## ATTENZIONE
Questo issue fa parte dell'iniziativa #hacktoberfest.
### Cos'è l'Hacktoberfest?
Hacktoberfest ([sito ufficiale](https://hacktoberfest.digitalocean.com/)) è un'iniziativa globale che ha luogo dal 1 al 31 ottobre su GitHub.
Il suo scopo è promuovere lo sviluppo dell'Open Source incoraggiando tutti gli utenti di GitHub a curiosare nei repository altrui e dare il proprio contributo a nuovi progetti.
### Come posso partecipare?
1. Registra un account gratuito su [GitHub](https://github.com/) (se non lo possiedi già)
2. Usa il tuo account GitHub per registrarti sul sito dell'[Hacktoberfest](https://hacktoberfest.digitalocean.com/sign_up/register)
3. Su GitHub cerca uno issue con il label #hacktoberfest su cui lavorare
4. Fai la tua pull request

Per il regolamento completo e ogni domanda, consulta il sito ufficiale di [Hacktoberfest](https://hacktoberfest.digitalocean.com/#details) (in inglese)
### Cosa ci guadagno?
La consapevolezza di aver dato una spinta alla causa dell'Open Source.
Ah, e sei fai almeno 4 pull request (4 in tutto, non solo per il nostro repository), a quanto pare vinci una maglietta collaborativa 👕 
💡 Controlla quante pull request hai già fatto per l'Hacktoberfest [qui](https://hacktoberfestchecker.herokuapp.com/) (grazie a @mte90 per l'informazione)

**Comment by Mte90** [comment]
Per gli articoli da tradurre potremmo fare un etherpad che manteniamo aggiornati con quelli dafere e quelli da valutare se tradurre.
In questo modo chiunque può mettere in coda nuovi articoli e partecipare nelel valutazioni.

**Comment by kitsunenosaraT** [comment]
Assolutamente necessario!
Però invece di usare una risorsa esterna come Etherpad, non sarebbe meglio usare la checklist di GitHub in cima allo issue? Come abbiamo fatto per lo issue #28 
E discutere nei commenti quali accettare e quali no.
Così rimane tutto nella stessa piattaforma.

**Comment by Mte90** [comment]
Ottima pensata, il dubbio è come segnalare nuovi articoli, se si commenta un ticket con un link solo poi ritrovarli diventa difficile.

**Comment by kitsunenosaraT** [comment]
Pensavo di mettere tutto in cima allo issue, diviso così:

**Articoli da tradurre**
- [ ] Art. 1 (se è assegnato, mettere X nella casella e il nome del traduttore tra parentesi)
- [ ] Art. 2
- [ ] Art. 3
___
**Articoli in triage**
- [ ] Art. 1 (con link all'articolo)
- [ ] Art. 2
- [ ] Art. 3

Questo in bella vista nel primo post dello issue. Poi nei commenti discutere della triage.
Può funzionare?

**Comment by Sav22999** [comment]
Salve a tutti.
Spero di aver capito bene, ovvero per poter collaborare nella traduzione bisogna "prenotarsi" qui.
Sono Saverio e vorrei tradurre "firefox-quantum-utilizzo-memoria.md", inizio se ricevo una vostra conferma.

**Comment by kitsunenosaraT** [comment]
Sei nel posto giusto, Saverio! :grinning:
Per tradurre l'articolo di tua scelta dovresti fare il fork (cioè copiare il repository sul tuo account) e poi lavorare sul file nella tua copia personale.

Stasera è un po' tardi, ma se hai dei dubbi su come fare questo passaggio possiamo sentirci domani e vedere tutto insieme!

**Comment by kitsunenosaraT** [comment]
@Sav22999 Se noti la lista in cima allo issue, ti ho riservato l'articolo! 👍 
Ti ho anche inviato una richiesta per diventare collaboratore ufficiale del repo...

In più ho aggiornato le istruzioni per GitHub su fork e pull request (sempre in cima allo issue).
Spero di essere stata chiara, ma se c'è qualche lacuna nella mia spiegazione non hai che da chiedere delucidazioni.

Un'ultima cosa: se vuoi che il tuo contributo venga annoverato nell'Hacktoberfest, ricordati di registrarti con le tue credenziali GitHub sul [sito](https://hacktoberfest.digitalocean.com/sign_up/register) (ci vuole un minuto).

Tienici aggiornati sui tuoi progressi, e buon lavoro!

**Comment by Sav22999** [comment]
@kitsunenosaraT Allora, sono andato sull'articolo in questione ed ho premuto "Fork".
Perfetto. Ora come dovrei procedere? Scusate la mia totale ignoranza..

**Comment by Sav22999** [comment]
@kitsunenosaraT Non so se è il luogo adatto, se non lo fosse indicami, per favore, dove dovrei inserire questo commento.
Dunque "Quantum Era" devo tradurlo o lasciarlo invariato? E' un nuovo termine, perciò, credo non dovrebbe avere variazioni per come leggi nelle linee guide. Tuttavia, magari potrebbe essere "Era Quantum".... Scusate e grazie

**Comment by kitsunenosaraT** [comment]
@Sav22999 
Il commento è nel posto giusto, non scusarti! (E non scusarti in ogni caso, anche se sbagliassi non succederebbe nulla di grave)

Quantum è il nome del progetto, come puoi anche vedere nel [glossario](https://transvision.mozfr.org/?recherche=Quantum&repo=mozilla_org&sourcelocale=en-US&locale=it&search_type=strings), quindi non si traduce.
"Quantum Era" è una "licenza poetica" dell'autore, un modo per dire che con Quantum inizia una nuova era per Firefox. Per questo la tua seconda opzione, "Era Quantum" oppure "era di Quantum" è la soluzione corretta 👍

**Comment by Sav22999** [comment]
@kitsunenosaraT Perfetto. Grazie mille, gentilissima.

**Comment by Sav22999** [comment]
Ragazzi, sono sempre io. Mannaggio, sono 10 minuti che sto cercando di capire come tradurre "quantum-ed" ma non ci sono riuscito... potete darmi una mano voi?

**Comment by Mte90** [comment]
Se sei su Telegram vieni su https://t.me/mozItaHUB che abbiamo il canale dei traduttori così puoi fare richieste dirtettamente li per queste cose :-)

**Comment by kitsunenosaraT** [comment]
Aspetta @Mte90 Per queste cose specifiche forse è meglio occuparcene qui, così abbiamo tutto nello stesso posto. Dopotutto le domande che vengono fuori ora potrebbero essere utili per il prossimo articolo.

@Sav22999 puoi riportare qui nei commenti la frase che stai cercando di tradurre per intero + il tuo tentativo di traduzione?

**Comment by Sav22999** [comment]
@Mte90  non ho trovato alcun link per il canale telegram dei "localizzatori"...

**Comment by Mte90** [comment]
Va bene il mio era un suggerimento per non avere un ticket con del contenuto off topic con il contesto (su github non è come nel forum che puoi spostare i messaggi).
Su telegram entra in voglio diventare un volontario e poi ti aggiungiamo in l10n.

**Comment by Sav22999** [comment]
@kitsunenosaraT Certo. **We’ve <a href="https://wiki.mozilla.org/Quantum">quantum-ed all the things</a> but we haven’t really talked about memory usage**, **Noi abbiamo <a href="https://wiki.mozilla.org/Quantum">QUANTUM-ED tutte le cose</a> ma non abbiamo veramente parlato dell'uso della memoria** (quantum-ed non so come tradurlo... ho cercato anche su Transvision...)
@Mte90 sono già nel gruppo "voglio diventare volontario"

**Comment by kitsunenosaraT** [comment]
@Mte90 Capisco, è solo che non vorrei spalmare il contenuto su tanti canali diversi, perché poi diventa difficile da seguire/andarsi a ricercare un'informazione.
Secondo te sarebbe più ordinato tenere questo issue solo per la proposta di nuovi articoli e per ogni articolo da tradurre fare uno issue a parte? Io stavo giusto pensando se valeva la pena aprire uno issue per ogni articolo 🤔 

@Sav22999  Perfetto!
Allora, qui abbiamo una delle caratteristiche più affascinanti/frustranti della lingua inglese, cioè trasformare i sostantivi in verbi.

Il significato dietro tutta questa frase è che la tecnologia Quantum ha influenzato tutti gli aspetti e le prestazioni di Firefox.
Volendo essere ultra-letterale, potresti seguire l'esempio dell'autore e coniare un verbo in italiano
>es. Abbiamo *quantumizzato* tutto quanto

Tuttavia questo è un articolo di una certa serietà, per cui è meglio adottare uno stile più sobrio.

La cosa migliore da fare è abbandonare l'idea di una traduzione letterale e cercare di rendere il senso con una perifrasi.
Ecco alcuni esempi che potrebbero starci bene (ma sei libero di inventarne di tuoi):
> Quantum ha influenzato/pervaso/migliorato le prestazioni di Firefox sotto numerosi aspetti, ma tra questi non abbiamo ancora discusso del consumo di memoria

**Comment by Mte90** [comment]
@kitsunenosaraT L'idea di un ticket per ogni articolo sul repo degli articoli non mi sembra una idea sbagliata in questo modo il flusso non si disperde.

Puoi cancellare tutti i miei messaggi fuori posto per pulire questo ticket :-)

@Sav22999 Allora ti aggiungo su L10N su telegram :-)

**Comment by kitsunenosaraT** [comment]
>@kitsunenosaraT L'idea di un ticket per ogni articolo sul repo degli articoli non mi sembra una idea sbagliata in questo modo il flusso non si disperde.

@gialloporpora che ne pensi di questa idea? Potremmo comunque tenere un po' d'ordine utilizzando la pagina dei progetti.

**Comment by Sav22999** [comment]
@kitsunenosaraT Nelle linee guida c'è scritto che devo utilizzare al posto degli apostrofi, delle virgolette, ecc i dei caratteri specifici. Anche su GitHub devo usare questa procedura?

**Comment by kitsunenosaraT** [comment]
Nei testi scritti nei file sì (particolarmente se sono in HTML).
Nei commenti tra noi come questi non ti disturbare, usa pure quelli dritti che sono più veloci.

**Comment by Sav22999** [comment]
@kitsunenosaraT  @Mte90  Volevo avvisare tutti che ho terminato di tradurre il file. Lo so, è pieno di errori... ho cercato di fare del mio meglio.
Ci ho messo un'eternità nel tradurre l'articolo, ma spero, comunque, non sia stato un lavoro completamente inutile... che dire, volevo solamente avvisarmi in modo tale che possiate verificare la correttezza o meno della pagina e così facendo correggendo gli eventuali errori (o, per lo meno, segnalandomeli).
Buona serata a tutti ragazzi.

**Comment by kitsunenosaraT** [comment]
@Sav22999 Grazie per aver dedicato la domenica al nostro articolo su Quantum!
Hai fatto il fork e modificato il file dell'articolo in modo corretto, ma adesso devi fare un ultimo passaggio…
Finora hai lavorato sulla tua copia del repository. Ora devi fare la famosa **pull request** per chiedere di immettere le tue modifiche nel repository principale (è un pulsante verde in alto nella pagina).
Da lì potremmo segnalarti le eventuali modifiche.

**Comment by Sav22999** [comment]
@kitsunenosaraT non riesco a trovare il pulsante.... E se vado in "Pull requeest", quindi creando "New pull request" non mi mostra niente, solo qualcosa tino "master"

**Comment by kitsunenosaraT** [comment]
>creando "New pull request" non mi mostra niente, solo qualcosa tino "master

Potresti farmi uno screenshot di questa schermata della pull request? Quando hai tempo, naturalmente.

**Comment by Sav22999** [comment]
@kitsunenosaraT Ecco
![capture _2017-10-09-12-33-27](https://user-images.githubusercontent.com/32335378/31334322-26658786-acee-11e7-8b75-7cad76468e4a.png)

**Comment by kitsunenosaraT** [comment]
Grazie, perfetto!
Vedo che tu stai cercando di fare la pull request dal repository MozillaItalia.
Però tu la traduzione dell'articolo ce l'hai sul **tuo** repository, indi per cui la tua richiesta dovrebbe partire da https://github.com/Sav22999/Mozilla-Italia-l10n-guide
Ripeti la procedura da lì, vedrai che la pull request verrà abilitata. :+1:

**Comment by kitsunenosaraT** [comment]
@Sav22999 
Indovina chi è sulla home page di Mozilla Italia di oggi… 
🎊 [Firefox nell'era Quantum: utilizzo della memoria](https://www.mozillaitalia.org/home/2017/10/13/firefox-nellera-quantum-utilizzo-della-memoria/) 🎊 
L'articolo è anche stato condiviso sui nostri social grazie a @gialloporpora 
@flodolo ha ancora fatto qualche piccolo ritocco qua e là prima di pubblicare.
Congratulazioni! 😄

**Comment by Sav22999** [comment]
@kitsunenosaraT grazie mille! È veramente emozionante!! *.*

**Comment by Sav22999** [comment]
@kitsunenosaraT ma qui nessuno si è prenotato?? Potrei farlo io per le "10 things ..."?

**Comment by kitsunenosaraT** [comment]
@Sav22999 è tutto tuo 👌
Ti consiglio di leggeeti anche la breve indagine a cui si rifà l'articolo (la ho messa come nota all'inizio). Buon lavoro!

**Comment by Sav22999** [comment]
@kitsunenosaraT perfetto. Grazie mille. Si, le ho già lette nell'attesa di tua conferma/negazione 😂.

**Comment by Sav22999** [comment]
@kitsunenosaraT ho un problema... non riesco a creare il fork. Quando premo su fork mi manda al fork precedemente creato per firefox quantum, e non c'è l'articolo "10 things" perché è stato aggiunto in seguito... come posso aggiornare quel fork?

**Comment by Mte90** [comment]
Si non puoi avere due fork, devi aggiornare il precedente e per farlo devi farlo utilizzando un programma.
Se non sei pratico di linea di consiglio di scaricare github desktop https://desktop.github.com/

**Comment by flodolo** [comment]
Sono 3 righe se vuoi farlo via linea di comando, abbastanza un delirio se vuoi [farlo dall'interfaccia](https://www.youtube.com/watch?v=TsUIRtT80QU) :)

Se decidi di andare con la riga di comando, ti consiglio di dare un'occhiata  [a questo](https://flod.org/github/).

P.S. non mi risulta che GH desktop ti permetta di farlo in maniera più intuitiva?

**Comment by Sav22999** [comment]
Studio informatica (programmazione) con le CLI vado a braccetto :P certo, non conosco quelle di GitHub, per cui se conoscete delle risorse, potrei anche vedermele (ovviamente se me le indicate ve ne sono grato xD)

**Comment by flodolo** [comment]
Ottimo, allora lascia perdere quel video e desktop ;-)

1. Configurati SSH, niente user e password da digitare: https://help.github.com/articles/connecting-to-github-with-ssh/
2. Clonati il repository in locale facendo attenzione a utilizzare l'URL con SSH
3. L'idea è che cloni il tuoi fork in locale, aggiungi un *remote* (normalmente lo chiamo upstream) che punta al repository principale. 

L'approccio principale è: mai toccare master, questo deve rimanere sincronizzato con il repo principale. Crea branch nel tuo repository per lavorare, quando sei pronto apri una pull request verso il repository principale. Tieni i due master in sync.

Il documento là sopra dovrebbe avere tutte le informazioni che ti servono, se hai dubbi chiedi pure ;-)

**Comment by kitsunenosaraT** [comment]
Ehm, vedo che mentre io facevo i miei pasticci, altri sono intervenuti con dei consigli.
Però ci  sarebbe un modo per aggiornare il tuo fork senza installare programmi o usare la linea di comando.
Ti ho mandato una Pull request, dal repository centrale al tou fork personale. Se la accetti, tutta la roba nuova verrà copiata nel tuo repo.
Vedrai che c'è un "conflitto", l'articolo in questione che nel tuo repository non si trova.
Devi segnarlo come "mark as resolved", e poi puoi fare la pull request.
Guarda nel tuo fork, dovresti trovare la pull request con le mie istruzioni, e speriamo bene 🤞

**Comment by Sav22999** [comment]
@kitsunenosaraT Accetto la tua proposta così evito di creare disastri xD.

**Comment by Sav22999** [comment]
Ragazzi, stavo traducendo l'articolo delle "10 cose .." e non so se lasciare inviarato questo nome, su Transvision non c'è niente... e su google viene riportato proprio così. Chiedo consiglio anche a voi.
Il nome in questione è "fitness trackers" (ovviamente la "S" non ci starebbe in italiano)

**Comment by flodolo** [comment]
Non è decisamente un argomento che capita di frequente. Io sarei per lasciarlo in inglese, tutte le aziende sembrano usare "fitness/activity tracker" per promuovere i loro prodotti.

**Comment by Sav22999** [comment]
@flodolo Perfetto, grazie mille.
Posso chiederti consiglio anche per quanto riguarda "Smart Car" (macchina/auto intelligente sembra strano...).
Poi, se non chiedo troppo, non capisco al punto (4), alla fine dice "31% compared to the overall average of just 7%.", ma il 31% si riferisce a cosa? Perchè non ha specificato precedentemente uno Stato per cui pensavo stesse parlando in generale, ma poi dice questa frase... quindi credo si riferisca solo agli US e il 7% e nel mondo. Se puoi ed hai tempo, aiutami a comprendere per favore.

**Comment by kitsunenosaraT** [comment]
Confermo che nel [sondaggio](https://www.surveygizmo.com/s3/3643927/091fb5d9e0e1?sglocale=it) abbiamo lasciato Activity Tracker, mentre per Smart Car abbiamo usato Automobile con connessione ad Internet.

Quando chiedi qualcosa su una frase, è sempre meglio citarla.

>The more tech savvy people are, the more optimistic they feel about a connected future. People who identified as the least tech savvy are most likely to be “scared as hell” about our more connected future — 31% compared to the overall average of just 7%.

31% è la percentuale di utenti che hanno dichiarato di essere *scared as hell* nel gruppo di persone che si sono identificate come *least tech savvy*
7% è la percentuale di utenti che hanno dichiarato di essere *scared as hell* tra tutti quelli che hanno risposto al sondaggio.

In pratica il punto è che le persone non *tech savvy* sono mediamente le più spaventate.

**Comment by flodolo** [comment]
Visto il contesto, o lo lasci in inglese (in corsivo) oppure "automobili smart". Anche in questo caso, l'inglese sembra prevalente :-\

> People who identified as the least tech savvy are most likely to be “scared as hell” about our more connected future — 31% compared to the overall average of just 7%.

Il 31% delle persone che si identificano come non esperte sono terrorizzate da un futuro più connesso, paragonato alla media generale del 7%.

**Comment by flodolo** [comment]
Mi sono incrociato con Sara. Credo che "smart car" = "automobile connessa a Internet" sia molto limitante (pensa a una Tesla), è come chiamare uno smartphone moderno un cellulare ;-)

**Comment by Sav22999** [comment]
@kitsunenosaraT Hai ragione, volevo citarlo tutto ma poi ho pensato di evidenziare la frase che non riuscivo a comprendere indicando, comunque, il punto 4 dell'articolo.
@flodolo @kitsunenosaraT Quindi uso "smart car" o "automobile connessa ad Internet"? 😕

**Comment by kitsunenosaraT** [comment]
Vai con automobile *smart* 👍 
In effetti il trend sembra quello.

**Comment by Sav22999** [comment]
@kitsunenosaraT Spero di aver effettuato la pull request in modo corretto

**Comment by Sav22999** [comment]
@kitsunenosaraT Ma l'articolo delle "10 things"? Ancora non si sa niente?

**Comment by kitsunenosaraT** [comment]
Dovrebbe essere pubblicato a giorni, insieme alle traduzioni in altre lingue, sul blog Medium. Stiamo tenendo d'occhio il blog per informarti appena esce.

Visto che tanto l'hacktoberfest finisce oggi, a meno che non ti interessi in modo particolare il contenuto dell'articolo, preferrei che ci concentrassimo sulle stringhe di Pontoon.
Ps. Comunque ti ringrazio di cuore per aver partecipato con noi al nostro primo Hacktoberfest :pumpkin:

**Comment by Sav22999** [comment]
@kitsunenosaraT è stato un piacere partecipare. Dal momento che per il momento non c'è il nuovo issue (o non lo trovo nuovamente io!?) avrei potuto tradurre l'articolo. Ma non fa niente, se dici che non è importante lasvio perdere :) grazie per la consultazione quotidiana di quel blog :) gentilissimi

**Comment by kitsunenosaraT** [comment]
🎉 Ecco l'articolo sui risultati del sondaggio sull'Iot, pubblicato sul blog [Medium](https://medium.com/mozilla-internet-citizen/10-interessanti-scoperte-dal-sondaggio-quanto-sei-connesso-13ebaff39def) di Mozilla! Congratulazioni, @Sav22999 🎉 
ps. Nell'articolo è finita per sbaglio un'immagine con testo in francese, ma la cosa è già stata segnalata 😅

**Comment by Sav22999** [comment]
@kitsunenosaraT Perfetto! Grazie mille. L'articolo, con le immagini, è ancora più interessante xD

**Comment by gialloporpora** [comment]
Bisognerebbe anche condividerlo su FB e Twitter.
Complimenti anche da parte mia.

**Comment by Sav22999** [comment]
@kitsunenosaraT questo issue non credo sia chiuso (o no?)

**Comment by AndyUrbi** [comment]
@kitsunenosaraT 
Visto che l'articolo non verrà mai pubblicato è da chiudere anche questo issue?

**Comment by Sav22999** [comment]
@kitsunenosaraT, come aveva già proposto @AndyUrbi, è possibile chiudere questo issue?

**Comment by kitsunenosaraT** [comment]
Scusate, mi era sfuggito... per oltre un anno 😓 Ora chiudo!

Tra parentesi, non sono sicura di capire il commento:

> Visto che l'articolo non verrà mai pubblicato è da chiudere anche questo issue?

Come è scritto qualche post più in su, l'articolo è stato regolarmente pubblicato su [Medium](https://medium.com/mozilla-internet-citizen/10-interessanti-scoperte-dal-sondaggio-quanto-sei-connesso-13ebaff39def).
