### ISSUE TITLE
GitBook Integration

### ISSUE THREAD

**Issue by kitsunenosaraT** [MozillaItalia/Mozilla-Italia-l10n-guide#60]
A seguito della recente migrazione su Mozilla Italia, sto guardando un modo per far si che la guida appaia su GitBook sotto questo dominio, invece che sotto il mio personale.
A quanto pare c'è un modo per [cambiare il dominio](https://help.gitbook.com/books/can-i-use-custom-domain.html), però c'è bisogno di settare dei parametri DNS dal lato GitHub.

In alternativa (e non sarebbe male), si può collegare direttamente il repo a GitBook come hanno fatto @flodolo et al. per la [documentazione per localizzatori](https://github.com/mozilla-l10n/localizer-documentation) su mozilla-l10n.

Solo che non mi sembra di avere i privilegi per fare nessuna di queste due cose, passo la patata bollente a @Mte90 😓

**Comment by Mte90** [comment]
Per la questione DNS si  tratta di un sito vero e proprio e non possiamo farlo su github.
Probabilmente https://help.gitbook.com/github/how-can-i-export-to-repo.html

Forse la soluzione più semplice è fare un account mozillaitalia su gitbook e asscoiare questo repo.

**Comment by Mte90** [comment]
Ok ho creato un orgnaizzazione su gitbook, sto aggiungendo il manuale :-)

**Comment by Mte90** [comment]
Ecco qua https://mozillaitalia.gitbooks.io/l10n-guide/content/

**Comment by kitsunenosaraT** [comment]
Mitico @Mte90 ! 😮 
Mi  sembra tutto a posto. È stato più veloce e indolore del previsto!
Chiudo con piacere lo issue, adesso puoi finamente sostituire il link anche nella presentazione per la Libre Office Conference 👌
