### ISSUE TITLE
Weekly Translations of Pontoon Projects (week 14)

### ISSUE THREAD

**Issue by kitsunenosaraT** [MozillaItalia/Mozilla-Italia-l10n-guide#95]
# Stringhe della settimana
- [x] [Firefox Accounts](https://pontoon.mozilla.org/it/firefox-accounts/all-resources/?status=missing%2Cfuzzy%2Csuggested&string=177563)  14 stringhe - @Sav22999
- [x] [AMO Frontend](https://pontoon.mozilla.org/it/amo-frontend/all-resources/?status=missing%2Cfuzzy%2Csuggested&string=177582) 7 stringhe + 5 fuzzy - @eliogi
- [x] [AMO Frontend 2](https://pontoon.mozilla.org/it/amo-frontend/all-resources/?status=missing%2Cfuzzy%2Csuggested&string=177582) 5 fuzzy - @eliogi
- [x] [MDN](https://pontoon.mozilla.org/it/mdn/all-resources/?status=missing%2Cfuzzy%2Csuggested&string=177819) 2 fuzzy - @eliogi
## Informazioni sul progetto
Questo issue serve a gestire le traduzioni dei siti Mozilla sulla piattaforma [Pontoon](https://pontoon.mozilla.org/it/).

Ogni settimana uscirà un nuovo issue con una lista dei progetti che contengono stringhe mancanti. Puoi sempre trovare lo issue della settimana corrente sulla [bacheca del progetto](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/projects/5).
Chi vuole farsi avanti, a seconda della propria disponibilità, si "prenoterà" per le stringhe.
Questo per organizzare meglio l'attività di traduzione ed evitare che più persone lavorino sulle stesse stringhe.

#### Prima di iniziare:
* [Registrati](https://accounts.firefox.com/oauth/signin?response_type=code&scope=profile%3Auid%20profile%3Aemail%20profile%3Adisplay_name%20profile%3Auid%20profile%3Adisplay_name%20profile%3Aemail&state=yrvTUh3o4F4c&redirect_uri=https%3A%2F%2Fpontoon.mozilla.org%2Faccounts%2Ffxa%2Flogin%2Fcallback%2F&client_id=76ab66239b5585ad) sulla piattaforma di traduzione Pontoon
  - (facoltativo) Installa il componente aggiuntivo [Pontoon Tools](https://addons.mozilla.org/it/firefox/addon/pontoon-tools/) per ricevere le notifiche delle stringhe mancanti in tempo reale (più altre chicche)
* **Leggi i capitoli della guida**, se lo desideri, lascia un feedback nel relativo issue:
  - Capitolo 1 – [Buone norme di traduzione tecnica](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/1-Buone_norme_di_traduzione.md) Feedback: issue #91 
  - Capitolo 2 – [Linee guida di Mozilla Italia](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/2-Linee_guida_di_Mozilla_Italia.md) Feedback: issue #27 
  - Capitolo 3 – [Flusso di lavoro](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/3-Flusso_di_lavoro.md) Feedback: issue #24 
  - Capitolo 4 – [Tipi di file](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/4-Tipi_di_file.md) Feedback: issue #31 
  - Capitolo 5  – [Risorse esterne](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/5-Risorse_esterne.md) Feedback: issue #36

#### Prendere in carico il progetto:
* lascia un messaggio nella sezione Commenti, scrivendo di quale progetto vuoi occuparti (importante per avvisare gli altri che ci stai lavorando tu). Scrivi anche il tuo nome utente accanto al nome del progetto sulla lista qui in alto (usa l'icona della matita per modificare il testo)
* attieniti alle istruzioni del [capitolo 3](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/3-Flusso_di_lavoro.md) e del [capitolo 4](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/4-Tipi_di_file.md)
* per qualsiasi problema o domanda scrivi pure in questo issue
* quando la tua traduzione è pronta, lascia un commento nello issue per dare l'OK al QA
* rimani a disposizione per il QA, ti verrà chiesto se vuoi confermare le modifiche del revisore o meno
* e buona traduzione! 🎊 

## Link Utili
* [Web Localization Dashboard](https://l10n.mozilla-community.org/webdashboard/?locale=it) -- Lista dei progetti Pontoon con relative scadenze
* Server di test -- Per vedere dove andranno a finire le vostre traduzioni
  - per le singole pagine di [mozilla.org](https://l10n.mozilla-community.org/langchecker/?action=listpages) 
  - per [AMO](https://addons-dev.allizom.org/it/)
  - per [MDN](https://developer.allizom.org/it/)
* [mozilla.dev.l10n.web](https://groups.google.com/forum/#!forum/mozilla.dev.l10n.web) -- Un newsgroup internazionale di riferimento per le stringhe della settimana. Condivide informazioni sui progetti correnti, anche utile per porre domande e segnalare bug ecc.

❗️  La lista delle stringhe da tradurre viene aggiornata più volte nell'arco della settimana

**Comment by Sav22999** [comment]
Mi prenoto per Firefox Accounts :hand:

**Comment by Sav22999** [comment]
Potete procedere al QA di Firefox accounts

**Comment by kitsunenosaraT** [comment]
@Sav22999 [Il QA è servito](https://pontoon.mozilla.org/it/firefox-accounts/all-resources/?status=suggested&string=177562).
Alcune cose:
- Occhio ai plurali, es, "generati nuovi codici"
- Nella memoria di traduzione è stato usato "autenticazione **in** due fattori", ho uniformato
- Per quanto riguarda i codici "consumed", l'autenticazione in due fattori funziona così:
   a ogni accesso devi usare un'app di autenticazione sul cellulare per generare un codice da inserire    durante il login. Ma  in alcune occasioni potresti non essere in grado di accedere all'app (es. il cellulare ti è stato rubato).
   Per evitare che tu venga tagliato fuori in questo caso, all'attivazione dell'autenticazione in due fattori viene sempre generata una lista di codici di recupero, da stampare e tenere a portata di mano per i momenti in cui non puoi usare l'app.
Ogni codice di recupero si può utilizzare una volta sola, quindi quando lo utilizzi lo hai "consumato". Però credo che in questo caso la traduzione più comprensibile sia "utilizzato".
- Per la leggibilità della frase, in alcune stringhe ho messo il soggetto in cima, al posto del verbo:
es. È stata attivata l'autenticazione > L'autenticazione è stata attivata

A te la mossa!

**Comment by Sav22999** [comment]
A perfetto!

**Comment by Sav22999** [comment]
Io credevo che quel codice fosse "scaduto" tipo quando una sessione scade (dopo un tot di inattività...) chiedo scusa per la mia incomprensione

**Comment by eliogi** [comment]
Ciao a tutti,
faccio AMO Frontend.

**Comment by eliogi** [comment]
Ciao,
ecco i [suggerimenti](https://pontoon.mozilla.org/it/amo-frontend/all-resources/?status=missing%2Cfuzzy%2Csuggested&string=177574).

Alcune osservazioni:

- black menu: sinceramente ho pensato ad una specie di lista nera, poi volevo lasciarlo non tradotto, ma in italiano non si può sentire così... ho tradotto menù nero, anche se è brutto. Su transvision, non c'è nulla
- honey: ho lasciato così... cosa vuol dire miele? in che contesto sarebbe usato?

A parte questo mi affido al vostro QA.

Elio.

**Comment by kitsunenosaraT** [comment]
Grazie @eliogi 
[Il QA](https://pontoon.mozilla.org/it/amo-frontend/all-resources/?status=missing%2Cfuzzy%2Csuggested&string=177575)
- Black Menu for Google(tm) e Honey sono in realtà nomi dei componenti aggiuntivi pubblicizzati questa settimana, quindi non vanno tradotti.

Piccolo trucco: gli aggiornamenti di AMO Frontend riguardano spesso i componenti aggiuntivi del momento, quindi quando vedi nomi strani o fuori posto, insospettisciti!
Ho appunto messo nella sezione Link Utili in cima allo issue il sito di test per [AMO](https://addons-dev.allizom.org/it/). Di solito puoi vedere le stringhe nuove lì, oppure nel menu di Firefox > Gestione componenti aggiuntive > Esplora

- Nota da "nazista della grammatica" su *social media*. *Media* è una parola plurale, il singolare è *medium*. Quindi o si usa **i** social media al plurale o si dice **il** social medium (personalmente lo sconsiglierei per il semplice fatto che non lo ho mai visto usare).

- "coupon code": forse ["codice coupon"](https://www.google.it/search?client=firefox-b&dcr=0&ei=UEfDWuKGD4SLU4mpqNAK&q=Codice+coupon&oq=Codice+coupon&gs_l=psy-ab.3..0l10.2160.5522.0.6216.9.6.0.3.3.0.128.564.5j1.6.0....0...1c.1.64.psy-ab..0.9.580...0i67k1.0.RKSI2pNNnA8) o "codice sconto" sono più usati nello e-commerce? Buono mi dà più l'idea di un pezzo di carta fisico da spendere nei supermercati o simili.

- Vista una descrizione più estesa di [SHINE](https://addons-dev.allizom.org/it/firefox/addon/shine-for-reddit/"), mi sembra che più che semplici motivi, si parli proprio di modificare l'aspetto dell'interfaccia.

- Le ultime due stringhe che iniziano con "Access…" fanno parte della lista di permessi che richiede l'app (vedi i commenti della stringa), quindi ho adattato tempo verbale e persona alla frase "Questa app richiede il permesso di:"

A te la mossa!

**Comment by eliogi** [comment]
Ciao @kitsunenosaraT .

Ok, rispondendo punto per punto.
- su social media, nulla da dire. Errore mio. Approvato.
- Black Menu for Google: siamo sicuri di voler usare quel "for" ? E' proprio tutto il nome del componente aggiuntivo ? 
- ok per codice coupon. Ho corretto dimmi che ne pensi.

Queste sono le stringhe rimaste in sospeso: https://pontoon.mozilla.org/it/amo-frontend/all-resources/?status=suggested&string=177585

Che ne pensi?

**Comment by kitsunenosaraT** [comment]
Grazie per aver corretto.
> Black Menu for Google: siamo sicuri di voler usare quel "for" ? E' proprio tutto il nome del componente aggiuntivo ?

[Direi proprio di sì](https://addons-dev.allizom.org/it/firefox/addon/black-menu-for-google/)

**Comment by eliogi** [comment]
Ok, c'è anche il TM.

Approvato tutto. 100 %.
Grazie mille.

**Comment by kitsunenosaraT** [comment]
Sono spuntate altre 5 fuzzy per AMO Frontend.

**Comment by eliogi** [comment]
Ciao mi prendo le 5 fuzzi di AMO Frontend. Lo faccio per due ragioni: la prima è che non ci sarà Saverio ad aiutarci in questi giorni e due continuo il lavoro fatto pochi giorni fa su AMO Frontend appunto.

**Comment by eliogi** [comment]
Fatto: [eccolo](https://pontoon.mozilla.org/it/amo-frontend/all-resources/?status=suggested&string=177735).
"Search Tool": lasciato così in virtù che potrebbe essere il nome di un componente aggiuntivo (che ho provato a cercare e non ho trovato ovviamente 😞 ).
"Rating": ho tradotto con "voto", anche se "valutazione" non mi dispiaceva, ma forse "votare" rende meglio. Unica corrispondenza su transvision è Rate-> Voto.

**Comment by kitsunenosaraT** [comment]
@eliogi [Ecco il QA](https://pontoon.mozilla.org/it/amo-frontend/all-resources/?status=suggested&string=177734)

Alle prime due stringhe ho aggiunto "dati utente". Parlando di permessi, sembra naturale che si riferisca ai dati personali, però penso che quando si tratta di privacy sia meglio specificare.

Search Tool: guardando i commenti (#: src/amo/components/SearchFilters/index.js:106) sembra più un componente del sito di AMO, nello specifico l'interfaccia di ricerca, piuttosto che un componente aggiuntivo.

"Rating" nel caso dei componenti aggiuntivi è "valutazione". Voto= do il mio voto a un componente invece che all'altro, per esempio in un concorso per il miglior componente aggiuntivo. Valutazione = esprimo il mio giudizio su un componente aggiuntivo (numero stelle+ recensione)

Scusa se sono un po' sbrigativa, ma devo correre via.
A te la mossa, leggerò i tuoi commenti appena torno!

**Comment by eliogi** [comment]
Ciao @kitsunenosaraT ,
ho approvato tutti i commenti. Mi sembra tutto regolare.
Solo su Votazione e Valutazione una nota: in realtà avevo pensato anche io a questa interpretazione, ma poi mi sono bloccato perche valutazione mi sembrava un'esperienza un po' diversa. Ma poi leggendo il tuo commento, mi sembra più coerente rispetto a votazione. 100%. Yep.

**Comment by kitsunenosaraT** [comment]
Grazie 1000 @eliogi ! Anche questa settimana AMO Frontend è salvo 😉

**Comment by eliogi** [comment]
Grazie a te Sara :)

**Comment by eliogi** [comment]
Prendo MDN

**Comment by eliogi** [comment]
Fatto, potete procedere al [QA](https://pontoon.mozilla.org/it/mdn/all-resources/?status=missing%2Cfuzzy%2Csuggested&string=177819).

**Comment by kitsunenosaraT** [comment]
Grazie, accettate 👍

**Comment by eliogi** [comment]
Grazie mille.

**Comment by kitsunenosaraT** [comment]
Prodi picciotti, chiudo questo issue completato grazie ai vostri sforzi e ne apro uno nuovo per la prossima settimana.
Buona domenica! 🏄
