### ISSUE TITLE
Internet Health Report Flyer

### ISSUE THREAD

**Issue by kitsunenosaraT** [MozillaItalia/Mozilla-Italia-l10n-guide#97]
Questo issue fa parte del progetto di localizzazione di [Internet Health Report](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/projects/6).

In particolare è rivolto a chi desidera tradurre in italiano il volantino di questa iniziativa Mozilla.
 
## Informazioni sul file da tradurre
**Nome**: 2018 Internet Health Report Flyer
**File**: [Google Drive](https://docs.google.com/document/d/1VYQ902GdNG5haD-yLlaFhT85nDzqSDogpsXL_m-Evkc/edit) | [Testo in formato markdown](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/InternetHealthReport/IHR_flyer.md) (no immagini, formattazione semplice)
**Tipo**: google docs oppure markdown
**Strumento di traduzione**: A scelta:
- scaricare il file e tradurlo con il proprio editor di testo preferito. Dal menu di Drive: File > Download as > scegli il formato
- caricare il file sul proprio spazio di archiviazione Google Drive e tradurlo lì. Dal menu di Drive: File > Add to my Drive
- scaricare il [testo in formato markdown](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/InternetHealthReport/IHR_flyer.md) e tradurlo con il proprio editor di testo preferito.

#### Prima di iniziare:
* **Leggi i capitoli della guida**, se lo desideri, lascia un feedback nel relativo issue:
  - Capitolo 1 – [Buone norme di traduzione tecnica](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/1-Buone_norme_di_traduzione.md) Feedback: issue #91 
  - Capitolo 2 – [Linee guida di Mozilla Italia](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/2-Linee_guida_di_Mozilla_Italia.md) Feedback: issue #27 
  - Capitolo 3 – [Flusso di lavoro](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/3-Flusso_di_lavoro.md) Feedback: issue #24 
 ❕  Leggi solo la parte introduttiva riguardo al ciclo traduzione > revisione, dal  momento che in questo progetto non faremo uso degli strumenti descritti nel resto del capitolo.
  - Capitolo 4 – [Tipi di file](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/4-Tipi_di_file.md) Feedback: issue #31 
  - Capitolo 5  – [Risorse esterne](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/5-Risorse_esterne.md) Feedback: issue #36

#### Prendere in carico il progetto:
* lascia un messaggio nella sezione Commenti, chiedendo che ti venga assegnato il progetto.
* attieniti alle indicazioni della guida e, in particolare, fai uso delle [memorie di traduzione di Mozilla](https://transvision.mozfr.org/) per verificare come sono stati tradotti in precedenza i termini. Per le tematiche come *decentralization*, *openness*, *web literacy* ecc. dai un'occhiata a come sono stati tradotti sul sito [Salute di Internet](https://www.mozilla.org/it/internet-health/)
* per qualsiasi problema o domanda scrivi pure in questo issue
* quando la tua traduzione è pronta, lascia un commento nello issue e allega direttamente il file tradotto (trascina il documento nel riquadro del commento), oppure caricalo su un servizio cloud (Google Drive, Dropbox ecc.) e inserisci qui il link.
* **rimani a disposizione per il QA**, ti verrà chiesto se vuoi confermare le modifiche del revisore o meno
* e buona traduzione! 🎊 

## Link Utili
* La [pagina wiki](https://wiki.mozilla.org/Internet_Health_Report) di Internet Health Report
* La [memoria di traduzione](https://transvision.mozfr.org/) di Mozilla, da consultare per garantire consistenza terminologica
* Il sito [Salute di Internet](https://www.mozilla.org/it/internet-health/), tradotto dai volontari di Mozilla Italia, che parla delle stesse tematiche affrontate in Internet Health Report.

**Comment by kitsunenosaraT** [comment]
Tradotto dall'utente @joyrom nella pull request #103.

**Comment by kitsunenosaraT** [comment]
@joyrom Mira l'opera tua 🎉 
https://docs.google.com/document/d/1VLkPseWAeVgq8Chnd-V7ooV1b0l8J7Y2W--KDzPaK7I/edit?usp=sharing

**Comment by Mte90** [comment]
Manca l'accesso alle slide :-)

**Comment by kitsunenosaraT** [comment]
Pardon, non mi ero accorta che i permessi erano solo per quelli con un account Mozilla.
Adesso i permessi di visualizzazione sono per "Anyone with the link".
Comunque, mano a mano che i file saranno pronti, aggiornerò [questo documento](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/InternetHealthReport/README.md) con i link alle versioni italiane. Poi ovviamente siete liberi di copiarli e archiviarli dove preferite.

**Comment by Mte90** [comment]
Il documento mi sembra perfetto :-)

**Comment by kitsunenosaraT** [comment]
Perfetto,chiudo lo issue. Il link al file italiano lo trovate [nell'indice](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/InternetHealthReport/README.md)
P.s. Se qualcuno con accesso alla wiki di Mozilla vuole, può caricarlo sulla [pagina di IHR](https://wiki.mozilla.org/Internet_Health_Report) con gli altri asset…

**Comment by Sav22999** [comment]
Esatto
________________________________
