### ISSUE TITLE
Weekly Translations of Pontoon Projects (week 15)

### ISSUE THREAD

**Issue by kitsunenosaraT** [MozillaItalia/Mozilla-Italia-l10n-guide#98]
# Stringhe della settimana
- [x] [Test Pilot Website](https://pontoon.mozilla.org/it/test-pilot-website/all-resources/?status=missing%2Cfuzzy%2Csuggested&string=177832)  10 stringhe - @Sav22999
- [x] [Focus for Android](https://pontoon.mozilla.org/it/focus-for-android/all-resources/?status=missing%2Cfuzzy%2Csuggested&string=177868) 3 stringhe - @Sav22999
- [x] [AMO Frontend](https://pontoon.mozilla.org/it/amo-frontend/all-resources/?status=missing%2Cfuzzy%2Csuggested&string=177866) 1 fuzzy @AndyUrbi
- [x] [Firefox Screenshots](https://pontoon.mozilla.org/it/firefox-screenshots/all-resources/?status=translated&time=201804120515-201804130515&author=francesco.lodolo%40mozillaitalia.org&string=178075) @flod 
- [x] [Focus for Android](https://pontoon.mozilla.org/it/focus-for-android/all-resources/?status=missing%2Csuggested&string=177868) 8 stringhe - @Sav22999
- [x] [mozilla.org](https://pontoon.mozilla.org/it/mozillaorg/all-resources/?status=missing%2Csuggested&string=178061) 16 stringhe - @Sav22999

## Informazioni sul progetto
Questo issue serve a gestire le traduzioni dei siti Mozilla sulla piattaforma [Pontoon](https://pontoon.mozilla.org/it/).

Ogni settimana uscirà un nuovo issue con una lista dei progetti che contengono stringhe mancanti. Puoi sempre trovare lo issue della settimana corrente sulla [bacheca del progetto](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/projects/5).
Chi vuole farsi avanti, a seconda della propria disponibilità, si "prenoterà" per le stringhe.
Questo per organizzare meglio l'attività di traduzione ed evitare che più persone lavorino sulle stesse stringhe.

#### Prima di iniziare:
* [Registrati](https://accounts.firefox.com/oauth/signin?response_type=code&scope=profile%3Auid%20profile%3Aemail%20profile%3Adisplay_name%20profile%3Auid%20profile%3Adisplay_name%20profile%3Aemail&state=yrvTUh3o4F4c&redirect_uri=https%3A%2F%2Fpontoon.mozilla.org%2Faccounts%2Ffxa%2Flogin%2Fcallback%2F&client_id=76ab66239b5585ad) sulla piattaforma di traduzione Pontoon
  - (facoltativo) Installa il componente aggiuntivo [Pontoon Tools](https://addons.mozilla.org/it/firefox/addon/pontoon-tools/) per ricevere le notifiche delle stringhe mancanti in tempo reale (più altre chicche)
* **Leggi i capitoli della guida**, se lo desideri, lascia un feedback nel relativo issue:
  - Capitolo 1 – [Buone norme di traduzione tecnica](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/1-Buone_norme_di_traduzione.md) Feedback: issue #91 
  - Capitolo 2 – [Linee guida di Mozilla Italia](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/2-Linee_guida_di_Mozilla_Italia.md) Feedback: issue #27 
  - Capitolo 3 – [Flusso di lavoro](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/3-Flusso_di_lavoro.md) Feedback: issue #24 
  - Capitolo 4 – [Tipi di file](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/4-Tipi_di_file.md) Feedback: issue #31 
  - Capitolo 5  – [Risorse esterne](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/5-Risorse_esterne.md) Feedback: issue #36

#### Prendere in carico il progetto:
* lascia un messaggio nella sezione Commenti, scrivendo di quale progetto vuoi occuparti (importante per avvisare gli altri che ci stai lavorando tu). Scrivi anche il tuo nome utente accanto al nome del progetto sulla lista qui in alto (usa l'icona della matita per modificare il testo)
* attieniti alle istruzioni del [capitolo 3](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/3-Flusso_di_lavoro.md) e del [capitolo 4](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/4-Tipi_di_file.md)
* per qualsiasi problema o domanda scrivi pure in questo issue
* quando la tua traduzione è pronta, lascia un commento nello issue per dare l'OK al QA
* rimani a disposizione per il QA, ti verrà chiesto se vuoi confermare le modifiche del revisore o meno
* e buona traduzione! 🎊 

## Link Utili
* [Web Localization Dashboard](https://l10n.mozilla-community.org/webdashboard/?locale=it) -- Lista dei progetti Pontoon con relative scadenze
* Server di test -- Per vedere dove andranno a finire le vostre traduzioni
  - per le singole pagine di [mozilla.org](https://l10n.mozilla-community.org/langchecker/?action=listpages) 
  - per [AMO](https://addons-dev.allizom.org/it/)
  - per [MDN](https://developer.allizom.org/it/)
* [mozilla.dev.l10n.web](https://groups.google.com/forum/#!forum/mozilla.dev.l10n.web) -- Un newsgroup internazionale di riferimento per le stringhe della settimana. Condivide informazioni sui progetti correnti, anche utile per porre domande e segnalare bug ecc.

❗️  La lista delle stringhe da tradurre viene aggiornata più volte nell'arco della settimana

**Comment by kitsunenosaraT** [comment]
Apriamo la settimana con 10 stringhe per il sito di Test Pilot ([sito di test](https://testpilot-l10n.dev.mozaws.net/))

**Comment by Sav22999** [comment]
Mi prenoto per test pilot

**Comment by Sav22999** [comment]
Potete procedere al QA di test pilot :v:

**Comment by kitsunenosaraT** [comment]
Eccoci qui con il [QA di Test Pilot](https://pontoon.mozilla.org/it/test-pilot-website/all-resources/?status=suggested&string=177824).

Per quanto riguarda Software Engineer: questa stringa appartiene alla pagina di chi ha collaborato allo sviluppo del componente aggiuntivo. In questo caso si sta parlando, più che di una professione, del ruolo all'interno del team di collaboratori. Quindi direi che ci starebbe meglio un più generico "Sviluppatore".

A te la mossa.

**Comment by Sav22999** [comment]
Non so.. Come meglio credi tu. Magari è meglio chiedere una consultazione a Mte o a Edov... sviluppatore mi sembra troppo generico... :thinking:

**Comment by flodolo** [comment]
Nota: finora tutti i "job title" di Test Pilot sono stati lasciati in inglese.

**Comment by Sav22999** [comment]
Li lasciamo in inglese quindi? @flodolo

**Comment by flodolo** [comment]
Sì, oppure li dobbiamo tradurre tutti, e auguri :)

**Comment by Sav22999** [comment]
@kitsunenosaraT lascio a te la decisione (nel frattempo puoi procedere nuovamente al QA, ho corretto un "hai" in più e **scusa** per gli errori di battitura, non so come un "cine" mi sia sfuggito (era "come"))
Have a nice day guys!

**Comment by kitsunenosaraT** [comment]
@Sav22999 Scusa il ritardo, ho accettato. Grazie per aver ritrovato quello "hai" di troppo che mi era sfuggito :wink:
@flodolo Ho mantenuto i job titles in inglese.

Aggiornamento: poche nuove stringhe per Focus e Frontend.

**Comment by AndyUrbi** [comment]
La frase da tradurre di AMO mi sembra vada bene visto che proxy resta invariato.
Tra l'altro ho visto che era la stringa mancante nell'issue 64 per cui quello si potrebbe chiudere.

**Comment by AndyUrbi** [comment]
Per quanto riguarda l'issue 93 sembra che manchino 15 stringhe. Invece come missing non resta nulla ma come suggested è nuovamente la stessa stringa.

**Comment by Sav22999** [comment]
Mi prenoto per mozilla. Sara avvisami se posso farne anche altri

**Comment by Sav22999** [comment]
Potete procedere al QA di mozilla.org

**Comment by kitsunenosaraT** [comment]
@AndyUrbi Grazie per la fuzzy di Amo Frontend, la ho accettata.
>La frase da tradurre di AMO mi sembra vada bene visto che proxy resta invariato.
>Tra l'altro ho visto che era la stringa mancante nell'issue 64 per cui quello si potrebbe chiudere.
>Per quanto riguarda l'issue 93 sembra che manchino 15 stringhe. Invece come missing non resta nulla ma come suggested è nuovamente la stessa stringa.

Come mai rivanghi i vecchi issue? Il #64 e il #93 sono entrambi chiusi.
Per quanto riguarda i link, filtrano automaticamente le stringhe ogni volta che ci clicchi sopra, aggiornando i risultati.
Quindi se clicchi sul link di un vecchio issue, vedrai automaticamente i risultati di un issue nuovo.

@Sav22999 il tuo QA arriva /tono minaccioso/ 😋 
Intanto, sì, se hai voglia e tempo puoi fare altre stringhe. È un momento in cui c'è un sacco di lavoro da fare, per cui non ha senso adesso stare a razionare le stringhe.

**Comment by Sav22999** [comment]
Mi sono preso entrambi i Focus for Android, così terminiamo anche questa settimana (chi volesse tradurre qualcosa c'è l'articolo IHR

**Comment by Sav22999** [comment]
Potete procedere al QA di firefox android

**Comment by flodolo** [comment]
> Potete procedere al QA di firefox android

Lasciato qualche suggerimento e approvato il resto.

"Add custom URL" è un pulsante, e avevamo dovuto tagliarlo drasticamente in iOS. Sì si scrive con l'accento ;-)

**Comment by Sav22999** [comment]
Sisi, so che che si scrive con l'accento, pensavo che andasse ugualmente bene. Grazie :)

**Comment by kitsunenosaraT** [comment]
@Sav22999 ci siamo!
Intanto, per avere una visione d'insieme, questo è il [minisito](https://addons.mozilla.org/it/firefox/addon/facebook-container/) che hai tradotto.
Promemoria: la lista delle pagine di test per mozilla.org è riportata nel primo messaggio dello issue, sezione Link Utili

Molte stringhe le ho rimodellate in italiano perché l'inglese era pieno di ripetizioni (in particolare un continuo ripetere la parola Facebook )

> Facebook. Well contained. Keep the rest of your life to yourself.

Qui ho messo delle proposte. Penso che essere letterali non sia necessario.
Il nome del componente aggiuntivo è solo [Facebook Container](https://addons.mozilla.org/it/firefox/addon/facebook-container/), quindi possiamo tradurre il "for Firefox" e "Extension".

Firefox Focus, the privacy browser > lo slogan italiano è "il browser riservato".
Tra parentesi, "web browser" in italiano sarebbe "browser web" (seguiamo l'ordine italiano sostantivo > aggettivo), ma in realtà nella maggior parte dei casi "web" si può omettere, in quanto in Italia quando si parla di *browser* al 90% si intende quello web.

La "blue tab" che dovrebbe indicare l'entrata in funzione dell'estensione, è in realtà una sottile linea blu sotto il titolo della scheda (vedi video sul sito di test per credere). Siccome io guardavo e non capivo dove cavolo era 'sta scheda blu, questa cosa mi ha confuso, e penso potrebbe confondere anche altri utenti, opto per una descrizione un po' più precisa.

**Comment by flodolo** [comment]
> Lasciato qualche suggerimento e approvato il resto.

Giusto per assicurarmi che siamo sulla stessa pagina: qualcuno dovrà approvare uno dei suggerimenti

**Comment by Sav22999** [comment]
Ho accettato la maggior parte delle stringhe. Ho corretto una stringa (sara ti era scappato un "le" in più)

**Comment by kitsunenosaraT** [comment]
E bravo @Sav22999 che mi fai anche da revisore 😁 
Siamo al 100% A te l'onore di ticchettare le caselle in cima allo issue.

**Comment by Sav22999** [comment]
Non volevo assolutamente mancare di rispetto al tuo incarico e alla tua persona, sia chiaro

**Comment by AndyUrbi** [comment]
@kitsunenosaraT > Come mai rivanghi i vecchi issue? Il #64 e il #93 sono entrambi chiusi.
Solamente perché mancavano i check per completarli. In effetti non trovo la chiusura da parte tua in nessuno dei 2, però ammetto che sto andando in confusione dato che la 64 era iniziata nel 2017!

**Comment by kitsunenosaraT** [comment]
@Sav22999 
>Non volevo assolutamente mancare di rispetto al tuo incarico e alla tua persona, sia chiaro

Sono orgogliosa di te perché hai riletto con attenzione la correzione invece di accettarla indiscriminatamente. E se la prossima volta che trovi un errore in un mio testo, non me lo correggi, mi offendo di brutto. Sia chiaro! 😉 

@AndyUrbi 
Ora le ho ticchettate, grazie.
Ma, anche se non c'è il mio messaggio esplicito "Ciao ragazzi, chiudo lo issue", puoi vedere che è chiuso dal tag rosso sotto lo issue e dal messaggio di sistema " kitsunenosaraT closed this on [data]".

Per non perdere tempo navigando tra centinaia di issue vecchi, quando vuoi vedere le stringhe rimaste da tradurre fai riferimento *unicamente* allo issue della settimana corrente, che si trova sempre nella [pagina del progetto](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/projects/5) sotto la colonna **Current week**.
(Abbiamo ideato questo sistema apposta per evitare situazioni di questo tipo).

**Comment by kitsunenosaraT** [comment]
Scusate, nel commento precedente avevo sbagliato a darvi l'URL del minisito per Facebook Container. (Ora lo ho corretto).
@Sav22999 [Ammira la tua opera!](https://www-dev.allizom.org/it/firefox/facebookcontainer/)
🎉

**Comment by Sav22999** [comment]
Bella! L'ho anche installata, anche uso raramente i social media :joy:

**Comment by AndyUrbi** [comment]
@kitsunenosaraT 
Non ti preoccupare, non è che perdo tempo a scartabellare i vecchi issue. Ma è molto semplice accorgersene quando vedi i numeri che non corrispondono, per cui in quei pochi casi cerco di capire a cosa è dovuta la differenza: tutto qui.

A proposito: auguri di buon compleanno!

**Comment by kitsunenosaraT** [comment]
@AndyUrbi grazie in ritardo per gli auguri 🙏 
Se per te non è un problema controllare gli issue vecchi, meglio così. Basta che siamo tutti "sulla stessa pagina" riguardo cosa c'è da tradurre.

Miei prodi, è lunedì quindi chiudo questo issue, anche se non ci sono ancora stringhe nuove per aprirne uno nuovo. Quando ci sarà qualcosa da tradurre, troverete il nuovo issue come al solito nella [pagina del progetto Pontoon](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/projects/5), sotto la colonna **Current Week**.
Buona settimana!
